export type LeafCondition = { field: string; operator?: "equals" | "not_equals" | "in" | "not_in" | "exists" | "gt" | "gte" | "lt" | "lte" | "contains" | "not_contains" | "starts_with" | "ends_with" | "matches" | "before" | "after" | "between" | "is_empty"; value?: unknown };
export type Condition = LeafCondition | { operator: "AND" | "OR" | "NOT"; conditions: Condition[] };
function valueAt(input: unknown, path: string): unknown { return path.split(".").reduce<unknown>((value, key) => value && typeof value === "object" ? (value as Record<string, unknown>)[key] : undefined, input); }
function comparable(value: unknown): number | string { if (value instanceof Date) return value.getTime(); if (typeof value === "number") return value; if (typeof value === "string" && /^\d{4}-\d{2}-\d{2}(?:T|$)/.test(value)) { const parsed = Date.parse(value); if (!Number.isNaN(parsed)) return parsed; } return String(value ?? ""); }
export function evaluateCondition(condition: Condition, input: unknown): boolean {
  if ("conditions" in condition) { if (condition.operator === "NOT") return condition.conditions.length === 1 && !evaluateCondition(condition.conditions[0]!, input); return condition.operator === "AND" ? condition.conditions.every((item) => evaluateCondition(item, input)) : condition.conditions.some((item) => evaluateCondition(item, input)); }
  const actual = valueAt(input, condition.field); const operator = condition.operator ?? "equals";
  switch (operator) { case "equals": return actual === condition.value; case "not_equals": return actual !== condition.value; case "exists": return condition.value === false ? actual == null : actual != null; case "is_empty": return actual == null || actual === "" || (Array.isArray(actual) && actual.length === 0); case "in": return Array.isArray(condition.value) && condition.value.includes(actual); case "not_in": return Array.isArray(condition.value) && !condition.value.includes(actual); case "gt": case "after": return comparable(actual) > comparable(condition.value); case "gte": return comparable(actual) >= comparable(condition.value); case "lt": case "before": return comparable(actual) < comparable(condition.value); case "lte": return comparable(actual) <= comparable(condition.value); case "between": return Array.isArray(condition.value) && condition.value.length === 2 && comparable(actual) >= comparable(condition.value[0]) && comparable(actual) <= comparable(condition.value[1]); case "contains": return Array.isArray(actual) ? actual.includes(condition.value) : String(actual ?? "").includes(String(condition.value ?? "")); case "not_contains": return Array.isArray(actual) ? !actual.includes(condition.value) : !String(actual ?? "").includes(String(condition.value ?? "")); case "starts_with": return String(actual ?? "").startsWith(String(condition.value ?? "")); case "ends_with": return String(actual ?? "").endsWith(String(condition.value ?? "")); case "matches": try { return new RegExp(String(condition.value ?? ""), "u").test(String(actual ?? "")); } catch { return false; } }
}

export function isWithinBusinessHours(now: Date, timezone: string, workingHours: Record<string, { start: string; end: string } | null>, holidays: readonly string[] = []) {
  const parts = Object.fromEntries(new Intl.DateTimeFormat("en-US", { timeZone: timezone, year: "numeric", month: "2-digit", day: "2-digit", weekday: "short", hour: "2-digit", minute: "2-digit", hourCycle: "h23" }).formatToParts(now).map((part) => [part.type, part.value]));
  const weekday = String(parts.weekday).toLowerCase(), current = `${parts.hour}:${parts.minute}`, date = `${parts.year}-${parts.month}-${parts.day}`; if (holidays.includes(date)) return false;
  const window = workingHours[weekday]; if (window && (window.start === window.end || (window.start < window.end ? current >= window.start && current < window.end : current >= window.start))) return true;
  const weekdays = ["sun","mon","tue","wed","thu","fri","sat"], previous = weekdays[(weekdays.indexOf(weekday) + 6) % 7]!, previousWindow = workingHours[previous];
  return Boolean(previousWindow && previousWindow.start > previousWindow.end && current < previousWindow.end);
}
