import { Prisma } from "@prisma/client";
import { prisma } from "../prisma.js";
import { registerAction, type ActionContext, type ActionResult } from "./actionRegistry.js";
import { recordOutboxEvent } from "../outbox.js";

export interface IdempotentActionGateway {
  execute(input: { context: ActionContext; config: Record<string, unknown>; idempotencyKey: string; signal: AbortSignal }): Promise<unknown>;
}
function target(config: Record<string, unknown>, context: ActionContext, entity: "customer" | "lead" | "appointment") { const input = context.input && typeof context.input === "object" ? context.input as Record<string, unknown> : {}; const hydrated = input[entity]; const event = input.event; return String(config.targetId ?? (hydrated && typeof hydrated === "object" ? (hydrated as Record<string, unknown>).id : undefined) ?? (event && typeof event === "object" ? (event as Record<string, unknown>).id : "")); }
function changes(config: Record<string, unknown>, allowed: readonly string[]) {
  const value = config.changes;
  if (!value || typeof value !== "object" || Array.isArray(value)) throw new Error("Action changes are required");
  const entries = Object.entries(value as Record<string, unknown>);
  if (!entries.length || entries.some(([key]) => !allowed.includes(key))) throw new Error("Action contains an unsupported update field");
  return Object.fromEntries(entries);
}
function eventContext(context: ActionContext) { const input = context.input && typeof context.input === "object" ? context.input as Record<string, unknown> : {}; const lineage = Array.isArray(input.automationLineage) ? input.automationLineage.map(String).slice(-50) : []; return { metadata: { automationLineage: lineage } as Prisma.InputJsonValue, correlationId: typeof input.correlationId === "string" ? input.correlationId : context.executionId }; }
async function assignedMember(businessId: string, value: unknown) { if (!value) return null; const id = String(value); const member = await prisma.businessMember.findFirst({ where: { id, businessId, status: "ACTIVE" }, select: { id: true, userId: true } }); if (!member) throw new Error("Assigned staff member is unavailable"); return member; }

export function registerDefaultActions(gateways: { messaging?: IdempotentActionGateway; ai?: IdempotentActionGateway } = {}) {
  registerAction("UPDATE_CUSTOMER", async (context, config) => { const id = target(config, context, "customer"); const data = changes(config, ["name", "email", "notes", "birthday", "anniversary", "customFields"]); await prisma.$transaction(async (tx) => { const result = await tx.customer.updateMany({ where: { id, businessId: context.businessId }, data }); if (!result.count) throw new Error("Customer target not found"); await recordOutboxEvent(tx, { dedupeKey: `${context.executionId}:${context.nodeId}:customer-updated`, aggregateType: "customer", aggregateId: id, eventType: "CustomerUpdated", tenantId: context.businessId, businessId: context.businessId, causationId: context.executionId, ...eventContext(context), payload: { id } }); }); return { output: { id } }; });
  registerAction("UPDATE_LEAD", async (context, config) => { const id = target(config, context, "lead"); const data = changes(config, ["serviceRequested", "urgency", "estimatedValue", "notes"]); await prisma.$transaction(async (tx) => { const result = await tx.lead.updateMany({ where: { id, businessId: context.businessId }, data }); if (!result.count) throw new Error("Lead target not found"); await recordOutboxEvent(tx, { dedupeKey: `${context.executionId}:${context.nodeId}:lead-updated`, aggregateType: "lead", aggregateId: id, eventType: "LeadUpdated", tenantId: context.businessId, businessId: context.businessId, causationId: context.executionId, ...eventContext(context), payload: { id } }); }); return { output: { id } }; });
  registerAction("UPDATE_APPOINTMENT", async (context, config) => { const id = target(config, context, "appointment"); const data = changes(config, ["notes", "reminderMinutes"]); await prisma.$transaction(async (tx) => { const result = await tx.appointment.updateMany({ where: { id, businessId: context.businessId }, data }); if (!result.count) throw new Error("Appointment target not found"); await recordOutboxEvent(tx, { dedupeKey: `${context.executionId}:${context.nodeId}:appointment-updated`, aggregateType: "appointment", aggregateId: id, eventType: "AppointmentUpdated", tenantId: context.businessId, businessId: context.businessId, causationId: context.executionId, ...eventContext(context), payload: { id } }); }); return { output: { id } }; });
  registerAction("CREATE_TASK", async (context, config) => { const member = await assignedMember(context.businessId, config.assignedMemberId); return { output: await prisma.automationTask.upsert({ where: { idempotencyKey: `${context.executionId}:${context.nodeId}` }, create: { idempotencyKey: `${context.executionId}:${context.nodeId}`, businessId: context.businessId, executionId: context.executionId, title: String(config.title ?? "Automation task"), description: config.description ? String(config.description) : null, assignedMemberId: member?.id, dueAt: config.dueAt ? new Date(String(config.dueAt)) : null }, update: {} }) }; });
  registerAction("ESCALATE", async (context, config) => { const member = await assignedMember(context.businessId, config.assignedMemberId); return { output: await prisma.automationTask.upsert({ where: { idempotencyKey: `${context.executionId}:${context.nodeId}` }, create: { idempotencyKey: `${context.executionId}:${context.nodeId}`, businessId: context.businessId, executionId: context.executionId, title: String(config.title ?? "Automation escalation"), description: config.description ? String(config.description) : null, assignedMemberId: member?.id, status: "ESCALATED", dueAt: new Date() }, update: {} }) }; });
  registerAction("ASSIGN_STAFF", async (context, config) => { const appointmentId = target(config, context, "appointment"); const memberId = String(config.memberId ?? ""); await prisma.$transaction(async (tx) => { const member = await tx.businessMember.findFirst({ where: { id: memberId, businessId: context.businessId, status: "ACTIVE" } }); if (!member) throw new Error("Assigned staff member is unavailable"); const result = await tx.appointment.updateMany({ where: { id: appointmentId, businessId: context.businessId }, data: { assignedMemberId: memberId } }); if (!result.count) throw new Error("Appointment target not found"); await recordOutboxEvent(tx, { dedupeKey: `${context.executionId}:${context.nodeId}:appointment-assigned`, aggregateType: "appointment", aggregateId: appointmentId, eventType: "AppointmentUpdated", tenantId: context.businessId, businessId: context.businessId, causationId: context.executionId, ...eventContext(context), payload: { id: appointmentId, assignedMemberId: memberId } }); }); return { output: { appointmentId, memberId } }; });
  registerAction("CREATE_NOTIFICATION", async (context, config) => { const key = context.idempotencyKey; const configuredMember = await assignedMember(context.businessId, config.assignedMemberId); const configuredUser = config.userId ? await prisma.businessMember.findFirst({ where: { businessId: context.businessId, userId: String(config.userId), status: "ACTIVE" }, select: { userId: true } }) : null; if (config.userId && !configuredUser) throw new Error("Notification recipient is unavailable"); const business = await prisma.business.findUniqueOrThrow({ where: { id: context.businessId }, select: { ownerId: true } }); const recipientUserId = configuredUser?.userId ?? configuredMember?.userId ?? business.ownerId; const record = await prisma.$transaction(async (tx) => { const task = await tx.automationTask.upsert({ where: { idempotencyKey: key }, create: { idempotencyKey: key, businessId: context.businessId, executionId: context.executionId, title: String(config.title ?? "Automation update"), description: String(config.body ?? "A workflow needs your attention"), assignedMemberId: configuredMember?.id, status: "NOTIFICATION_QUEUED" }, update: {} }); await recordOutboxEvent(tx, { dedupeKey: `${key}:notification`, aggregateType: "workflow_execution", aggregateId: context.executionId, eventType: "InternalNotificationRequested", tenantId: context.businessId, businessId: context.businessId, causationId: context.executionId, payload: { recipientUserId, title: task.title, body: task.description, executionId: context.executionId, idempotencyKey: key } }); return task; }); return { output: { notificationId: record.id, queued: true } }; });
  registerAction("PAUSE_WORKFLOW", async (): Promise<ActionResult> => ({ directive: "PAUSE" })); registerAction("RESUME_WORKFLOW", async (context, config) => { const targetId = String(config.executionId ?? context.executionId); const resumed = await prisma.$transaction(async (tx) => { const result = await tx.workflowExecution.updateMany({ where: { id: targetId, businessId: context.businessId, status: "PAUSED" }, data: { status: "PENDING", nextAttemptAt: new Date(), scheduledFor: new Date(), lastError: null } }); if (result.count) await tx.workflowExecutionEvent.create({ data: { executionId: targetId, businessId: context.businessId, type: "RESUMED_BY_WORKFLOW", nodeId: context.nodeId, metadata: { sourceExecutionId: context.executionId } } }); return result.count > 0; }); return { output: { executionId: targetId, resumed } }; }); registerAction("COMPLETE_WORKFLOW", async (): Promise<ActionResult> => ({ directive: "COMPLETE" }));
  registerAction("INVOKE_MESSAGING", async (context, config) => { if (!gateways.messaging) throw new Error("Messaging gateway is not configured"); return { output: await gateways.messaging.execute({ context, config, idempotencyKey: context.idempotencyKey, signal: context.signal }) }; });
  registerAction("INVOKE_AI", async (context, config) => { if (!gateways.ai) throw new Error("AI gateway is not configured"); return { output: await gateways.ai.execute({ context, config, idempotencyKey: context.idempotencyKey, signal: context.signal }) }; });
}
