import { ACTION_NAMES, validateActionConfig } from "./actionRegistry.js";
import { SUPPORTED_TRIGGERS, type WorkflowDefinition } from "./workflowContracts.js";
const DELAY_UNITS = new Set(["seconds","minutes","hours","days","weeks","months","business_days","business_hours"]);
const MAX_DELAY: Record<string, number> = { seconds: 31_536_000, minutes: 525_600, hours: 8_760, days: 365, weeks: 52, months: 12, business_days: 260, business_hours: 2_080 };
const CONDITION_OPERATORS = new Set(["equals","not_equals","in","not_in","exists","gt","gte","lt","lte","contains","not_contains","starts_with","ends_with","matches","before","after","between","is_empty"]);
function validateCondition(value: unknown, path: string, errors: string[]): void { if (!value || typeof value !== "object" || Array.isArray(value)) { errors.push(`Invalid condition at ${path}`); return; } const condition = value as Record<string, unknown>; if (condition.operator === "AND" || condition.operator === "OR" || condition.operator === "NOT") { if (!Array.isArray(condition.conditions) || !condition.conditions.length) errors.push(`Condition group at ${path} is empty`); else if (condition.operator === "NOT" && condition.conditions.length !== 1) errors.push(`NOT condition at ${path} requires exactly one child`); else condition.conditions.forEach((item, index) => validateCondition(item, `${path}.${index}`, errors)); return; } if (typeof condition.field !== "string" || !condition.field.trim()) errors.push(`Condition field is missing at ${path}`); if (condition.operator !== undefined && !CONDITION_OPERATORS.has(String(condition.operator))) errors.push(`Unsupported condition operator at ${path}`); }
export function validateWorkflow(definition: WorkflowDefinition) {
  const errors: string[] = []; if (!definition || typeof definition !== "object") return { valid: false, errors: ["Definition is required"] };
  if (!SUPPORTED_TRIGGERS.includes(definition.trigger?.type as (typeof SUPPORTED_TRIGGERS)[number])) errors.push(`Unsupported trigger: ${definition.trigger?.type}`);
  if (!Array.isArray(definition.nodes) || definition.nodes.length === 0) errors.push("At least one workflow node is required"); if (definition.nodes.length > 250) errors.push("Workflow exceeds the 250-node limit");
  const ids = new Set<string>(); const graph = new Map<string, string[]>();
  for (const node of definition.nodes ?? []) { if (!node.id || ids.has(node.id)) errors.push(`Duplicate or missing node id: ${node.id}`); ids.add(node.id); graph.set(node.id, node.next ?? []); if (!["condition","delay","action","branch"].includes(node.type)) errors.push(`Unsupported node type: ${node.type}`); if (node.type === "action" && !ACTION_NAMES.includes(String(node.config.action) as (typeof ACTION_NAMES)[number])) errors.push(`Unsupported action: ${String(node.config.action)}`); else if (node.type === "action") for (const error of validateActionConfig(String(node.config.action), node.config)) errors.push(`Invalid action ${node.id}: ${error}`); if (node.type === "action" && (node.next?.length ?? 0) > 1) errors.push(`Action node ${node.id} can have at most one successor`); if (node.type === "delay" && (!Number.isFinite(Number(node.config.amount)) || Number(node.config.amount) <= 0 || !DELAY_UNITS.has(String(node.config.unit)))) errors.push(`Invalid delay on node: ${node.id}`); if (node.type === "delay" && (node.next?.length ?? 0) > 1) errors.push(`Delay node ${node.id} can have at most one successor`); if (node.type === "condition" || node.type === "branch") validateCondition(node.config.condition, node.id, errors); if ((node.type === "condition" || node.type === "branch") && (node.next?.length ?? 0) !== 2) errors.push(`Condition node ${node.id} requires true and false branches`); }
  for (const node of definition.nodes ?? []) if (node.type === "delay") { const amount = Number(node.config.amount); const unit = String(node.config.unit); if (amount > (MAX_DELAY[unit] ?? 0) || (["months","business_days"].includes(unit) && !Number.isInteger(amount))) errors.push(`Invalid delay on node: ${node.id}`); }
  const start = definition.startNodeId ?? definition.nodes?.[0]?.id; if (start && !ids.has(start)) errors.push(`Invalid start node: ${start}`);
  for (const [id, edges] of graph) for (const edge of edges) if (!ids.has(edge)) errors.push(`Invalid node reference from ${id}: ${edge}`);
  const visiting = new Set<string>(); const visited = new Set<string>(); const walk = (id: string): void => { if (visiting.has(id)) { errors.push(`Circular workflow detected at node: ${id}`); return; } if (visited.has(id)) return; visiting.add(id); for (const edge of graph.get(id) ?? []) if (ids.has(edge)) walk(edge); visiting.delete(id); visited.add(id); }; if (start) walk(start);
  for (const id of ids) if (!visited.has(id)) errors.push(`Unreachable node: ${id}`);
  if (definition.settings?.timeoutSeconds !== undefined && (!Number.isFinite(definition.settings.timeoutSeconds) || definition.settings.timeoutSeconds < 1 || definition.settings.timeoutSeconds > 31_536_000)) errors.push("Workflow timeout must be between 1 second and 365 days");
  if (definition.settings?.maxRetries !== undefined && (!Number.isInteger(definition.settings.maxRetries) || definition.settings.maxRetries < 0 || definition.settings.maxRetries > 20)) errors.push("Workflow retries must be between 0 and 20");
  if (["SCHEDULED","BIRTHDAY","ANNIVERSARY"].includes(definition.trigger?.type)) { const config = definition.trigger.config ?? {}; const hour = Number(config.hour ?? 9); const minute = Number(config.minute ?? 0); if (!Number.isInteger(hour) || hour < 0 || hour > 23 || !Number.isInteger(minute) || minute < 0 || minute > 59) errors.push("Scheduled trigger time is invalid"); if (config.weekdays !== undefined && (!Array.isArray(config.weekdays) || config.weekdays.some((day) => !["sun","mon","tue","wed","thu","fri","sat"].includes(String(day).toLowerCase())))) errors.push("Scheduled trigger weekdays are invalid"); if (config.timezone !== undefined) try { new Intl.DateTimeFormat("en-US", { timeZone: String(config.timezone) }).format(); } catch { errors.push("Scheduled trigger timezone is invalid"); } }
  return { valid: errors.length === 0, errors: [...new Set(errors)] };
}
