import type { AppointmentStatus, Prisma } from "@prisma/client";
import { prisma } from "../../lib/prisma.js";
import { ApiError } from "../../lib/errors.js";
import { recordActivity } from "../../lib/activity.js";
import type { CreateAppointmentInput, UpdateAppointmentInput } from "./appointments.schemas.js";

const include = { customer: { select: { id: true, name: true, phone: true, email: true } }, assignedMember: { include: { user: { select: { id: true, fullName: true, email: true } } } }, serviceOffering: true } as const;
const blockingStatuses: AppointmentStatus[] = ["SCHEDULED", "CONFIRMED"];
async function validateLinks(tx: Prisma.TransactionClient, businessId: string, customerId?: string | null, memberId?: string | null) { if (customerId && !await tx.customer.findFirst({ where: { id: customerId, businessId }, select: { id: true } })) throw ApiError.badRequest("customerId does not belong to this business"); if (memberId && !await tx.businessMember.findFirst({ where: { id: memberId, businessId, status: "ACTIVE" }, select: { id: true } })) throw ApiError.badRequest("assignedMemberId is not an active member of this business"); }
async function lockSchedule(tx: Prisma.TransactionClient, businessId: string, memberId?: string | null) { await tx.$executeRaw`SELECT pg_advisory_xact_lock(hashtext(${`appointment:${businessId}:${memberId ?? "unassigned"}`}))`; }
async function getOffering(tx: Prisma.TransactionClient, businessId: string, id?: string | null) { if (!id) return null; const offering = await tx.serviceOffering.findFirst({ where: { id, businessId, active: true }, include: { assignments: true } }); if (!offering) throw ApiError.badRequest("serviceOfferingId is not an active service for this business"); return offering; }
function assertMemberCanProvide(offering: Awaited<ReturnType<typeof getOffering>>, memberId?: string | null) { if (!offering || !memberId || !offering.assignments.length) return; if (!offering.assignments.some(assignment => assignment.businessMemberId === memberId)) throw ApiError.badRequest("The selected team member cannot provide this service"); }
async function assertAvailable(tx: Prisma.TransactionClient, businessId: string, startsAt: Date, endsAt: Date, memberId?: string | null, excludeId?: string, preparationMinutes = 0, cleanupMinutes = 0) { const occupiedFrom = new Date(startsAt.getTime() - preparationMinutes * 60_000); const occupiedTo = new Date(endsAt.getTime() + cleanupMinutes * 60_000); const appointments = await tx.appointment.findMany({ where: { businessId, assignedMemberId: memberId ?? null, status: { in: blockingStatuses }, startsAt: { lt: occupiedTo }, endsAt: { gt: occupiedFrom }, ...(excludeId ? { id: { not: excludeId } } : {}) }, select: { startsAt: true, endsAt: true, serviceOffering: { select: { preparationMinutes: true, cleanupMinutes: true } } } }); const conflict = appointments.some(appointment => new Date(appointment.startsAt.getTime() - (appointment.serviceOffering?.preparationMinutes ?? 0) * 60_000) < occupiedTo && new Date(appointment.endsAt.getTime() + (appointment.serviceOffering?.cleanupMinutes ?? 0) * 60_000) > occupiedFrom); if (conflict) throw ApiError.conflict("This team member already has an appointment during that time"); const block = await tx.bookingBlock.findFirst({ where: { businessId, OR: [{ assignedMemberId: null }, ...(memberId ? [{ assignedMemberId: memberId }] : [])], startsAt: { lt: occupiedTo }, endsAt: { gt: occupiedFrom } }, select: { id: true } }); if (block) throw ApiError.conflict("This time is blocked and cannot be booked"); }
export function listAppointments(businessId: string, input: { from: string; to: string; status?: AppointmentStatus; customerId?: string }) { return prisma.appointment.findMany({ where: { businessId, startsAt: { lt: new Date(input.to) }, endsAt: { gt: new Date(input.from) }, status: input.status, customerId: input.customerId }, include, orderBy: { startsAt: "asc" } }); }
export async function getAppointment(businessId: string, id: string) { const appointment = await prisma.appointment.findFirst({ where: { id, businessId }, include }); if (!appointment) throw ApiError.notFound("Appointment not found"); return appointment; }
export function createAppointment(businessId: string, actorId: string, input: CreateAppointmentInput) { return prisma.$transaction(async tx => { await lockSchedule(tx, businessId, input.assignedMemberId); await validateLinks(tx, businessId, input.customerId, input.assignedMemberId); const offering = await getOffering(tx, businessId, input.serviceOfferingId); assertMemberCanProvide(offering, input.assignedMemberId); await assertAvailable(tx, businessId, new Date(input.startsAt), new Date(input.endsAt), input.assignedMemberId, undefined, offering?.preparationMinutes, offering?.cleanupMinutes); const appointment = await tx.appointment.create({ data: { businessId, createdByUserId: actorId, ...input, serviceName: offering?.name ?? input.serviceName, price: input.price ?? offering?.price }, include }); await recordActivity({ businessId, actorId, eventType: "APPOINTMENT_CREATED", entityType: "appointment", entityId: appointment.id }, tx); return appointment; }, { isolationLevel: "Serializable" }); }
export async function updateAppointment(businessId: string, actorId: string, id: string, input: UpdateAppointmentInput) { return prisma.$transaction(async tx => { const current = await tx.appointment.findFirst({ where: { id, businessId } }); if (!current) throw ApiError.notFound("Appointment not found"); if (["COMPLETED", "CANCELED", "NO_SHOW"].includes(current.status)) throw ApiError.conflict("A closed appointment cannot be edited"); const customerId = input.customerId === undefined ? current.customerId : input.customerId; const memberId = input.assignedMemberId === undefined ? current.assignedMemberId : input.assignedMemberId; const offeringId = input.serviceOfferingId === undefined ? current.serviceOfferingId : input.serviceOfferingId; const offering = await getOffering(tx, businessId, offeringId); assertMemberCanProvide(offering, memberId); const startsAt = new Date(input.startsAt ?? current.startsAt); const endsAt = new Date(input.endsAt ?? current.endsAt); if (endsAt <= startsAt) throw ApiError.badRequest("endsAt must be after startsAt"); await lockSchedule(tx, businessId, memberId); await validateLinks(tx, businessId, customerId, memberId); await assertAvailable(tx, businessId, startsAt, endsAt, memberId, id, offering?.preparationMinutes, offering?.cleanupMinutes); const appointment = await tx.appointment.update({ where: { id }, data: { ...input, ...(input.serviceOfferingId && offering ? { serviceName: offering.name, price: input.price ?? offering.price } : {}) }, include }); await recordActivity({ businessId, actorId, eventType: "APPOINTMENT_UPDATED", entityType: "appointment", entityId: id }, tx); return appointment; }, { isolationLevel: "Serializable" }); }
const transitions: Record<AppointmentStatus, AppointmentStatus[]> = { SCHEDULED: ["CONFIRMED", "CANCELED", "NO_SHOW"], CONFIRMED: ["COMPLETED", "CANCELED", "NO_SHOW"], COMPLETED: [], CANCELED: [], NO_SHOW: [] };
export async function transitionAppointment(businessId: string, actorId: string, id: string, status: AppointmentStatus) { return prisma.$transaction(async tx => { const current = await tx.appointment.findFirst({ where: { id, businessId } }); if (!current) throw ApiError.notFound("Appointment not found"); if (!transitions[current.status].includes(status)) throw ApiError.conflict(`Cannot move appointment from ${current.status} to ${status}`); const appointment = await tx.appointment.update({ where: { id }, data: { status }, include }); const eventType = status === "COMPLETED" ? "APPOINTMENT_COMPLETED" : status === "CANCELED" ? "APPOINTMENT_CANCELED" : status === "NO_SHOW" ? "APPOINTMENT_NO_SHOW" : "APPOINTMENT_UPDATED"; await recordActivity({ businessId, actorId, eventType, entityType: "appointment", entityId: id }, tx); return appointment; }, { isolationLevel: "Serializable" }); }
