import { afterAll, afterEach, beforeAll, describe, expect, it } from "vitest";
import type { FastifyInstance } from "fastify";
import { prisma } from "../src/lib/prisma.js";
import { authHeader, createTestApp, registerAccount, resetDatabase, setPlan } from "./helpers.js";
import { evaluateCondition } from "../src/lib/automation/conditionEngine.js";
import { delayUntil } from "../src/lib/automation/delayEngine.js";
import { validateWorkflow } from "../src/lib/automation/workflowValidation.js";
import { publishOutboxBatch } from "../src/worker/outboxPublisher.js";
import { clearSubscriberHandlers, dispatchDeliveryBatch, recoverExpiredDeliveries, registerSubscriber } from "../src/lib/automation/domainEventBus.js";
import { registerDefaultActions } from "../src/lib/automation/defaultActions.js";
import { processWorkflowExecutions } from "../src/worker/workflowWorker.js";
import { registerWorkflowTriggerSubscribers } from "../src/lib/automation/triggerEngine.js";
import { nextWorkflowTriggerAt } from "../src/lib/automation/workflowScheduling.js";

describe("hybrid automation core", () => {
  let app: FastifyInstance;
  beforeAll(async()=>{app=await createTestApp();}); afterEach(async()=>{clearSubscriberHandlers();await resetDatabase();}); afterAll(async()=>{await app.close();await prisma.$disconnect();});
  it("validates nested conditions, business delays, timezone schedules, and rejects cycles",()=>{ expect(evaluateCondition({operator:"AND",conditions:[{field:"lead.status",value:"new"},{operator:"OR",conditions:[{field:"customer.tags",operator:"contains",value:"VIP"},{field:"customer.tags",operator:"contains",value:"Loyal"}]}]},{lead:{status:"new"},customer:{tags:["VIP"]}})).toBe(true); expect(delayUntil(new Date("2026-08-28T09:00:00Z"),{amount:1,unit:"business_days",timezone:"UTC"}).toISOString()).toBe("2026-08-31T09:00:00.000Z"); expect(nextWorkflowTriggerAt({trigger:{type:"SCHEDULED",config:{hour:9,minute:0}},nodes:[{id:"a",type:"action",config:{action:"CREATE_TASK"}}]},"Asia/Dubai",new Date("2026-08-30T04:59:00Z"))?.toISOString()).toBe("2026-08-30T05:00:00.000Z"); expect(validateWorkflow({trigger:{type:"MANUAL"},nodes:[{id:"a",type:"action",config:{action:"CREATE_TASK"},next:["b"]},{id:"b",type:"action",config:{action:"CREATE_TASK"},next:["a"]}]}).valid).toBe(false); });
  it("creates, versions, publishes, and tenant-isolates workflows",async()=>{const first=await registerAccount(app);const second=await registerAccount(app);await setPlan(first.businessId,"PRO");const definition={trigger:{type:"MANUAL"},nodes:[{id:"task",type:"action",config:{action:"CREATE_TASK",title:"Call customer"},next:[]}]};const created=await app.inject({method:"POST",url:"/automation/workflows",headers:authHeader(first.token),payload:{name:"Manual care",definition}});expect(created.statusCode).toBe(201);const id=created.json().id;expect((await app.inject({method:"GET",url:`/automation/workflows/${id}`,headers:authHeader(second.token)})).statusCode).toBe(404);expect((await app.inject({method:"POST",url:`/automation/workflows/${id}/publish`,headers:authHeader(first.token),payload:{version:1}})).statusCode).toBe(200);expect((await app.inject({method:"POST",url:`/automation/workflows/${id}/trigger`,headers:authHeader(first.token),payload:{input:{customerId:"x"}}})).statusCode).toBe(202);expect(await prisma.workflowExecution.count({where:{workflowId:id}})).toBe(1);});
  it("fans out outbox events durably and acknowledges idempotent delivery",async()=>{const {businessId}=await registerAccount(app);let calls=0;await registerSubscriber({name:"test-customer-created",eventType:"CustomerCreated",handler:async()=>{calls+=1;}});await prisma.outboxEvent.create({data:{dedupeKey:"test:customer",aggregateType:"customer",aggregateId:"customer-1",eventType:"CustomerCreated",tenantId:businessId,businessId,payload:{id:"customer-1"}}});expect((await publishOutboxBatch()).published).toBe(1);expect((await dispatchDeliveryBatch()).delivered).toBe(1);expect((await dispatchDeliveryBatch()).delivered).toBe(0);expect(calls).toBe(1);});
  it("executes a claimed workflow once and persists restart-safe progress",async()=>{const account=await registerAccount(app);await setPlan(account.businessId,"PRO");registerDefaultActions();const definition={trigger:{type:"MANUAL"},nodes:[{id:"task",type:"action",config:{action:"CREATE_TASK",title:"Call customer"},next:[]}]};const created=await app.inject({method:"POST",url:"/automation/workflows",headers:authHeader(account.token),payload:{name:"Runtime test",definition}});const id=created.json().id;await app.inject({method:"POST",url:`/automation/workflows/${id}/publish`,headers:authHeader(account.token),payload:{version:1}});await app.inject({method:"POST",url:`/automation/workflows/${id}/trigger`,headers:authHeader(account.token),payload:{input:{}}});expect(await processWorkflowExecutions()).toBe(1);expect(await processWorkflowExecutions()).toBe(0);const execution=await prisma.workflowExecution.findFirstOrThrow({where:{workflowId:id}});expect(execution.status).toBe("COMPLETED");expect(await prisma.automationTask.count({where:{executionId:execution.id}})).toBe(1);expect(await prisma.workflowExecutionEvent.count({where:{executionId:execution.id,type:"COMPLETED"}})).toBe(1);});
  it("recovers expired durable delivery leases",async()=>{const {businessId}=await registerAccount(app);const subscription=await prisma.eventSubscription.create({data:{name:"lease-test",eventType:"CustomerCreated"}});const event=await prisma.outboxEvent.create({data:{dedupeKey:"lease:event",aggregateType:"customer",aggregateId:"c",eventType:"CustomerCreated",tenantId:businessId,businessId,payload:{id:"c"}}});await prisma.eventDelivery.create({data:{eventId:event.id,subscriptionId:subscription.id,status:"PROCESSING",leaseOwner:"dead-worker",leaseExpiresAt:new Date(Date.now()-1_000)}});expect((await recoverExpiredDeliveries()).count).toBe(1);expect((await prisma.eventDelivery.findFirstOrThrow()).status).toBe("RETRY");});
  it("delivers a business event through its trigger subscription into workflow execution",async()=>{const account=await registerAccount(app);await setPlan(account.businessId,"PRO");registerDefaultActions();await registerWorkflowTriggerSubscribers();const definition={trigger:{type:"CUSTOMER_CREATED"},nodes:[{id:"task",type:"action",config:{action:"CREATE_TASK",title:"Welcome customer"},next:[]}]};const created=await app.inject({method:"POST",url:"/automation/workflows",headers:authHeader(account.token),payload:{name:"Customer welcome",definition}});const workflowId=created.json().id;await app.inject({method:"POST",url:`/automation/workflows/${workflowId}/publish`,headers:authHeader(account.token),payload:{version:1}});await prisma.outboxEvent.create({data:{dedupeKey:"customer:trigger-test",aggregateType:"customer",aggregateId:"customer-1",eventType:"CustomerCreated",tenantId:account.businessId,businessId:account.businessId,payload:{id:"customer-1"}}});await publishOutboxBatch();expect((await dispatchDeliveryBatch()).delivered).toBe(1);expect(await prisma.workflowExecution.count({where:{workflowId}})).toBe(1);expect(await processWorkflowExecutions()).toBe(1);expect((await prisma.workflowExecution.findFirstOrThrow({where:{workflowId}})).status).toBe("COMPLETED");});

  it("replays a crashed provider action with the same key without duplicating its effect", async () => {
    const account = await registerAccount(app); await setPlan(account.businessId, "PRO");
    const effects = new Map<string, unknown>(); let calls = 0;
    registerDefaultActions({ ai: { execute: async ({ idempotencyKey }) => { calls += 1; if (!effects.has(idempotencyKey)) effects.set(idempotencyKey, { answer: "safe" }); if (calls === 1) throw new Error("connection_lost_after_provider_commit"); return effects.get(idempotencyKey); } } });
    const definition = { trigger: { type: "MANUAL" }, settings: { maxRetries: 3 }, nodes: [{ id: "ai", type: "action", config: { action: "INVOKE_AI", prompt: "test" }, next: [] }] };
    const created = await app.inject({ method: "POST", url: "/automation/workflows", headers: authHeader(account.token), payload: { name: "Replay safe", definition } });
    const workflowId = created.json().id; await app.inject({ method: "POST", url: `/automation/workflows/${workflowId}/publish`, headers: authHeader(account.token), payload: { version: 1 } }); await app.inject({ method: "POST", url: `/automation/workflows/${workflowId}/trigger`, headers: authHeader(account.token), payload: { input: {} } });
    await processWorkflowExecutions(); const execution = await prisma.workflowExecution.findFirstOrThrow({ where: { workflowId } }); expect(execution.status).toBe("FAILED");
    await prisma.workflowExecution.update({ where: { id: execution.id }, data: { nextAttemptAt: new Date(0) } }); await processWorkflowExecutions();
    expect((await prisma.workflowExecution.findUniqueOrThrow({ where: { id: execution.id } })).status).toBe("COMPLETED"); expect(effects.size).toBe(1); expect(calls).toBe(2);
    expect(await prisma.workflowActionAttempt.findUniqueOrThrow({ where: { executionId_nodeId: { executionId: execution.id, nodeId: "ai" } } })).toMatchObject({ status: "SUCCEEDED", attempts: 2 });
  });
});
