import { createHash } from "node:crypto";
import { afterAll, afterEach, beforeAll, describe, expect, it } from "vitest";
import type { FastifyInstance } from "fastify";
import { configureAttachmentPlatform, createAttachmentDownload, downloadAttachment, initiateAttachment, processAttachmentScans, uploadAttachment } from "../src/lib/messaging/attachmentPlatform.js";
import { bulkConversationUpdate, createMessagingTemplate, initializeConversationSLAs, mergeConversations, processConversationSLAs, publishTemplate, renderTemplate, splitConversation, storeProviderCredential } from "../src/lib/messaging/messagingOperations.js";
import { prisma } from "../src/lib/prisma.js";
import { createTestApp, registerAccount, resetDatabase } from "./helpers.js";

describe("messaging production completion", () => {
  let app: FastifyInstance;
  beforeAll(async()=>{app=await createTestApp();}); afterEach(async()=>{await resetDatabase();}); afterAll(async()=>{await app.close();await prisma.$disconnect();});
  async function business(){return registerAccount(app);}
  it("queues malware scanning before releasing a validated attachment",async()=>{const objects=new Map<string,Buffer>();configureAttachmentPlatform({storage:{put:async(key,body)=>{objects.set(key,Buffer.from(body));},get:async key=>objects.get(key)??null,remove:async key=>{objects.delete(key);}},scanner:{scan:async(_body,mime)=>({clean:true,detectedMime:mime})}});const account=await business();const body=Buffer.from("safe attachment");const declared={fileName:"proof.txt",mimeType:"text/plain",sizeBytes:body.length,checksumSha256:createHash("sha256").update(body).digest("hex")};const first=await initiateAttachment(account.businessId,declared);const second=await initiateAttachment(account.businessId,declared);expect(first.attachment.storageKey).not.toBe(second.attachment.storageKey);await uploadAttachment(first.uploadToken,body,"text/plain");await expect(createAttachmentDownload(account.businessId,first.attachment.id)).rejects.toMatchObject({statusCode:404});await processAttachmentScans();await expect(uploadAttachment(first.uploadToken,Buffer.from("different"),"text/plain")).rejects.toMatchObject({statusCode:400});const download=await createAttachmentDownload(account.businessId,first.attachment.id);expect((await downloadAttachment(download.token)).body.toString()).toBe("safe attachment");});
  it("versions, publishes, rolls template variables, and previews safely",async()=>{const account=await business();const template=await createMessagingTemplate(account.businessId,{key:"BOOKING_READY",name:"Booking",purpose:"SERVICE",channel:"sms",locale:"en",body:"Hello {{customer.name}}",variables:["customer.name"]});const version=template.versions[0]!;expect(renderTemplate(version.body,{customer:{name:"Ada"}})).toBe("Hello Ada");await expect(createMessagingTemplate(account.businessId,{key:"BAD_TEMPLATE",name:"Bad",purpose:"SERVICE",channel:"sms",locale:"en",body:"Hi {{missing}}",variables:[]})).rejects.toMatchObject({statusCode:400});expect((await publishTemplate(account.businessId,version.id)).status).toBe("PUBLISHED");});
  it("rotates encrypted credentials without returning secrets",async()=>{const account=await business();const channel=await prisma.messagingChannelAccount.create({data:{businessId:account.businessId,provider:"twilio",channel:"sms",externalAccountId:"acct"}});const verifier={verify:async()=>({valid:true,latencyMs:2})};const first=await storeProviderCredential(account.businessId,account.userId,channel.id,{token:"secret-one"},verifier);const second=await storeProviderCredential(account.businessId,account.userId,channel.id,{token:"secret-two"},verifier);expect((await prisma.providerCredential.findUniqueOrThrow({where:{id:first.id}})).status).toBe("ROTATED");expect(second.encryptedPayload).not.toContain("secret-two");expect(await prisma.providerCredentialAudit.count({where:{businessId:account.businessId}})).toBe(2);});
  it("breaches each SLA once under concurrent workers",async()=>{const account=await business();const conversation=await prisma.conversation.create({data:{businessId:account.businessId,status:"OPEN"}});await initializeConversationSLAs(account.businessId,conversation.id,{firstResponse:1,resolution:1,assignment:1,escalation:1});await prisma.conversationSLA.updateMany({data:{dueAt:new Date(0)}});await Promise.all([processConversationSLAs(),processConversationSLAs()]);expect(await prisma.conversationLifecycleEvent.count({where:{conversationId:conversation.id,type:"SLA_BREACHED"}})).toBe(4);expect(await prisma.automationTask.count({where:{businessId:account.businessId}})).toBe(2);});
  it("atomically bulk-updates, merges, and splits tenant conversations",async()=>{const account=await business();const first=await prisma.conversation.create({data:{businessId:account.businessId,status:"OPEN"}});const second=await prisma.conversation.create({data:{businessId:account.businessId,status:"OPEN"}});const message=await prisma.message.create({data:{businessId:account.businessId,conversationId:first.id,messageType:"custom",body:"Move me"}});expect(await bulkConversationUpdate(account.businessId,[first.id,second.id],{status:"PENDING"},account.userId)).toBe(2);const split=await splitConversation(account.businessId,first.id,[message.id],account.userId);expect((await prisma.message.findUniqueOrThrow({where:{id:message.id}})).conversationId).toBe(split.id);await mergeConversations(account.businessId,second.id,[split.id],account.userId);expect((await prisma.message.findUniqueOrThrow({where:{id:message.id}})).conversationId).toBe(second.id);await expect(mergeConversations(account.businessId,second.id,[second.id],account.userId)).rejects.toMatchObject({statusCode:409});});
});
