import { Pressable, StyleSheet, Text, View } from 'react-native';
import { AudienceCenterDto, SmartAudienceKey } from '../apiTypes';
import { colors, radius, spacing, typography } from '../theme';
import { formatMoney } from '../utils/format';

export function AudienceSummary({ data, selected, onSelect }: { data: AudienceCenterDto; selected: SmartAudienceKey | null; onSelect: (key: SmartAudienceKey | null) => void }) {
  return <View style={styles.wrap}><View style={styles.heading}><Text style={styles.title}>Smart audiences</Text>{selected ? <Pressable accessibilityRole="button" onPress={() => onSelect(null)}><Text style={styles.clear}>Clear</Text></Pressable> : null}</View><View style={styles.cards}>{data.audiences.filter(item => item.totalCustomers > 0).map(item => <Pressable key={item.key} accessibilityRole="button" accessibilityState={{ selected: selected === item.key }} onPress={() => onSelect(selected === item.key ? null : item.key)} style={[styles.card, selected === item.key && styles.selected]}><Text style={styles.label}>{item.label}</Text><Text style={styles.count}>{item.totalCustomers}</Text><Text style={styles.detail}>{formatMoney(item.revenue)} value{item.outstandingPayments > 0 ? ` · ${formatMoney(item.outstandingPayments)} outstanding` : ''}</Text></Pressable>)}</View></View>;
}
const styles = StyleSheet.create({ wrap: { gap: spacing.sm }, heading: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, title: { ...typography.bodyStrong, color: colors.text }, clear: { ...typography.caption, color: colors.primary, fontWeight: '700' }, cards: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm }, card: { width: '48%', minHeight: 96, borderWidth: 1, borderColor: colors.border, borderRadius: radius.md, backgroundColor: colors.surface, padding: spacing.sm, gap: spacing.xxs }, selected: { borderColor: colors.primary }, label: { ...typography.caption, color: colors.text }, count: { ...typography.heading, color: colors.text }, detail: { ...typography.micro, color: colors.textSecondary } });
