import { Ionicons } from '@expo/vector-icons';
import { GoogleSigninButton } from '@react-native-google-signin/google-signin';
import { useNavigation } from '@react-navigation/native';
import type { NativeStackNavigationProp } from '@react-navigation/native-stack';
import * as AppleAuthentication from 'expo-apple-authentication';
import { useRef, useState, type ReactNode } from 'react';
import { Platform, Pressable, StyleSheet, Text, TextInput, useWindowDimensions, View } from 'react-native';
import { ApiError } from '../services/api';
import { APPLE_AUTH_ENABLED, GOOGLE_AUTH_ENABLED, PASSWORD_RESET_EMAIL_ENABLED } from '../config';
import { registrationInput } from '../domain/authenticationFlow';
import { useAuth } from '../state/AuthContext';
import { colors, radius, spacing, typography } from '../theme';
import { PrimaryButton } from './ui';
import type { RootStackParamList } from '../types';

interface AuthFormProps { defaultIndustry?: string; defaultMode?: 'login'|'register'; invitationToken?: string; invitedEmail?: string; onSuccess?: () => void; onForgotPassword?: () => void; onOpenPrivacy?: () => void; onOpenTerms?: () => void; }
export function AuthForm({ defaultIndustry, defaultMode = 'register', invitationToken, invitedEmail, onSuccess, onForgotPassword, onOpenPrivacy, onOpenTerms }: AuthFormProps) {
  const navigation = useNavigation<NativeStackNavigationProp<RootStackParamList>>();
  const { height } = useWindowDimensions();
  const compact = height < 860;
  const { login, register, googleSignIn, appleSignIn } = useAuth();
  const [mode, setMode] = useState<'login'|'register'>(defaultMode); const [email, setEmail] = useState(invitedEmail ?? ''); const [password, setPassword] = useState(''); const [fullName, setFullName] = useState(''); const [businessName, setBusinessName] = useState(''); const [passwordVisible, setPasswordVisible] = useState(false); const [loading, setLoading] = useState<'password'|'google'|'apple'|null>(null); const [error, setError] = useState<string | null>(null); const submissionActive = useRef(false);
  const errorText = (caught: unknown) => invitationToken && caught instanceof ApiError && caught.kind === 'not-found' ? 'This invitation was sent to a different email address or is no longer available.' : caught instanceof ApiError || caught instanceof Error ? caught.message : 'Unable to authenticate. Please try again.';
  const begin = (kind: 'password'|'google'|'apple') => { if (submissionActive.current) return false; submissionActive.current = true; setLoading(kind); setError(null); return true; }; const end = () => { submissionActive.current = false; setLoading(null); };
  const submit = async () => { if (!begin('password')) return; try { if (mode === 'login') await login(email.trim(), password); else await register(registrationInput({ email, password, fullName, businessName, defaultIndustry, invitationToken })); onSuccess?.(); } catch (caught) { setError(errorText(caught)); } finally { end(); } };
  const google = async () => { if (!begin('google')) return; try { if (await googleSignIn(invitationToken)) onSuccess?.(); } catch (caught) { setError(errorText(caught)); } finally { end(); } };
  const apple = async () => { if (!begin('apple')) return; try { if (await appleSignIn(invitationToken)) onSuccess?.(); } catch (caught) { setError(errorText(caught)); } finally { end(); } };
  const registrationReady = fullName.trim();
  const providerVisible = GOOGLE_AUTH_ENABLED || (APPLE_AUTH_ENABLED && Platform.OS === 'ios');
  return <View style={[styles.form, compact && styles.formCompact]}>
    {!invitationToken ? <View accessibilityRole="tablist" style={[styles.tabs, compact && styles.tabsCompact]}><Tab label="Login" selected={mode === 'login'} onPress={() => { setMode('login'); setError(null); }} /><Tab label="Sign up" selected={mode === 'register'} onPress={() => { setMode('register'); setError(null); }} /></View> : null}
    <Text style={[styles.heading, compact && styles.headingCompact]}>{mode === 'register' ? invitationToken ? 'Join the team' : 'Create an account' : 'Welcome back'}</Text>
    <View style={[styles.fields, compact && styles.fieldsCompact]}>{mode === 'register' ? <><Field compact={compact} label="Your name" value={fullName} onChangeText={setFullName} />{!invitationToken ? <Field compact={compact} label="Business name" value={businessName} onChangeText={setBusinessName} /> : null}</> : null}<Field compact={compact} label="Email address" value={email} onChangeText={setEmail} keyboardType="email-address" autoCapitalize="none" /><Field compact={compact} label="Password" value={password} onChangeText={setPassword} secureTextEntry={!passwordVisible} accessory={<Pressable accessibilityRole="button" accessibilityLabel={passwordVisible ? 'Hide password' : 'Show password'} hitSlop={10} onPress={() => setPasswordVisible(value => !value)}><Ionicons name={passwordVisible ? 'eye-off-outline' : 'eye-outline'} size={22} color={colors.textSecondary} /></Pressable>} /></View>
    {error ? <Text accessibilityRole="alert" style={styles.error}>{error}</Text> : null}<PrimaryButton disabled={Boolean(loading) || !email.trim() || !password || (mode === 'register' && !registrationReady)} fullWidth icon="mail-outline" label={loading === 'password' ? 'Please wait…' : mode === 'register' ? invitationToken ? 'Create account and join' : 'Continue with email' : 'Log in with email'} onPress={() => void submit()} />
    {mode === 'login' && onForgotPassword && PASSWORD_RESET_EMAIL_ENABLED ? <Pressable disabled={Boolean(loading)} onPress={onForgotPassword} style={styles.forgot}><Text style={styles.forgotText}>Forgot password?</Text></Pressable> : null}
    {providerVisible ? <><View style={styles.divider}><View style={styles.dividerLine} /><Text style={styles.dividerText}>OR {mode === 'register' ? 'SIGN UP' : 'LOG IN'} WITH</Text><View style={styles.dividerLine} /></View><View style={styles.providers}>{GOOGLE_AUTH_ENABLED ? <View accessibilityLabel="Continue with Google" accessibilityRole="button" style={Boolean(loading) && styles.disabled} pointerEvents={loading ? 'none' : 'auto'}><GoogleSigninButton color={GoogleSigninButton.Color.Light} disabled={Boolean(loading)} onPress={() => void google()} size={GoogleSigninButton.Size.Wide} style={[styles.googleButton, compact && styles.googleButtonCompact]} /></View> : null}{APPLE_AUTH_ENABLED && Platform.OS === 'ios' ? <View style={[styles.appleWrap, Boolean(loading) && styles.disabled]} pointerEvents={loading ? 'none' : 'auto'}><AppleAuthentication.AppleAuthenticationButton buttonType={AppleAuthentication.AppleAuthenticationButtonType.CONTINUE} buttonStyle={AppleAuthentication.AppleAuthenticationButtonStyle.WHITE_OUTLINE} cornerRadius={radius.md} style={styles.appleButton} onPress={() => void apple()} /></View> : null}</View></> : null}
    {mode === 'register' ? <Text style={styles.legal}>By signing up, I agree to the <Text accessibilityRole="link" onPress={onOpenTerms ?? (() => navigation.navigate('LegalDocument', { page: 'terms' }))} style={styles.legalLink}>Terms of Use</Text> and <Text accessibilityRole="link" onPress={onOpenPrivacy ?? (() => navigation.navigate('LegalDocument', { page: 'privacy' }))} style={styles.legalLink}>Privacy Policy</Text>.</Text> : null}
  </View>;
}
function Tab({ label, selected, onPress }: { label: string; selected: boolean; onPress: () => void }) { return <Pressable accessibilityRole="tab" accessibilityState={{ selected }} onPress={onPress} style={[styles.tab, selected && styles.tabActive]}><Text style={[styles.tabText, selected && styles.tabTextActive]}>{label}</Text></Pressable>; }
function Field({ label, accessory, compact, ...props }: { label: string; value: string; onChangeText: (value: string) => void; compact: boolean; keyboardType?: 'email-address'; autoCapitalize?: 'none'; secureTextEntry?: boolean; accessory?: ReactNode }) { return <View style={styles.field}><Text style={styles.label}>{label}</Text><View style={[styles.inputWrap, compact && styles.inputWrapCompact]}><TextInput accessibilityLabel={label} {...props} placeholder={label} placeholderTextColor={colors.textSecondary} style={[styles.input, compact && styles.inputCompact]} />{accessory}</View></View>; }
const styles = StyleSheet.create({ form: { flex: 1, gap: spacing.lg }, formCompact: { gap: spacing.sm }, tabs: { height: 58, padding: 5, borderRadius: radius.lg, backgroundColor: colors.background, flexDirection: 'row' }, tabsCompact: { height: 50 }, tab: { flex: 1, borderRadius: radius.md, alignItems: 'center', justifyContent: 'center' }, tabActive: { backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border }, tabText: { ...typography.body, color: colors.textSecondary }, tabTextActive: { ...typography.bodyStrong, color: colors.text }, heading: { ...typography.title, color: colors.text, textAlign: 'center', marginVertical: spacing.xs }, headingCompact: { ...typography.heading, marginVertical: 0 }, fields: { gap: spacing.md }, fieldsCompact: { gap: spacing.xs }, field: { gap: spacing.xxs }, label: { ...typography.caption, color: colors.textSecondary, marginLeft: spacing.sm }, inputWrap: { minHeight: 56, borderRadius: radius.lg, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, paddingHorizontal: spacing.md, flexDirection: 'row', alignItems: 'center' }, inputWrapCompact: { minHeight: 48 }, input: { flex: 1, minHeight: 54, ...typography.body, color: colors.text }, inputCompact: { minHeight: 46 }, forgot: { minHeight: 42, alignSelf: 'center', justifyContent: 'center' }, forgotText: { ...typography.bodyStrong, color: colors.text }, error: { ...typography.caption, color: colors.negative }, divider: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm }, dividerLine: { height: 1, flex: 1, backgroundColor: colors.border }, dividerText: { ...typography.micro, color: colors.textSecondary }, providers: { flexDirection: 'row', justifyContent: 'center', gap: spacing.sm }, googleButton: { width: 230, height: 52 }, googleButtonCompact: { height: 48 }, appleWrap: { flex: 1, maxWidth: 230, minWidth: 132 }, appleButton: { width: '100%', height: 52 }, disabled: { opacity: 0.45 }, legal: { ...typography.caption, color: colors.textSecondary, textAlign: 'center', marginTop: 'auto' }, legalLink: { color: colors.text, textDecorationLine: 'underline' } });
