import { Ionicons } from '@expo/vector-icons';
import * as AppleAuthentication from 'expo-apple-authentication';
import { useRef, useState } from 'react';
import { Platform, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { ApiError } from '../services/api';
import { APPLE_AUTH_ENABLED, GOOGLE_AUTH_ENABLED, PASSWORD_RESET_EMAIL_ENABLED } from '../config';
import { useAuth } from '../state/AuthContext';
import { colors, radius, spacing, typography } from '../theme';
import { PrimaryButton } from './ui';

interface AuthFormProps { defaultIndustry?: string; defaultMode?: 'login'|'register'; invitationToken?: string; invitedEmail?: string; onSuccess?: () => void; onForgotPassword?: () => void; }
export function AuthForm({ defaultIndustry, defaultMode = 'register', invitationToken, invitedEmail, onSuccess, onForgotPassword }: AuthFormProps) {
  const { login, register, googleSignIn, appleSignIn } = useAuth();
  const [mode, setMode] = useState<'login'|'register'>(defaultMode); const [email, setEmail] = useState(invitedEmail ?? ''); const [password, setPassword] = useState(''); const [fullName, setFullName] = useState(''); const [businessName, setBusinessName] = useState(''); const [loading, setLoading] = useState<'password'|'google'|'apple'|null>(null); const [error, setError] = useState<string | null>(null); const submissionActive = useRef(false);
  const errorText = (caught: unknown) => invitationToken && caught instanceof ApiError && caught.kind === 'not-found' ? 'This invitation was sent to a different email address or is no longer available.' : caught instanceof ApiError || caught instanceof Error ? caught.message : 'Unable to authenticate. Please try again.';
  const begin = (kind: 'password'|'google'|'apple') => { if (submissionActive.current) return false; submissionActive.current = true; setLoading(kind); setError(null); return true; }; const end = () => { submissionActive.current = false; setLoading(null); };
  const submit = async () => { if (!begin('password')) return; try { if (mode === 'login') await login(email.trim(), password); else await register({ email: email.trim(), password, fullName: fullName.trim(), ...(invitationToken ? { invitationToken } : { businessName: businessName.trim(), industry: defaultIndustry }) }); onSuccess?.(); } catch (caught) { setError(errorText(caught)); } finally { end(); } };
  const google = async () => { if (!begin('google')) return; try { if (await googleSignIn(invitationToken)) onSuccess?.(); } catch (caught) { setError(errorText(caught)); } finally { end(); } };
  const apple = async () => { if (!begin('apple')) return; try { if (await appleSignIn(invitationToken)) onSuccess?.(); } catch (caught) { setError(errorText(caught)); } finally { end(); } };
  const registrationReady = fullName.trim();
  const providerVisible = GOOGLE_AUTH_ENABLED || (APPLE_AUTH_ENABLED && Platform.OS === 'ios');
  return <View style={styles.form}><Text style={styles.heading}>{mode === 'register' ? invitationToken ? 'Join the team' : 'Create your account' : 'Welcome back'}</Text>{mode === 'register' ? <><Field label="Your name" value={fullName} onChangeText={setFullName} />{!invitationToken ? <Field label="Business name" value={businessName} onChangeText={setBusinessName} /> : null}</> : null}<Field label="Email" value={email} onChangeText={setEmail} keyboardType="email-address" autoCapitalize="none" /><Field label="Password" value={password} onChangeText={setPassword} secureTextEntry />{mode === 'login' && onForgotPassword && PASSWORD_RESET_EMAIL_ENABLED ? <Pressable disabled={Boolean(loading)} onPress={onForgotPassword} style={styles.forgot}><Text style={styles.switchStrong}>Forgot password?</Text></Pressable> : null}{error ? <Text accessibilityRole="alert" style={styles.error}>{error}</Text> : null}<PrimaryButton disabled={Boolean(loading) || !email.trim() || !password || (mode === 'register' && !registrationReady)} fullWidth label={loading === 'password' ? 'Please wait…' : mode === 'register' ? invitationToken ? 'Create account and join' : 'Create account' : 'Sign in'} onPress={() => void submit()} />{providerVisible ? <><View style={styles.divider}><View style={styles.dividerLine} /><Text style={styles.dividerText}>or</Text><View style={styles.dividerLine} /></View>{GOOGLE_AUTH_ENABLED ? <Pressable accessibilityRole="button" accessibilityLabel="Continue with Google" disabled={Boolean(loading)} onPress={() => void google()} style={({ pressed }) => [styles.googleButton, pressed && styles.googlePressed, Boolean(loading) && styles.disabled]}><Ionicons name="logo-google" size={20} color={colors.text} /><Text style={styles.googleText}>{loading === 'google' ? 'Connecting…' : 'Continue with Google'}</Text></Pressable> : null}{APPLE_AUTH_ENABLED && Platform.OS === 'ios' ? <View style={Boolean(loading) && styles.disabled} pointerEvents={loading ? 'none' : 'auto'}><AppleAuthentication.AppleAuthenticationButton buttonType={AppleAuthentication.AppleAuthenticationButtonType.CONTINUE} buttonStyle={AppleAuthentication.AppleAuthenticationButtonStyle.BLACK} cornerRadius={radius.md} style={styles.appleButton} onPress={() => void apple()} /></View> : null}</> : null}<Pressable disabled={Boolean(loading)} onPress={() => { setMode(current => current === 'register' ? 'login' : 'register'); setError(null); }} style={styles.switch}><Text style={styles.switchText}>{mode === 'register' ? 'Already use CHAKUSA? ' : 'New to CHAKUSA? '}<Text style={styles.switchStrong}>{mode === 'register' ? 'Sign in' : invitationToken ? 'Create account and join' : 'Create account'}</Text></Text></Pressable></View>;
}
function Field({ label, ...props }: { label: string; value: string; onChangeText: (value: string) => void; keyboardType?: 'email-address'; autoCapitalize?: 'none'; secureTextEntry?: boolean }) { return <View><Text style={styles.label}>{label}</Text><TextInput accessibilityLabel={label} {...props} style={styles.input} /></View>; }
const styles = StyleSheet.create({ form: { gap: spacing.md }, heading: { ...typography.heading, color: colors.text }, label: { ...typography.caption, color: colors.text, marginBottom: spacing.xs }, input: { minHeight: 50, borderRadius: radius.md, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, paddingHorizontal: spacing.md, ...typography.body, color: colors.text }, forgot: { minHeight: 32, alignSelf: 'flex-end', justifyContent: 'center' }, error: { ...typography.caption, color: colors.negative }, divider: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm }, dividerLine: { height: 1, flex: 1, backgroundColor: colors.border }, dividerText: { ...typography.caption, color: colors.textSecondary }, googleButton: { minHeight: 50, borderRadius: radius.md, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: spacing.sm }, googlePressed: { backgroundColor: colors.background }, googleText: { ...typography.bodyStrong, color: colors.text }, appleButton: { width: '100%', height: 50 }, disabled: { opacity: 0.45 }, switch: { minHeight: 44, justifyContent: 'center', alignItems: 'center' }, switchText: { ...typography.body, color: colors.textSecondary }, switchStrong: { color: colors.primary, fontWeight: '600' } });
