import { Pressable, StyleSheet, Switch, Text, TextInput, View } from 'react-native';
import { BUSINESS_DAYS, BusinessDay, WeeklyHours } from '../domain/businessSetup';
import { colors, radius, spacing, typography } from '../theme';

export function BusinessHoursEditor({ value, onChange }: { value: WeeklyHours; onChange: (value: WeeklyHours) => void }) {
  const update = (day: BusinessDay, patch: Partial<WeeklyHours[BusinessDay]>) => onChange({ ...value, [day]: { ...value[day], ...patch } });
  return <View style={styles.wrap}><Text style={styles.label}>Opening hours</Text><Text style={styles.helper}>Used for scheduling and automation quiet hours. Enter times as 24-hour HH:MM.</Text><View style={styles.card}>{BUSINESS_DAYS.map(([day, label], index) => <View key={day} style={[styles.row, index < BUSINESS_DAYS.length - 1 && styles.border]}><Pressable accessibilityRole="switch" accessibilityState={{ checked: value[day].enabled }} onPress={() => update(day, { enabled: !value[day].enabled })} style={styles.day}><Switch pointerEvents="none" value={value[day].enabled} trackColor={{ false: colors.border, true: colors.success }} /><Text style={styles.dayText}>{label}</Text></Pressable>{value[day].enabled ? <View style={styles.times}><TextInput accessibilityLabel={`${label} opening time`} value={value[day].opensAt} onChangeText={opensAt => update(day, { opensAt })} maxLength={5} keyboardType="numbers-and-punctuation" style={styles.time} /><Text style={styles.to}>to</Text><TextInput accessibilityLabel={`${label} closing time`} value={value[day].closesAt} onChangeText={closesAt => update(day, { closesAt })} maxLength={5} keyboardType="numbers-and-punctuation" style={styles.time} /></View> : <Text style={styles.closed}>Closed</Text>}</View>)}</View></View>;
}
const styles = StyleSheet.create({ wrap: { gap: spacing.xs }, label: { ...typography.caption, color: colors.text }, helper: { ...typography.caption, color: colors.textSecondary }, card: { backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, borderRadius: radius.md, paddingHorizontal: spacing.sm }, row: { minHeight: 62, flexDirection: 'row', alignItems: 'center', gap: spacing.xs }, border: { borderBottomWidth: 1, borderBottomColor: colors.divider }, day: { minWidth: 132, flexDirection: 'row', alignItems: 'center', gap: spacing.xs }, dayText: { ...typography.caption, color: colors.text }, times: { flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'flex-end', gap: spacing.xxs }, time: { width: 58, height: 40, textAlign: 'center', borderWidth: 1, borderColor: colors.border, borderRadius: radius.sm, ...typography.caption, color: colors.text }, to: { ...typography.micro, color: colors.textSecondary }, closed: { ...typography.caption, color: colors.textSecondary, flex: 1, textAlign: 'right' } });
