import { useState } from 'react';
import { Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { AudienceCenterDto } from '../apiTypes';
import { customersApi } from '../services/endpoints';
import { colors, radius, spacing, typography } from '../theme';

export function CustomerTags({ customerId, data, onChanged }: { customerId: string; data: AudienceCenterDto; onChanged: () => void }) {
  const member = data.members.find(item => item.customerId === customerId); const [name, setName] = useState(''); const [saving, setSaving] = useState(false);
  const assigned = member?.manualTagIds ?? [];
  const set = async (tagIds: string[]) => { setSaving(true); try { await customersApi.setTags(customerId, tagIds); onChanged(); } finally { setSaving(false); } };
  const create = async () => { if (!name.trim() || saving) return; setSaving(true); try { const tag = await customersApi.createTag(name.trim()); setName(''); await customersApi.setTags(customerId, [...assigned, tag.id]); onChanged(); } finally { setSaving(false); } };
  return <View style={styles.card}><Text style={styles.title}>Tags</Text><View style={styles.tags}>{data.tags.map(tag => <Pressable key={tag.id} disabled={saving} accessibilityRole="button" accessibilityState={{ selected: assigned.includes(tag.id) }} onPress={() => void set(assigned.includes(tag.id) ? assigned.filter(id => id !== tag.id) : [...assigned, tag.id])} style={[styles.tag, assigned.includes(tag.id) && styles.selected]}><Text style={[styles.text, assigned.includes(tag.id) && styles.selectedText]}>{tag.name}</Text></Pressable>)}</View><View style={styles.create}><TextInput accessibilityLabel="New tag" value={name} onChangeText={setName} placeholder="Create tag" placeholderTextColor={colors.textSecondary} style={styles.input} /><Pressable accessibilityRole="button" disabled={saving || !name.trim()} onPress={() => void create()} style={styles.add}><Text style={styles.addText}>{saving ? 'Saving…' : 'Add'}</Text></Pressable></View></View>;
}
const styles = StyleSheet.create({ card: { backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, borderRadius: radius.md, padding: spacing.md, gap: spacing.sm }, title: { ...typography.bodyStrong, color: colors.text }, tags: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.xs }, tag: { minHeight: 36, paddingHorizontal: spacing.sm, justifyContent: 'center', borderRadius: radius.round, borderWidth: 1, borderColor: colors.border }, selected: { backgroundColor: colors.primary, borderColor: colors.primary }, text: { ...typography.caption, color: colors.text }, selectedText: { color: colors.surface }, create: { flexDirection: 'row', gap: spacing.xs }, input: { flex: 1, minHeight: 42, borderWidth: 1, borderColor: colors.border, borderRadius: radius.md, paddingHorizontal: spacing.sm, color: colors.text }, add: { minWidth: 58, justifyContent: 'center', alignItems: 'center', borderRadius: radius.md, backgroundColor: colors.primary }, addText: { ...typography.caption, fontWeight: '700', color: colors.surface } });
