import { useQuery } from "@tanstack/react-query";
import { BarChart3 } from "lucide-react";
import { Bar, BarChart, CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { apiFetch } from "../api";
import { ErrorState, formatMoney, formatNumber, LoadingState, MetricCard, PageHeader, StatusBadge } from "../components/ui";

interface Analytics { series: { date: string; businesses: number; customers: number; leads: number; recoveredLeads: number; recoveredRevenue: number; reviews: number }[]; breakdowns: { countries: { key: string; count: number }[]; industries: { key: string; count: number }[]; automation: { key: string; count: number }[]; subscriptions: { key: string; count: number }[]; activeBusinesses: number }; totals: { businesses: number; customers: number; leads: number; recoveredLeads: number; recoveredRevenue: number; reviews: number }; window: { days: number; startsAt: string; generatedAt: string } }

export default function AnalyticsPage() {
  const query = useQuery({ queryKey: ["admin-analytics"], queryFn: () => apiFetch<Analytics>("/admin/analytics?days=90") });
  if (query.isLoading) return <LoadingState label="Loading platform analytics" />;
  if (query.error || !query.data) return <ErrorState message={(query.error as Error)?.message ?? "Analytics unavailable"} onRetry={() => void query.refetch()} />;
  const data = query.data;
  return <div className="page"><PageHeader eyebrow="Platform intelligence" title="Analytics" description={`Growth, recovery, retention signals, subscriptions, and operational trends for the last ${data.window.days} days.`} actions={<StatusBadge value="read-only" />} /><section className="metric-grid primary-metrics"><MetricCard label="New businesses" value={formatNumber(data.totals.businesses)} /><MetricCard label="New customers" value={formatNumber(data.totals.customers)} /><MetricCard label="Leads" value={formatNumber(data.totals.leads)} /><MetricCard label="Recovered leads" value={formatNumber(data.totals.recoveredLeads)} /><MetricCard label="Recovered revenue" value={formatMoney(data.totals.recoveredRevenue)} /><MetricCard label="Active businesses" value={formatNumber(data.breakdowns.activeBusinesses)} /></section><section className="dashboard-grid charts-grid"><article className="panel chart-panel"><div className="panel-heading"><div><p className="eyebrow">Growth</p><h2>Businesses and customers</h2></div></div><div className="chart-wrap"><ResponsiveContainer width="100%" height={280}><LineChart data={data.series}><CartesianGrid strokeDasharray="3 3" vertical={false} stroke="var(--border-subtle)" /><XAxis dataKey="date" hide /><YAxis allowDecimals={false} axisLine={false} tickLine={false} /><Tooltip /><Line type="monotone" dataKey="businesses" stroke="#176b55" strokeWidth={2} dot={false} /><Line type="monotone" dataKey="customers" stroke="#90a69d" strokeWidth={2} dot={false} /></LineChart></ResponsiveContainer></div></article><article className="panel chart-panel"><div className="panel-heading"><div><p className="eyebrow">Recovery</p><h2>Revenue recovered</h2></div></div><div className="chart-wrap"><ResponsiveContainer width="100%" height={280}><BarChart data={data.series}><CartesianGrid strokeDasharray="3 3" vertical={false} stroke="var(--border-subtle)" /><XAxis dataKey="date" hide /><YAxis allowDecimals={false} axisLine={false} tickLine={false} /><Tooltip /><Bar dataKey="recoveredRevenue" fill="#176b55" radius={[4, 4, 0, 0]} /></BarChart></ResponsiveContainer></div></article></section><section className="dashboard-grid charts-grid"><article className="panel chart-panel"><div className="panel-heading"><div><p className="eyebrow">Countries</p><h2>Business distribution</h2></div></div>{data.breakdowns.countries.slice(0, 8).map((item) => <div className="panel-stat-row" key={item.key}><span>{item.key}<strong>{formatNumber(item.count)}</strong></span></div>)}</article><article className="panel chart-panel"><div className="panel-heading"><div><p className="eyebrow">Industries</p><h2>Business segments</h2></div></div>{data.breakdowns.industries.slice(0, 8).map((item) => <div className="panel-stat-row" key={item.key}><span>{item.key}<strong>{formatNumber(item.count)}</strong></span></div>)}</article></section></div>;
}
