import { useMutation, useQuery } from "@tanstack/react-query";
import { CirclePause, CirclePlay, RotateCcw, Send, Workflow } from "lucide-react";
import { apiFetch } from "../api";
import { useAuth } from "../auth";
import { DataTable, ErrorState, formatDate, LoadingState, PageHeader, StatusBadge } from "../components/ui";
import { AdminWorkflowOperations } from "../components/AdminWorkflowOperations";

interface WorkflowRow { id:string; name:string; businessId:string; status:string; updatedAt:string; versions:{version:number;publishedAt:string|null}[]; _count:{executions:number} }
interface Execution { id:string; status:string; attempts:number; nextAttemptAt:string; lastError:string|null; workflow:{id:string;name:string;businessId:string} }
interface Runtime { counts:{status:string;count:number;retries:number}[]; deliveries:{status:string;count:number;attempts:number}[]; runtime:{status:string;count:number}[]; oldestPendingAt:string|null; last24Hours:{events:number;averageDurationMs:number|null;retries:number} }
interface Template { id:string; key:string; version:number; name:string; description:string|null; active:boolean }
interface Foundation { capabilities:Record<string,string>; killSwitches:Record<string,boolean>; providerKillSwitches:Record<string,boolean>; maintenance:boolean; updatedAt:string|null }

export default function AutomationPage() {
  const auth = useAuth();
  const workflows = useQuery({ queryKey:["platform-workflows"], queryFn:()=>apiFetch<{items:WorkflowRow[]}>("/admin/workflows"), refetchInterval:30_000 });
  const executions = useQuery({ queryKey:["workflow-executions"], queryFn:()=>apiFetch<{items:Execution[]}>("/admin/workflow-executions"), refetchInterval:15_000 });
  const runtime = useQuery({ queryKey:["automation-runtime"], queryFn:()=>apiFetch<Runtime>("/admin/outbox"), refetchInterval:15_000 });
  const foundation = useQuery({ queryKey:["automation-foundation"], queryFn:()=>apiFetch<Foundation>("/admin/automation/foundation"), refetchInterval:30_000 });
  const templates = useQuery({ queryKey:["workflow-templates"], queryFn:()=>apiFetch<{items:Template[]}>("/admin/workflow-templates") });
  const retry = useMutation({ mutationFn:(id:string)=>apiFetch(`/admin/workflow-executions/${id}/retry`,{method:"POST"}), onSuccess:async()=>{await Promise.all([executions.refetch(),runtime.refetch()]);} });
  const workflowAction = useMutation({ mutationFn:({id,action}:{id:string;action:"publish"|"pause"|"resume"})=>apiFetch(`/admin/workflows/${id}/${action}`,{method:"POST"}), onSuccess:async()=>{await workflows.refetch();} });
  const templateAction = useMutation({ mutationFn:({id,active}:{id:string;active:boolean})=>apiFetch(`/admin/workflow-templates/${id}/${active?"deactivate":"activate"}`,{method:"POST"}), onSuccess:async()=>{await templates.refetch();} });
  const queue = (executions.data?.items ?? []).filter(item=>["PENDING","RUNNING","PAUSED","FAILED"].includes(item.status));
  return <div className="page"><PageHeader eyebrow="Operations" title="Automation core" description="Durable events, workflow runtime, retry queues, failures, versions, and tenant workflow activity." actions={<span className="live-indicator"><i/>Live every 15s</span>}/><AdminWorkflowOperations workflowIds={(workflows.data?.items??[]).map(item=>({id:item.id,name:item.name}))}/>
    <section className="metrics-grid">{(runtime.data?.runtime ?? []).map(item=><article className="metric-card" key={item.status}><span>{item.status.replaceAll("_"," ")}</span><strong>{item.count}</strong><small>workflow executions</small></article>)}<article className="metric-card"><span>EVENT QUEUE</span><strong>{runtime.data?.counts.find(item=>item.status==="PENDING")?.count ?? 0}</strong><small>pending outbox events</small></article><article className="metric-card"><span>DELIVERY FAILURES</span><strong>{runtime.data?.deliveries.filter(item=>["RETRY","DEAD"].includes(item.status)).reduce((sum,item)=>sum+item.count,0) ?? 0}</strong><small>retry and dead-letter deliveries</small></article><article className="metric-card"><span>24H LATENCY</span><strong>{runtime.data?.last24Hours.averageDurationMs == null ? "—" : `${Math.round(runtime.data.last24Hours.averageDurationMs)} ms`}</strong><small>average completed execution</small></article></section>
    <Panel title="Workflow and version management" loading={workflows.isLoading} error={workflows.error} retry={()=>void workflows.refetch()}><DataTable columns={["Workflow","Tenant","Status","Versions","Executions","Updated","Controls"]} rows={(workflows.data?.items ?? []).map(item=>[<span className="icon-value"><Workflow size={15}/>{item.name}</span>,item.businessId,<StatusBadge value={item.status}/>,item.versions.map(version=>`${version.version}${version.publishedAt?" (live)":""}`).join(", ")||"—",item._count.executions,formatDate(item.updatedAt),<div className="page-actions">{item.status==="DRAFT"&&auth.hasPermission("workflow.publish")&&<button className="button ghost small" disabled={workflowAction.isPending} onClick={()=>workflowAction.mutate({id:item.id,action:"publish"})}><Send size={13}/>Publish latest</button>}{item.status==="PUBLISHED"&&auth.hasPermission("workflow.pause")&&<button className="button ghost small" disabled={workflowAction.isPending} onClick={()=>workflowAction.mutate({id:item.id,action:"pause"})}><CirclePause size={13}/>Pause</button>}{item.status==="PAUSED"&&auth.hasPermission("workflow.resume")&&<button className="button ghost small" disabled={workflowAction.isPending} onClick={()=>workflowAction.mutate({id:item.id,action:"resume"})}><CirclePlay size={13}/>Resume</button>}</div>])} empty={{title:"No workflows",description:"No hybrid workflows have been created."}}/>{workflowAction.error instanceof Error&&<p className="error-copy">{workflowAction.error.message}</p>}</Panel>
    <Panel title="Versioned workflow templates" loading={templates.isLoading} error={templates.error} retry={()=>void templates.refetch()}><DataTable columns={["Template","Key","Version","Status","Description","Control"]} rows={(templates.data?.items ?? []).map(item=>[item.name,item.key,item.version,<StatusBadge value={item.active?"ACTIVE":"INACTIVE"}/>,item.description??"—",auth.hasPermission("workflow.edit")?<button className="button ghost small" disabled={templateAction.isPending} onClick={()=>templateAction.mutate({id:item.id,active:item.active})}>{item.active?"Deactivate":"Activate"}</button>:"—"])} empty={{title:"No templates",description:"Template catalog initialization has not completed."}}/>{templateAction.error instanceof Error&&<p className="error-copy">{templateAction.error.message}</p>}</Panel>
    <Panel title="Retry and failure queues" loading={executions.isLoading} error={executions.error} retry={()=>void executions.refetch()}><DataTable columns={["Workflow","Tenant","Status","Attempts","Next attempt","Failure","Action"]} rows={queue.map(item=>[item.workflow.name,item.workflow.businessId,<StatusBadge value={item.status}/>,item.attempts,formatDate(item.nextAttemptAt),item.lastError ?? "—",item.status==="FAILED"&&auth.hasPermission("automation.retry")?<button className="button ghost small" disabled={retry.isPending} onClick={()=>retry.mutate(item.id)}><RotateCcw size={13}/>Retry</button>:"—"])} empty={{title:"Runtime queue is clear",description:"There are no pending retries or failures."}}/></Panel>
    <Panel title="Durable event delivery" loading={runtime.isLoading} error={runtime.error} retry={()=>void runtime.refetch()}><DataTable columns={["Delivery status","Count","Attempts"]} rows={(runtime.data?.deliveries ?? []).map(item=>[<StatusBadge value={item.status}/>,item.count,item.attempts])} empty={{title:"No event deliveries",description:"Delivery rows appear after outbox publication."}}/></Panel>
    <Panel title="Capabilities and kill switches" loading={foundation.isLoading} error={foundation.error} retry={()=>void foundation.refetch()}><DataTable columns={["Capability","Release status","Operational"]} rows={Object.entries(foundation.data?.capabilities??{}).map(([key,status])=>{const switchKey=["ai","messaging","providers","conversations"].includes(key)?key:"automation";return [key.replaceAll("_"," "),<StatusBadge value={status}/>,<StatusBadge value={foundation.data?.maintenance||foundation.data?.killSwitches[switchKey]===false?"DISABLED":"AVAILABLE"}/>];})} empty={{title:"No capability metadata",description:"Automation capability metadata has not been initialized."}}/>{foundation.data&&Object.keys(foundation.data.providerKillSwitches).length>0?<p className="error-copy">Disabled providers: {Object.keys(foundation.data.providerKillSwitches).join(", ")}</p>:null}</Panel>
  </div>;
}

function Panel({title,loading,error,retry,children}:{title:string;loading:boolean;error:Error|null;retry:()=>void;children:React.ReactNode}) { return <section className="panel table-panel"><div className="panel-heading"><div><p className="eyebrow">Automation</p><h2>{title}</h2></div></div>{loading?<LoadingState label={`Loading ${title.toLowerCase()}`}/>:error?<ErrorState message={error.message} onRetry={retry}/>:children}</section>; }
