import { useQuery } from "@tanstack/react-query";
import { Building2, SlidersHorizontal } from "lucide-react";
import { useDeferredValue, useState } from "react";
import { useNavigate } from "react-router-dom";
import { apiFetch, queryString, type PageEnvelope } from "../api";
import { DataTable, ErrorState, formatDate, LoadingState, PageHeader, Pagination, SearchInput, StatusBadge } from "../components/ui";

interface BusinessRow { id: string; name: string; industry: string | null; country: string | null; platformStatus: string; verifiedAt: string | null; onboardingCompletedAt: string | null; createdAt: string; lastActivityAt: string | null; owner: { fullName: string; email: string }; subscription: { plan: string; status: string } | null; _count: { members: number; customers: number; leads: number } }

export default function BusinessesPage() {
  const navigate = useNavigate();
  const [search, setSearch] = useState(""); const [plan, setPlan] = useState(""); const [status, setStatus] = useState(""); const [platformStatus, setPlatformStatus] = useState(""); const [sort, setSort] = useState("newest"); const [page, setPage] = useState(1);
  const deferredSearch = useDeferredValue(search);
  const params = { search: deferredSearch || undefined, plan: plan || undefined, subscriptionStatus: status || undefined, platformStatus: platformStatus || undefined, sort, page, pageSize: 25 };
  const query = useQuery({ queryKey: ["businesses", params], queryFn: () => apiFetch<PageEnvelope<BusinessRow>>(`/admin/businesses?${queryString(params)}`) });
  const rows = query.data?.items ?? [];
  return <div className="page"><PageHeader eyebrow="Platform directory" title="Businesses" description="Search, inspect, and operate every business on Chakusa." actions={<button className="button secondary"><SlidersHorizontal size={16} />Saved views</button>} /><div className="toolbar panel"><SearchInput value={search} onChange={(value) => { setSearch(value); setPage(1); }} placeholder="Search business, industry, owner, or email" /><div className="filters"><select value={platformStatus} onChange={(event) => { setPlatformStatus(event.target.value); setPage(1); }}><option value="">All platform states</option><option value="ACTIVE">ACTIVE</option><option value="SUSPENDED">SUSPENDED</option></select><select value={plan} onChange={(event) => { setPlan(event.target.value); setPage(1); }}><option value="">All plans</option><option>FREE</option><option>PRO</option><option>BUSINESS</option></select><select value={status} onChange={(event) => { setStatus(event.target.value); setPage(1); }}><option value="">All billing statuses</option><option>ACTIVE</option><option>TRIALING</option><option>GRACE_PERIOD</option><option>EXPIRED</option><option>CANCELED</option></select><select value={sort} onChange={(event) => setSort(event.target.value)}><option value="newest">Newest first</option><option value="oldest">Oldest first</option><option value="name">Name A–Z</option></select></div></div><section className="panel table-panel">{query.isLoading ? <LoadingState label="Loading businesses" /> : query.error ? <ErrorState message={(query.error as Error).message} onRetry={() => void query.refetch()} /> : <><DataTable columns={["Business", "Owner", "Platform", "Plan", "Customers", "Leads", "Last active", "Joined"]} rows={rows.map((item) => [<div className="primary-cell"><span className="entity-icon"><Building2 size={16} /></span><div><strong>{item.name}</strong><span>{item.industry ?? "Industry not set"}{item.country ? ` · ${item.country}` : ""}</span></div></div>, <div className="stacked-cell"><strong>{item.owner.fullName}</strong><span>{item.owner.email}</span></div>, <div className="badge-stack"><StatusBadge value={item.platformStatus} /><StatusBadge value={item.verifiedAt ? "verified" : "unverified"} /></div>, <div className="badge-stack"><StatusBadge value={item.subscription?.plan ?? "FREE"} /><StatusBadge value={item.subscription?.status ?? "ACTIVE"} /></div>, item._count.customers.toLocaleString(), item._count.leads.toLocaleString(), formatDate(item.lastActivityAt), formatDate(item.createdAt, false)])} empty={{ title: "No businesses found", description: "Try changing the search or filters." }} onRow={(index) => navigate(`/businesses/${rows[index].id}`)} /><Pagination page={query.data!.page} pageSize={query.data!.pageSize} total={query.data!.total} onPage={setPage} /></>}</section></div>;
}
