import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { ArrowLeft, BadgeCheck, Ban, ExternalLink, MapPin, PlayCircle, RotateCcw, Trash2, Users } from "lucide-react";
import { useState } from "react";
import { Link, useNavigate, useParams } from "react-router-dom";
import { apiFetch } from "../api";
import { useAuth } from "../auth";
import { ConfirmationDialog, DataTable, ErrorState, formatDate, formatMoney, formatNumber, LoadingState, MetricCard, StatusBadge } from "../components/ui";

type LifecycleAction = "verify" | "suspend" | "reactivate" | "delete";

export default function BusinessDetailPage() {
  const { id } = useParams();
  const navigate = useNavigate();
  const auth = useAuth();
  const queryClient = useQueryClient();
  const [resetOpen, setResetOpen] = useState(false);
  const [lifecycleAction, setLifecycleAction] = useState<LifecycleAction | null>(null);
  const [confirmation, setConfirmation] = useState("");
  const [reason, setReason] = useState("");
  const query = useQuery({ queryKey: ["business", id], queryFn: () => apiFetch<any>(`/admin/businesses/${id}`), enabled: Boolean(id) });
  const refresh = () => Promise.all([queryClient.invalidateQueries({ queryKey: ["business", id] }), queryClient.invalidateQueries({ queryKey: ["businesses"] })]);
  const close = () => { setResetOpen(false); setLifecycleAction(null); setConfirmation(""); setReason(""); };
  const resetMutation = useMutation({ mutationFn: () => apiFetch(`/admin/businesses/${id}/reset-onboarding`, { method: "POST", body: JSON.stringify({ confirmation }) }), onSuccess: async () => { close(); await refresh(); } });
  const lifecycleMutation = useMutation({ mutationFn: () => apiFetch(`/admin/businesses/${id}${lifecycleAction === "delete" ? "" : `/${lifecycleAction}`}`, { method: lifecycleAction === "delete" ? "DELETE" : "POST", body: JSON.stringify({ confirmation, ...(lifecycleAction === "suspend" || lifecycleAction === "delete" ? { reason } : {}) }) }), onSuccess: async () => { close(); if (lifecycleAction === "delete") navigate("/businesses"); else await refresh(); } });
  if (query.isLoading) return <LoadingState label="Loading business profile" />;
  if (query.error || !query.data) return <ErrorState message={(query.error as Error)?.message ?? "Business not found"} />;
  const { business, stats, recentAutomation } = query.data;
  const openLifecycle = (action: LifecycleAction) => { setLifecycleAction(action); setConfirmation(""); setReason(""); lifecycleMutation.reset(); };
  const lifecycleTitle = lifecycleAction === "verify" ? "Verify this business?" : lifecycleAction === "suspend" ? "Suspend this business?" : lifecycleAction === "delete" ? "Delete this business permanently?" : "Reactivate this business?";
  const lifecycleDescription = lifecycleAction === "verify" ? "Verification records an authoritative platform review without changing billing." : lifecycleAction === "suspend" ? "Product access, public entry points, and new automation execution will stop. Pending automation runs will be cancelled." : lifecycleAction === "delete" ? "This permanently removes the business and its platform data. The action cannot be undone." : "Product and public access will be restored. Previously cancelled automation runs remain cancelled.";
  const lifecycleLabel = lifecycleAction === "verify" ? "Verify business" : lifecycleAction === "suspend" ? "Suspend business" : lifecycleAction === "delete" ? "Delete business" : "Reactivate business";

  return <div className="page detail-page">
    <Link className="back-link" to="/businesses"><ArrowLeft size={16} />Back to businesses</Link>
    <header className="detail-header"><div className="detail-identity"><span className="entity-hero">{business.name[0]}</span><div><div className="detail-title-line"><h1>{business.name}</h1><StatusBadge value={business.platformStatus} /><StatusBadge value={business.verifiedAt ? "verified" : "unverified"} /><StatusBadge value={business.subscription?.plan ?? "FREE"} /></div><p>{business.industry ?? "Industry not set"}{business.country ? ` · ${business.country}` : ""}</p></div></div><div className="page-actions">{auth.hasPermission("business.verify") && !business.verifiedAt && <button className="button secondary" onClick={() => openLifecycle("verify")}><BadgeCheck size={15} />Verify</button>}{auth.hasPermission("business.suspend") && (business.platformStatus === "ACTIVE" ? <button className="button danger-outline" onClick={() => openLifecycle("suspend")}><Ban size={15} />Suspend</button> : <button className="button secondary" onClick={() => openLifecycle("reactivate")}><PlayCircle size={15} />Reactivate</button>)}{auth.hasPermission("business.delete") && business.platformStatus === "SUSPENDED" && <button className="button danger-outline" onClick={() => openLifecycle("delete")}><Trash2 size={15} />Delete</button>}{auth.hasPermission("business.onboarding.reset") && business.onboardingCompletedAt && <button className="button secondary" onClick={() => { setResetOpen(true); setConfirmation(""); }}><RotateCcw size={15} />Reset onboarding</button>}</div></header>
    <section className="metric-grid detail-metrics"><MetricCard label="Customers" value={formatNumber(stats.customers)} /><MetricCard label="Leads" value={formatNumber(stats.leads)} detail={`${stats.recoveredLeads} recovered`} /><MetricCard label="Recovered revenue" value={formatMoney(stats.recoveredRevenue, business.currency ?? "USD")} /><MetricCard label="Automation runs" value={formatNumber(stats.automationRuns)} /><MetricCard label="Review requests" value={formatNumber(stats.reviewRequests)} /><MetricCard label="Average rating" value={stats.averageRating == null ? "—" : `${formatNumber(stats.averageRating, 1)} / 5`} /></section>
    <section className="detail-grid"><article className="panel detail-card"><div className="panel-heading"><div><p className="eyebrow">Business profile</p><h2>Account information</h2></div></div><dl className="definition-list"><div><dt>Owner</dt><dd><strong>{business.owner.fullName}</strong><span>{business.owner.email}</span></dd></div><div><dt>Platform status</dt><dd><StatusBadge value={business.platformStatus} /></dd></div><div><dt>Verified</dt><dd>{formatDate(business.verifiedAt)}</dd></div>{business.suspendedAt && <div><dt>Suspension</dt><dd><strong>{formatDate(business.suspendedAt)}</strong><span>{business.suspensionReason}</span></dd></div>}<div><dt>Phone</dt><dd>{business.phone ?? "Not provided"}</dd></div><div><dt>Location</dt><dd>{business.country || business.timezone ? <><MapPin size={15} />{[business.country, business.timezone].filter(Boolean).join(" · ")}</> : "Not configured"}</dd></div><div><dt>Onboarding</dt><dd><StatusBadge value={business.onboardingCompletedAt ? "completed" : "pending"} /></dd></div><div><dt>Public profile</dt><dd>{business.publicSlug ? <span className="inline-link">/{business.publicSlug}<ExternalLink size={13} /></span> : "Not configured"}</dd></div><div><dt>Created</dt><dd>{formatDate(business.createdAt)}</dd></div></dl></article><article className="panel detail-card"><div className="panel-heading"><div><p className="eyebrow">Billing</p><h2>Subscription</h2></div></div>{business.subscription ? <dl className="definition-list"><div><dt>Current plan</dt><dd><StatusBadge value={business.subscription.plan} /></dd></div><div><dt>Status</dt><dd><StatusBadge value={business.subscription.status} /></dd></div><div><dt>Provider</dt><dd>{business.subscription.provider ?? "No provider"}</dd></div><div><dt>Current period</dt><dd>{formatDate(business.subscription.currentPeriodStart, false)} — {formatDate(business.subscription.currentPeriodEnd, false)}</dd></div><div><dt>Trial ends</dt><dd>{formatDate(business.subscription.trialEndsAt)}</dd></div><div><dt>Cancel at period end</dt><dd>{business.subscription.cancelAtPeriodEnd ? "Yes" : "No"}</dd></div></dl> : <p className="quiet-copy">No subscription row is available.</p>}</article></section>
    <section className="panel table-panel detail-section"><div className="panel-heading"><div><p className="eyebrow">Access</p><h2>Team members</h2></div><span>{business.members.length} seats</span></div><DataTable columns={["Member", "Role", "Status", "Joined"]} rows={business.members.map((member: any) => [<div className="primary-cell"><span className="entity-icon"><Users size={16} /></span><div><strong>{member.user.fullName}</strong><span>{member.user.email}</span></div></div>, <StatusBadge value={member.role} />, <StatusBadge value={member.status} />, formatDate(member.createdAt, false)])} empty={{ title: "No team members", description: "This business has no membership records." }} /></section>
    <section className="panel table-panel detail-section"><div className="panel-heading"><div><p className="eyebrow">Automation</p><h2>Recent runs</h2></div></div><DataTable columns={["Rule", "Trigger", "Status", "Attempts", "Scheduled", "Duration"]} rows={recentAutomation.map((run: any) => [run.automationRule.name, run.automationRule.triggerType.replaceAll("_", " "), <StatusBadge value={run.status} />, run.attemptCount, formatDate(run.scheduledFor), run.executionTimeMs == null ? "—" : `${(run.executionTimeMs / 1000).toFixed(1)}s`])} empty={{ title: "No automation history", description: "No runs have been recorded for this business." }} /></section>
    <ConfirmationDialog open={resetOpen} title="Reset business onboarding?" description="The business will be returned to the product onboarding flow. Existing business data is preserved." expected={business.name} value={confirmation} onChange={setConfirmation} onCancel={() => { close(); resetMutation.reset(); }} onConfirm={() => resetMutation.mutate()} pending={resetMutation.isPending} error={resetMutation.error instanceof Error ? resetMutation.error.message : undefined} confirmLabel="Reset onboarding" />
    <ConfirmationDialog open={lifecycleAction !== null} title={lifecycleTitle} description={lifecycleDescription} expected={business.name} value={confirmation} onChange={setConfirmation} onCancel={() => { close(); lifecycleMutation.reset(); }} onConfirm={() => lifecycleMutation.mutate()} pending={lifecycleMutation.isPending} error={lifecycleMutation.error instanceof Error ? lifecycleMutation.error.message : undefined} confirmLabel={lifecycleLabel}>{(lifecycleAction === "suspend" || lifecycleAction === "delete") && <label><span>Internal {lifecycleAction === "delete" ? "deletion" : "suspension"} reason</span><textarea value={reason} onChange={(event) => setReason(event.target.value)} minLength={10} maxLength={500} /></label>}</ConfirmationDialog>
  </div>;
}
