import { useQuery } from "@tanstack/react-query";
import { MessageSquareText } from "lucide-react";
import { useDeferredValue, useState } from "react";
import { apiFetch, queryString, type PageEnvelope } from "../api";
import { DataTable, ErrorState, formatDate, formatNumber, LoadingState, MetricCard, PageHeader, Pagination, SearchInput, StatusBadge } from "../components/ui";

interface Message { id: string; messageType: string; channel: string; body: string; status: string; sentAt: string | null; deliveredAt: string | null; provider: string | null; createdAt: string; source: string; business: { name: string }; customer: { name: string } | null }

export default function CommunicationsPage() {
  const [search, setSearch] = useState(""); const [status, setStatus] = useState(""); const [page, setPage] = useState(1);
  const params = { search: useDeferredValue(search) || undefined, status: status || undefined, page, pageSize: 25 };
  const overview = useQuery({ queryKey: ["communication-overview"], queryFn: () => apiFetch<Record<string, number>>("/admin/communications/overview") });
  const query = useQuery({ queryKey: ["communications", params], queryFn: () => apiFetch<PageEnvelope<Message>>(`/admin/communications?${queryString(params)}`) });
  const rows = query.data?.items ?? []; const metrics = overview.data;
  return <div className="page"><PageHeader eyebrow="Engagement operations" title="Communication center" description="Inspect delivery across messages, reminders, review requests, and automations." /><section className="metric-grid secondary-metrics"><MetricCard label="Messages" value={formatNumber(metrics?.messages)} /><MetricCard label="Delivered" value={formatNumber(metrics?.delivered)} tone="good" /><MetricCard label="Failed" value={formatNumber(metrics?.failed)} tone={metrics?.failed ? "danger" : "default"} /><MetricCard label="Templates" value={formatNumber(metrics?.templates)} /><MetricCard label="Review requests" value={formatNumber(metrics?.reviewRequests)} detail={`${formatNumber(metrics?.reviewsReceived)} received`} /><MetricCard label="Reminders due" value={formatNumber(metrics?.remindersDue)} tone={metrics?.remindersDue ? "warning" : "default"} /></section><div className="toolbar panel"><SearchInput value={search} onChange={(value) => { setSearch(value); setPage(1); }} placeholder="Search message, business, or customer" /><div className="filters"><select value={status} onChange={(e) => { setStatus(e.target.value); setPage(1); }}><option value="">All delivery states</option><option>draft</option><option>copied</option><option>sent</option><option>delivered</option><option>failed</option><option>undelivered</option></select></div></div><section className="panel table-panel">{query.isLoading ? <LoadingState label="Loading communications" /> : query.error ? <ErrorState message={(query.error as Error).message} onRetry={() => void query.refetch()} /> : <><DataTable columns={["Message", "Business / customer", "Channel", "Source", "Delivery", "Sent"]} rows={rows.map((message) => [<div className="primary-cell"><span className="entity-icon"><MessageSquareText size={16} /></span><div><strong>{message.messageType.replaceAll("_", " ")}</strong><span className="message-preview">{message.body}</span></div></div>, <div className="stacked-cell"><strong>{message.business.name}</strong><span>{message.customer?.name ?? "No customer"}</span></div>, <StatusBadge value={message.channel} />, message.source, <StatusBadge value={message.status} />, formatDate(message.sentAt ?? message.createdAt)])} empty={{ title: "No communications found", description: "No delivery records match the filters." }} /><Pagination page={query.data!.page} pageSize={query.data!.pageSize} total={query.data!.total} onPage={setPage} /></>}</section></div>;
}
