import { useQuery } from "@tanstack/react-query";
import { MessageSquareText } from "lucide-react";
import { useDeferredValue, useState } from "react";
import { apiFetch, queryString, type PageEnvelope } from "../api";
import { DataTable, ErrorState, formatDate, formatNumber, LoadingState, MetricCard, PageHeader, Pagination, SearchInput, StatusBadge } from "../components/ui";

interface Message { id: string; messageType: string; channel: string; body: string; status: string; direction: string; actorType: string; sentAt: string | null; deliveredAt: string | null; provider: string | null; providerErrorCode: string | null; createdAt: string; source: string; dispatches: Array<{status:string;attempts:number;lastError:string|null}>; business: { name: string }; customer: { name: string } | null }

export default function CommunicationsPage() {
  const [search, setSearch] = useState(""); const [status, setStatus] = useState(""); const [page, setPage] = useState(1);
  const params = { search: useDeferredValue(search) || undefined, status: status || undefined, page, pageSize: 25 };
  const overview = useQuery({ queryKey: ["communication-overview"], queryFn: () => apiFetch<Record<string, number>>("/admin/communications/overview") });
  const operations = useQuery({ queryKey: ["communication-operations"], queryFn: () => apiFetch<{providers:Array<{status:string;healthStatus:string}>;credentials:Array<{validationStatus:string;expiresAt:string|null}>;templates:unknown[];slas:Array<{status:string;_count:number}>;attachments:Array<{uploadStatus:string;_count:number}>}>("/admin/communications/operations") });
  const query = useQuery({ queryKey: ["communications", params], queryFn: () => apiFetch<PageEnvelope<Message>>(`/admin/communications?${queryString(params)}`) });
  const rows = query.data?.items ?? []; const metrics = overview.data; const operational = operations.data;
  return <div className="page"><PageHeader eyebrow="Engagement operations" title="Communication center" description="Inspect conversation traffic, durable dispatch, provider delivery, and failures." /><section className="metric-grid secondary-metrics"><MetricCard label="Messages" value={formatNumber(metrics?.messages)} /><MetricCard label="Open conversations" value={formatNumber(metrics?.openConversations)} /><MetricCard label="Pending dispatch" value={formatNumber(metrics?.pendingDispatches)} /><MetricCard label="Dead letters" value={formatNumber(metrics?.deadDispatches)} tone={metrics?.deadDispatches ? "danger" : "default"} /><MetricCard label="Delivered" value={formatNumber(metrics?.delivered)} tone="good" /><MetricCard label="Failed" value={formatNumber(metrics?.failed)} tone={metrics?.failed ? "danger" : "default"} /></section><div className="toolbar panel"><SearchInput value={search} onChange={(value) => { setSearch(value); setPage(1); }} placeholder="Search message, business, or customer" /><div className="filters"><select value={status} onChange={(e) => { setStatus(e.target.value); setPage(1); }}><option value="">All delivery states</option><option>draft</option><option>sent</option><option>delivered</option><option>failed</option></select></div></div><section className="panel table-panel">{query.isLoading ? <LoadingState label="Loading communications" /> : query.error ? <ErrorState message={(query.error as Error).message} onRetry={() => void query.refetch()} /> : <><DataTable columns={["Message", "Business / customer", "Channel", "Source", "Delivery", "Dispatch", "Sent"]} rows={rows.map((message) => [<div className="primary-cell"><span className="entity-icon"><MessageSquareText size={16} /></span><div><strong>{message.messageType.replaceAll("_", " ")}</strong><span className="message-preview">{message.body}</span></div></div>, <div className="stacked-cell"><strong>{message.business.name}</strong><span>{message.customer?.name ?? "No customer"}</span></div>, <StatusBadge value={message.channel} />, message.source, <StatusBadge value={message.status} />, message.dispatches[0] ? <div className="stacked-cell"><StatusBadge value={message.dispatches[0].status}/><span>{message.dispatches[0].attempts} attempts{message.dispatches[0].lastError ? ` · ${message.dispatches[0].lastError}` : ""}</span></div> : "Not queued", formatDate(message.sentAt ?? message.createdAt)])} empty={{ title: "No communications found", description: "No delivery records match the filters." }} /><Pagination page={query.data!.page} pageSize={query.data!.pageSize} total={query.data!.total} onPage={setPage} /></>}</section></div>;
}
