import { useQuery } from "@tanstack/react-query";
import { FileText } from "lucide-react";
import { apiFetch } from "../api";
import { DataTable, ErrorState, formatDate, formatMoney, formatNumber, LoadingState, MetricCard, PageHeader, StatusBadge } from "../components/ui";

interface PaymentSummary { source: string; status: string; currency: string; count: number; amount: number; refundedAmount: number }
interface Invoice { id: string; invoiceNumber: string; status: string; currency: string; issueDate: string | null; dueDate: string | null; updatedAt: string; total: number | null; business: { id: string; name: string } }
interface Quote { id: string; documentNumber: string; documentType: string; status: string; currency: string; expiresAt: string | null; updatedAt: string; total: number | null; business: { id: string; name: string } }
interface FinanceData { quotes: Record<string, number>; invoices: Record<string, number>; payments: PaymentSummary[]; recentInvoices: Invoice[]; recentQuotes: Quote[] }

const sum = (values: Record<string, number>) => Object.values(values).reduce((total, value) => total + value, 0);

export default function FinanceOperationsPage() {
  const query = useQuery({ queryKey: ["admin-finance-operations"], queryFn: () => apiFetch<FinanceData>("/admin/finance/operations") });
  if (query.isLoading) return <div className="page"><LoadingState label="Loading finance operations" /></div>;
  if (query.error || !query.data) return <div className="page"><ErrorState message={(query.error as Error)?.message || "Finance operations are unavailable"} onRetry={() => void query.refetch()} /></div>;
  const data = query.data; const paid = data.payments.filter((row) => row.status === "paid" || row.status === "partially_refunded"); const failed = data.payments.filter((row) => row.status === "failed").reduce((total, row) => total + row.count, 0);
  return <div className="page"><PageHeader eyebrow="Business commerce" title="Finance operations" description="Read-only oversight for quotes, invoices, and verified payment ledgers produced by business dashboards." actions={<button className="button secondary" onClick={() => void query.refetch()}>Refresh data</button>} />
    <section className="metric-grid primary-metrics"><MetricCard label="Quotes" value={formatNumber(sum(data.quotes))} detail={`${formatNumber(data.quotes.ACCEPTED)} accepted`} /><MetricCard label="Invoices" value={formatNumber(sum(data.invoices))} detail={`${formatNumber(data.invoices.SENT)} sent`} /><MetricCard label="Paid transactions" value={formatNumber(paid.reduce((total, row) => total + row.count, 0))} tone="good" /><MetricCard label="Failed transactions" value={formatNumber(failed)} tone={failed ? "warning" : "default"} /><MetricCard label="Draft documents" value={formatNumber((data.quotes.DRAFT ?? 0) + (data.invoices.DRAFT ?? 0))} /><MetricCard label="Payment currencies" value={formatNumber(new Set(data.payments.map((row) => row.currency)).size)} detail="Kept separate by currency" /></section>
    <section className="dashboard-grid activity-grid"><article className="panel table-panel"><div className="panel-heading"><div><p className="eyebrow">Invoices</p><h2>Recently updated</h2></div><FileText size={18} /></div><DataTable columns={["Business", "Invoice", "Status", "Total", "Due"]} rows={data.recentInvoices.map((item) => [item.business.name, item.invoiceNumber, <StatusBadge value={item.status} />, item.total == null ? "Not finalised" : formatMoney(item.total, item.currency), formatDate(item.dueDate, false)])} empty={{ title: "No invoices", description: "Invoices created in business dashboards will appear here." }} /></article>
    <article className="panel table-panel"><div className="panel-heading"><div><p className="eyebrow">Quotes and estimates</p><h2>Recently updated</h2></div><FileText size={18} /></div><DataTable columns={["Business", "Document", "Status", "Total", "Expires"]} rows={data.recentQuotes.map((item) => [item.business.name, <div className="stacked-cell"><strong>{item.documentNumber}</strong><span>{item.documentType.toLowerCase()}</span></div>, <StatusBadge value={item.status} />, item.total == null ? "Not finalised" : formatMoney(item.total, item.currency), formatDate(item.expiresAt, false)])} empty={{ title: "No quotes", description: "Quotes created in business dashboards will appear here." }} /></article></section>
    <section className="panel table-panel detail-section"><div className="panel-heading"><div><p className="eyebrow">Verified ledgers</p><h2>Payment totals by source and currency</h2></div></div><DataTable columns={["Source", "Currency", "Status", "Transactions", "Gross amount", "Refunded"]} rows={data.payments.map((item) => [item.source, item.currency.toUpperCase(), <StatusBadge value={item.status} />, formatNumber(item.count), formatMoney(item.amount, item.currency), formatMoney(item.refundedAmount, item.currency)])} empty={{ title: "No payment transactions", description: "Payment data remains empty until payment processing is enabled and verified." }} /></section>
  </div>;
}
