CREATE TABLE "ai_model_registry" ("id" TEXT NOT NULL, "provider" TEXT NOT NULL, "model" TEXT NOT NULL, "version" TEXT NOT NULL, "capabilities" JSONB NOT NULL, "pricing" JSONB, "supported_languages" JSONB, "approved_use_cases" JSONB NOT NULL, "status" TEXT NOT NULL DEFAULT 'ACTIVE', "health_status" TEXT NOT NULL DEFAULT 'UNKNOWN', "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updated_at" TIMESTAMP(3) NOT NULL, CONSTRAINT "ai_model_registry_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "ai_model_registry_provider_model_version_key" ON "ai_model_registry"("provider", "model", "version");
CREATE INDEX "ai_model_registry_status_health_status_idx" ON "ai_model_registry"("status", "health_status");
CREATE TABLE "ai_invocation_ledger" ("id" TEXT NOT NULL, "business_id" TEXT NOT NULL, "customer_id" TEXT, "conversation_id" TEXT, "workflow_execution_id" TEXT, "provider" TEXT NOT NULL, "model" TEXT NOT NULL, "model_version" TEXT, "prompt_version" TEXT NOT NULL, "prompt_checksum" TEXT NOT NULL, "input_tokens" INTEGER, "output_tokens" INTEGER, "reasoning_tokens" INTEGER, "cost" DECIMAL(14,6), "latency_ms" INTEGER, "correlation_id" TEXT, "causation_id" TEXT, "confidence" DOUBLE PRECISION, "safety_result" TEXT NOT NULL, "outcome" TEXT NOT NULL, "tool_requests" JSONB, "approval_status" TEXT NOT NULL DEFAULT 'NOT_REQUIRED', "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "ai_invocation_ledger_pkey" PRIMARY KEY ("id"));
CREATE INDEX "ai_invocation_ledger_business_id_created_at_idx" ON "ai_invocation_ledger"("business_id", "created_at");
CREATE INDEX "ai_invocation_ledger_conversation_id_created_at_idx" ON "ai_invocation_ledger"("conversation_id", "created_at");
CREATE TABLE "ai_conversation_runs" ("id" TEXT NOT NULL, "business_id" TEXT NOT NULL, "customer_id" TEXT, "conversation_id" TEXT NOT NULL, "status" TEXT NOT NULL DEFAULT 'RECEIVED', "mode" TEXT NOT NULL DEFAULT 'DRAFT', "state" JSONB NOT NULL DEFAULT '{}', "idempotency_key" TEXT NOT NULL, "last_error" TEXT, "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updated_at" TIMESTAMP(3) NOT NULL, CONSTRAINT "ai_conversation_runs_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "ai_conversation_runs_idempotency_key_key" ON "ai_conversation_runs"("idempotency_key");
CREATE INDEX "ai_conversation_runs_business_id_status_updated_at_idx" ON "ai_conversation_runs"("business_id", "status", "updated_at");
