import { Ionicons } from '@expo/vector-icons';
import { useState } from 'react';
import { Alert, Platform, Pressable, StyleSheet, Text, View } from 'react-native';
import { AppHeader, Screen } from '../components/ui';
import { useAuth } from '../state/AuthContext';
import { colors, radius, spacing, typography } from '../theme';
import { titleCase } from '../utils/format';

export function AccountInformationScreen() {
  const { user, business, role, linkGoogle, linkApple } = useAuth(); const [linking, setLinking] = useState<'GOOGLE'|'APPLE'|null>(null); const providers = user?.authProviders ?? [];
  const link = async (provider: 'GOOGLE'|'APPLE') => { if (linking) return; setLinking(provider); try { const linked = provider === 'GOOGLE' ? await linkGoogle() : await linkApple(); if (linked) Alert.alert('Account secured', `${provider === 'GOOGLE' ? 'Google' : 'Apple'} is now connected to your CHAKUSA account.`); } catch (error) { Alert.alert('Could not connect account', error instanceof Error ? error.message : 'Please try again.'); } finally { setLinking(null); } };
  return <Screen><AppHeader eyebrow="ACCOUNT & SECURITY" title={user?.fullName ?? 'Your account'} subtitle="Your identity, access methods, and business membership" /><Text style={styles.sectionTitle}>IDENTITY</Text><View style={styles.card}><Field icon="person-outline" label="Name" value={user?.fullName} /><Field icon="mail-outline" label="Email" value={user?.email} /><Field icon="storefront-outline" label="Business" value={business?.name} /><Field icon="shield-outline" label="Role" value={role ? titleCase(role) : undefined} last /></View><Text style={styles.sectionTitle}>SIGN-IN METHODS</Text><View style={styles.card}><ProviderRow connected={providers.includes('GOOGLE')} label="Google" loading={linking === 'GOOGLE'} onConnect={() => void link('GOOGLE')} />{Platform.OS === 'ios' ? <ProviderRow connected={providers.includes('APPLE')} label="Apple" loading={linking === 'APPLE'} onConnect={() => void link('APPLE')} /> : null}{user?.hasPassword ? <View style={styles.provider}><Ionicons name="key-outline" size={21} color={colors.textSecondary} /><View style={styles.providerCopy}><Text style={styles.value}>Email and password</Text><Text style={styles.detail}>Connected</Text></View><Ionicons name="checkmark-circle" size={22} color={colors.success} /></View> : null}</View><View style={styles.notice}><Ionicons name="information-circle-outline" size={22} color={colors.primary} /><Text style={styles.noticeText}>Logging out of this device does not affect your other devices. Use “Log out of all devices” in Settings if another session should no longer have access.</Text></View></Screen>;
}
function Field({ icon, label, value, last }: { icon: keyof typeof Ionicons.glyphMap; label: string; value?: string | null; last?: boolean }) { return <View style={[styles.field, !last && styles.border]}><Ionicons name={icon} size={20} color={colors.textSecondary} /><View style={styles.fieldCopy}><Text style={styles.label}>{label}</Text><Text selectable style={styles.value}>{value || 'Not available'}</Text></View></View>; }
function ProviderRow({ connected, label, loading, onConnect }: { connected: boolean; label: string; loading: boolean; onConnect: () => void }) { return <View style={[styles.provider, styles.border]}><Ionicons name={label === 'Google' ? 'logo-google' : 'logo-apple'} size={21} color={colors.textSecondary} /><View style={styles.providerCopy}><Text style={styles.value}>{label}</Text><Text style={styles.detail}>{connected ? 'Connected' : 'Not connected'}</Text></View>{connected ? <Ionicons name="checkmark-circle" size={22} color={colors.success} /> : <Pressable accessibilityRole="button" disabled={loading} onPress={onConnect} style={({ pressed }) => [styles.connect, pressed && styles.pressed]}><Text style={styles.connectText}>{loading ? 'Connecting…' : 'Connect'}</Text></Pressable>}</View>; }
const styles = StyleSheet.create({ sectionTitle: { ...typography.micro, color: colors.textSecondary, marginBottom: spacing.xs, letterSpacing: 1 }, card: { backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, borderRadius: radius.md, paddingHorizontal: spacing.lg }, field: { minHeight: 68, flexDirection: 'row', alignItems: 'center', gap: spacing.md }, fieldCopy: { flex: 1, gap: spacing.xxs }, border: { borderBottomWidth: 1, borderBottomColor: colors.divider }, label: { ...typography.caption, color: colors.textSecondary }, value: { ...typography.bodyStrong, color: colors.text }, detail: { ...typography.caption, color: colors.textSecondary }, provider: { minHeight: 64, flexDirection: 'row', alignItems: 'center', gap: spacing.md }, providerCopy: { flex: 1 }, connect: { minHeight: 40, justifyContent: 'center', paddingHorizontal: spacing.md, borderRadius: radius.round, backgroundColor: colors.primarySoft }, connectText: { ...typography.caption, color: colors.primary, fontWeight: '700' }, pressed: { opacity: 0.7 }, notice: { flexDirection: 'row', alignItems: 'flex-start', gap: spacing.sm, borderRadius: radius.md, backgroundColor: colors.primarySoft, padding: spacing.md }, noticeText: { ...typography.caption, color: colors.text, flex: 1 } });
