import { Ionicons } from '@expo/vector-icons';
import { useState } from 'react';
import { Alert, Platform, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { AppHeader, PrimaryButton, Screen } from '../components/ui';
import { useAuth } from '../state/AuthContext';
import { colors, radius, spacing, typography } from '../theme';
import { titleCase } from '../utils/format';

const editorStyles = StyleSheet.create({ editor: { gap: spacing.sm, padding: spacing.md, borderRadius: radius.md, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border }, title: { ...typography.bodyStrong, color: colors.text }, input: { minHeight: 48, borderRadius: radius.md, borderWidth: 1, borderColor: colors.border, paddingHorizontal: spacing.md, ...typography.body, color: colors.text } });

export function AccountInformationScreen() {
  const { user, business, role, linkGoogle, linkApple, updateProfile, changePassword } = useAuth(); const [linking, setLinking] = useState<'GOOGLE'|'APPLE'|null>(null); const [name, setName] = useState(user?.fullName ?? ''); const [currentPassword, setCurrentPassword] = useState(''); const [newPassword, setNewPassword] = useState(''); const [saving, setSaving] = useState<'profile'|'password'|null>(null); const providers = user?.authProviders ?? [];
  const link = async (provider: 'GOOGLE'|'APPLE') => { if (linking) return; setLinking(provider); try { const linked = provider === 'GOOGLE' ? await linkGoogle() : await linkApple(); if (linked) Alert.alert('Account secured', `${provider === 'GOOGLE' ? 'Google' : 'Apple'} is now connected to your CHAKUSA account.`); } catch (error) { Alert.alert('Could not connect account', error instanceof Error ? error.message : 'Please try again.'); } finally { setLinking(null); } };
  const saveProfile = async () => { if (saving || !name.trim()) return; setSaving('profile'); try { await updateProfile(name.trim()); Alert.alert('Profile updated', 'Your name has been saved.'); } catch (error) { Alert.alert('Could not update profile', error instanceof Error ? error.message : 'Please try again.'); } finally { setSaving(null); } };
  const savePassword = async () => { if (saving || newPassword.length < 8) return; setSaving('password'); try { await changePassword(user?.hasPassword ? currentPassword : undefined, newPassword); setCurrentPassword(''); setNewPassword(''); Alert.alert('Password updated', 'Other signed-in devices have been logged out for your security.'); } catch (error) { Alert.alert('Could not update password', error instanceof Error ? error.message : 'Please try again.'); } finally { setSaving(null); } };
  return <Screen><AppHeader eyebrow="ACCOUNT & SECURITY" title={user?.fullName ?? 'Your account'} subtitle="Your identity, access methods, and business membership" /><Text style={styles.sectionTitle}>IDENTITY</Text><View style={styles.card}><Field icon="mail-outline" label="Email" value={user?.email} /><Field icon="storefront-outline" label="Business" value={business?.name} /><Field icon="shield-outline" label="Role" value={role ? titleCase(role) : undefined} last /></View><View style={editorStyles.editor}><Text style={editorStyles.title}>Edit profile</Text><TextInput accessibilityLabel="Full name" value={name} onChangeText={setName} placeholder="Full name" placeholderTextColor={colors.textSecondary} style={editorStyles.input} /><PrimaryButton fullWidth disabled={Boolean(saving) || !name.trim()} label={saving === 'profile' ? 'Saving…' : 'Save name'} onPress={() => void saveProfile()} /></View><Text style={styles.sectionTitle}>SIGN-IN METHODS</Text><View style={styles.card}><ProviderRow connected={providers.includes('GOOGLE')} label="Google" loading={linking === 'GOOGLE'} onConnect={() => void link('GOOGLE')} />{Platform.OS === 'ios' ? <ProviderRow connected={providers.includes('APPLE')} label="Apple" loading={linking === 'APPLE'} onConnect={() => void link('APPLE')} /> : null}{user?.hasPassword ? <View style={styles.provider}><Ionicons name="key-outline" size={21} color={colors.textSecondary} /><View style={styles.providerCopy}><Text style={styles.value}>Email and password</Text><Text style={styles.detail}>Connected</Text></View><Ionicons name="checkmark-circle" size={22} color={colors.success} /></View> : null}</View><View style={editorStyles.editor}><Text style={editorStyles.title}>{user?.hasPassword ? 'Change password' : 'Create a password'}</Text>{user?.hasPassword ? <TextInput accessibilityLabel="Current password" secureTextEntry value={currentPassword} onChangeText={setCurrentPassword} placeholder="Current password" placeholderTextColor={colors.textSecondary} style={editorStyles.input} /> : null}<TextInput accessibilityLabel="New password" secureTextEntry value={newPassword} onChangeText={setNewPassword} placeholder="New password (8+ characters)" placeholderTextColor={colors.textSecondary} style={editorStyles.input} /><PrimaryButton fullWidth disabled={Boolean(saving) || newPassword.length < 8 || Boolean(user?.hasPassword && !currentPassword)} label={saving === 'password' ? 'Updating…' : user?.hasPassword ? 'Change password' : 'Create password'} onPress={() => void savePassword()} /></View><View style={styles.notice}><Ionicons name="information-circle-outline" size={22} color={colors.primary} /><Text style={styles.noticeText}>Logging out of this device does not affect your other devices. Password changes log out other devices automatically.</Text></View></Screen>;
}
function Field({ icon, label, value, last }: { icon: keyof typeof Ionicons.glyphMap; label: string; value?: string | null; last?: boolean }) { return <View style={[styles.field, !last && styles.border]}><Ionicons name={icon} size={20} color={colors.textSecondary} /><View style={styles.fieldCopy}><Text style={styles.label}>{label}</Text><Text selectable style={styles.value}>{value || 'Not available'}</Text></View></View>; }
function ProviderRow({ connected, label, loading, onConnect }: { connected: boolean; label: string; loading: boolean; onConnect: () => void }) { return <View style={[styles.provider, styles.border]}><Ionicons name={label === 'Google' ? 'logo-google' : 'logo-apple'} size={21} color={colors.textSecondary} /><View style={styles.providerCopy}><Text style={styles.value}>{label}</Text><Text style={styles.detail}>{connected ? 'Connected' : 'Not connected'}</Text></View>{connected ? <Ionicons name="checkmark-circle" size={22} color={colors.success} /> : <Pressable accessibilityRole="button" disabled={loading} onPress={onConnect} style={({ pressed }) => [styles.connect, pressed && styles.pressed]}><Text style={styles.connectText}>{loading ? 'Connecting…' : 'Connect'}</Text></Pressable>}</View>; }
const styles = StyleSheet.create({ sectionTitle: { ...typography.micro, color: colors.textSecondary, marginBottom: spacing.xs, letterSpacing: 1 }, card: { backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, borderRadius: radius.md, paddingHorizontal: spacing.lg }, field: { minHeight: 68, flexDirection: 'row', alignItems: 'center', gap: spacing.md }, fieldCopy: { flex: 1, gap: spacing.xxs }, border: { borderBottomWidth: 1, borderBottomColor: colors.divider }, label: { ...typography.caption, color: colors.textSecondary }, value: { ...typography.bodyStrong, color: colors.text }, detail: { ...typography.caption, color: colors.textSecondary }, provider: { minHeight: 64, flexDirection: 'row', alignItems: 'center', gap: spacing.md }, providerCopy: { flex: 1 }, connect: { minHeight: 40, justifyContent: 'center', paddingHorizontal: spacing.md, borderRadius: radius.round, backgroundColor: colors.primarySoft }, connectText: { ...typography.caption, color: colors.primary, fontWeight: '700' }, pressed: { opacity: 0.7 }, notice: { flexDirection: 'row', alignItems: 'flex-start', gap: spacing.sm, borderRadius: radius.md, backgroundColor: colors.primarySoft, padding: spacing.md }, noticeText: { ...typography.caption, color: colors.text, flex: 1 } });
