import { NativeStackScreenProps } from '@react-navigation/native-stack';
import { useCallback, useEffect, useState } from 'react';
import { Pressable, RefreshControl, ScrollView as NativeScrollView, ScrollViewProps, StyleSheet, Text, View } from 'react-native';
import { AttentionCategory, AttentionItemDto } from '../apiTypes';
import { AppHeader, EmptyState, ErrorState, LoadingState, PrimaryButton, Screen } from '../components/ui';
import { ApiError } from '../services/api';
import { dashboardApi } from '../services/endpoints';
import { colors, radius, spacing, typography } from '../theme';
import { RootStackParamList } from '../types';
import { formatDateTime } from '../utils/format';
type Props = NativeStackScreenProps<RootStackParamList, 'AttentionCenter'>;
const categories: { value: AttentionCategory; label: string }[] = [{ value: 'missed_call_followup', label: 'Missed calls' }, { value: 'customer_due', label: 'Due back' }, { value: 'review_opportunity', label: 'Reviews' }];
function ScrollView({ refreshing, onRefresh, ...props }: ScrollViewProps & { refreshing: boolean; onRefresh: () => void }) { return <NativeScrollView {...props} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={onRefresh} />} />; }
export function ActionQueueScreen({ navigation }: Props) {
  const [category, setCategory] = useState<AttentionCategory>('missed_call_followup'); const [items, setItems] = useState<AttentionItemDto[]>([]); const [page, setPage] = useState(1); const [total, setTotal] = useState(0); const [loading, setLoading] = useState(true); const [refreshing, setRefreshing] = useState(false); const [error, setError] = useState<string | null>(null);
  const load = useCallback(async (nextPage = 1, append = false) => { setLoading(true); setError(null); try { const result = await dashboardApi.attention(category, nextPage, 25); setItems(current => append ? [...current, ...result.items] : result.items); setTotal(result.total); setPage(result.page); } catch (caught) { setError(caught instanceof ApiError ? caught.message : 'Unable to load your action queue.'); } finally { setLoading(false); setRefreshing(false); } }, [category]);
  useEffect(() => { void load(); }, [load]); const refresh = () => { setRefreshing(true); void load(); };
  const open = (item: AttentionItemDto) => item.category === 'missed_call_followup' ? navigation.navigate('LeadDetail', { leadId: item.id }) : item.category === 'customer_due' ? navigation.navigate('Comeback') : navigation.navigate('ReviewDetail', { reviewId: item.id });
  return <Screen scroll={false} style={styles.screen}><AppHeader eyebrow="WHAT NEEDS ACTION" title="Attention Center" subtitle={`${total} action${total === 1 ? '' : 's'} in this category`} /><View style={styles.tabs}>{categories.map(item => <Pressable accessibilityRole="button" key={item.value} onPress={() => setCategory(item.value)} style={[styles.tab, category === item.value && styles.active]}><Text style={[styles.tabText, category === item.value && styles.activeText]}>{item.label}</Text></Pressable>)}</View><ScrollView contentContainerStyle={styles.list} refreshing={refreshing} onRefresh={refresh}>{loading && !items.length ? <LoadingState label="Loading your action queue…" /> : error && !items.length ? <ErrorState message={error} onRetry={() => void load()} /> : !items.length ? <EmptyState title="You're caught up" message="No actions in this category right now." /> : <>{items.map(item => <Pressable accessibilityRole="button" key={`${item.category}-${item.id}`} onPress={() => open(item)} style={styles.item}><View style={styles.copy}><Text style={styles.kind}>{item.category === 'missed_call_followup' ? 'Missed-call follow-up' : item.category === 'customer_due' ? 'Customer due back' : 'Review opportunity'}</Text><Text style={styles.customer}>{item.customerName ?? 'Unassigned customer'}</Text><Text style={styles.meta}>{item.detail ?? 'Service not specified'} · {formatDateTime(item.occurredAt)}</Text></View><Text style={styles.action}>{item.category === 'missed_call_followup' ? 'Follow up' : item.category === 'customer_due' ? 'Bring back' : 'Request review'}</Text></Pressable>)}{items.length < total ? <PrimaryButton disabled={loading} fullWidth label={loading ? 'Loading…' : 'Load more'} onPress={() => void load(page + 1, true)} /> : null}</>}</ScrollView></Screen>;
}
const styles = StyleSheet.create({ screen: { paddingBottom: spacing.lg }, tabs: { flexDirection: 'row', gap: spacing.xs }, tab: { flex: 1, minHeight: 44, alignItems: 'center', justifyContent: 'center', borderRadius: radius.round, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface }, active: { backgroundColor: colors.text }, tabText: { ...typography.caption, color: colors.textSecondary }, activeText: { color: colors.surface }, list: { gap: spacing.sm, paddingBottom: spacing.lg }, item: { minHeight: 88, flexDirection: 'row', alignItems: 'center', gap: spacing.sm, padding: spacing.md, borderRadius: radius.md, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface }, copy: { flex: 1 }, kind: { ...typography.caption, color: colors.textSecondary }, customer: { ...typography.bodyStrong, color: colors.text }, meta: { ...typography.caption, color: colors.textSecondary }, action: { ...typography.caption, color: colors.primary, fontWeight: '700', maxWidth: 70 } });
