import * as DocumentPicker from 'expo-document-picker';
import { File } from 'expo-file-system';
import { useNavigation } from '@react-navigation/native';
import { NativeStackNavigationProp } from '@react-navigation/native-stack';
import { useMemo, useState } from 'react';
import { StyleSheet, Text, TextInput, View } from 'react-native';
import { AppHeader, PrimaryButton, Screen, SecondaryButton } from '../components/ui';
import { parseAppointmentImportText } from '../domain/appointmentsImport';
import { ApiError } from '../services/api';
import { appointmentsApi } from '../services/endpoints';
import { colors, radius, spacing, typography } from '../theme';
import { RootStackParamList } from '../types';
export function AppointmentsImportScreen() {
  const navigation = useNavigation<NativeStackNavigationProp<RootStackParamList>>(); const [text, setText] = useState(''); const [fileName, setFileName] = useState<string | null>(null); const [importing, setImporting] = useState(false); const [error, setError] = useState<string | null>(null); const [result, setResult] = useState<{ created: { id: string }[]; skipped: { reason: string }[]; failed: { reason: string }[] } | null>(null); const parsed = useMemo(() => parseAppointmentImportText(text), [text]);
  const chooseFile = async () => { setError(null); try { const picked = await DocumentPicker.getDocumentAsync({ type: ['text/csv', 'text/plain', 'text/tab-separated-values'], copyToCacheDirectory: true }); if (picked.canceled) return; const asset = picked.assets[0]; if (!asset) return; if ((asset.size ?? 0) > 1_000_000) { setError('Choose a CSV file smaller than 1 MB.'); return; } setText(await new File(asset.uri).text()); setFileName(asset.name); } catch { setError('Unable to read that appointment file.'); } };
  const submit = async () => { if (!parsed.rows.length || importing) return; setImporting(true); setError(null); try { setResult(await appointmentsApi.bulkImport(parsed.rows)); } catch (caught) { setError(caught instanceof ApiError ? caught.message : 'Unable to import appointments.'); } finally { setImporting(false); } };
  if (result) return <Screen><AppHeader eyebrow="CALENDAR" title="Appointment import complete" subtitle={`${result.created.length} appointments added`} /><View style={styles.summary}><Text style={styles.result}>{result.created.length} added</Text><Text style={styles.result}>{result.skipped.length} duplicates skipped</Text><Text style={styles.result}>{result.failed.length} failed</Text></View><PrimaryButton fullWidth label="Done" onPress={() => navigation.goBack()} /></Screen>;
  return <Screen><AppHeader eyebrow="CALENDAR" title="Import appointments" subtitle="Preview your CSV before anything is added" /><SecondaryButton fullWidth label="Choose appointment CSV" onPress={() => void chooseFile()} />{fileName ? <Text style={styles.file}>Previewing {fileName}</Text> : null}<Text style={styles.hint}>Columns: customer name, phone, email, service, start time, end time, price, notes. Use ISO dates such as 2026-09-01T09:00:00+04:00.</Text><TextInput accessibilityLabel="Appointment CSV" multiline value={text} onChangeText={setText} placeholder="customer name,phone,email,service,start,end,price,notes" placeholderTextColor={colors.tabInactive} style={styles.input} /><Text style={styles.hint}>{parsed.rows.length} ready · {parsed.skippedLines} invalid rows skipped. Imported history never sends customer confirmations.</Text>{error ? <Text accessibilityRole="alert" style={styles.error}>{error}</Text> : null}<PrimaryButton fullWidth disabled={!parsed.rows.length || importing} label={importing ? 'Importing…' : `Import ${parsed.rows.length || ''} appointments`} onPress={() => void submit()} /><SecondaryButton fullWidth disabled={importing} label="Cancel" onPress={() => navigation.goBack()} /></Screen>;
}
const styles = StyleSheet.create({ input: { minHeight: 190, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, borderRadius: radius.md, padding: spacing.md, ...typography.body, color: colors.text, textAlignVertical: 'top' }, hint: { ...typography.caption, color: colors.textSecondary }, file: { ...typography.caption, color: colors.primary }, error: { ...typography.caption, color: colors.negative }, summary: { gap: spacing.sm }, result: { ...typography.body, color: colors.text } });
