import { useNavigation, useRoute, RouteProp } from '@react-navigation/native';
import { NativeStackNavigationProp } from '@react-navigation/native-stack';
import { useEffect, useMemo, useState } from 'react';
import { Alert, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { AppointmentDto, AppointmentStatus, CustomerDto, ServiceOfferingDto, TeamMemberDto } from '../apiTypes';
import { AppHeader, LoadingState, PrimaryButton, Screen, SecondaryButton } from '../components/ui';
import { combineLocalDateTime, localDateKey, localTime } from '../domain/calendar';
import { ApiError } from '../services/api';
import { appointmentsApi, customersApi, servicesApi, teamApi } from '../services/endpoints';
import { useAuth } from '../state/AuthContext';
import { colors, radius, spacing, typography } from '../theme';
import { RootStackParamList } from '../types';

export function AppointmentEditorScreen() {
  const navigation = useNavigation<NativeStackNavigationProp<RootStackParamList>>(); const route = useRoute<RouteProp<RootStackParamList, 'AppointmentEditor'>>(); const { business } = useAuth(); const id = route.params?.appointmentId;
  const initialStart = useMemo(() => { const value = new Date(); value.setMinutes(Math.ceil(value.getMinutes() / 30) * 30, 0, 0); if (route.params?.date) { const [year, month, day] = route.params.date.split('-').map(Number); value.setFullYear(year!, month! - 1, day); } return value; }, [route.params?.date]);
  const initialEnd = useMemo(() => new Date(initialStart.getTime() + 60 * 60_000), [initialStart]);
  const [appointment, setAppointment] = useState<AppointmentDto | null>(null); const [customers, setCustomers] = useState<CustomerDto[]>([]); const [members, setMembers] = useState<TeamMemberDto[]>([]); const [offerings, setOfferings] = useState<ServiceOfferingDto[]>([]); const [customerId, setCustomerId] = useState(''); const [memberId, setMemberId] = useState(''); const [serviceOfferingId, setServiceOfferingId] = useState(''); const [service, setService] = useState(business?.defaultServices?.[0] ?? ''); const [date, setDate] = useState(localDateKey(initialStart)); const [startTime, setStartTime] = useState(localTime(initialStart)); const [endTime, setEndTime] = useState(localTime(initialEnd)); const [price, setPrice] = useState(''); const [notes, setNotes] = useState(''); const [reminder, setReminder] = useState('60'); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null);
  const [paid, setPaid] = useState('0');
  useEffect(() => { void Promise.all([customersApi.list('', 1, 100), teamApi.listMembers(), servicesApi.list(true), id ? appointmentsApi.get(id) : Promise.resolve(null)]).then(([customerPage, team, catalog, existing]) => { setCustomers(customerPage.items); setMembers(team.filter(item => item.status === 'ACTIVE')); setOfferings(catalog); if (existing) { setAppointment(existing); setCustomerId(existing.customerId ?? ''); setMemberId(existing.assignedMemberId ?? ''); setServiceOfferingId(existing.serviceOfferingId ?? ''); setService(existing.serviceName); const start = new Date(existing.startsAt); const end = new Date(existing.endsAt); setDate(localDateKey(start)); setStartTime(localTime(start)); setEndTime(localTime(end)); setPrice(existing.price == null ? '' : String(existing.price)); setNotes(existing.notes ?? ''); setReminder(existing.reminderMinutes == null ? '' : String(existing.reminderMinutes)); } else if (catalog[0]) { setServiceOfferingId(catalog[0].id); setService(catalog[0].name); setPrice(catalog[0].price == null ? '' : String(catalog[0].price)); setEndTime(localTime(new Date(initialStart.getTime() + catalog[0].durationMinutes * 60_000))); } }).catch(caught => setError(caught instanceof Error ? caught.message : 'Unable to load appointment.')).finally(() => setLoading(false)); }, [id, initialStart]);
  useEffect(() => { if (appointment) setPaid(String(appointment.paidAmount ?? 0)); }, [appointment]);
  const selectService = (offering: ServiceOfferingDto) => { setServiceOfferingId(offering.id); setService(offering.name); setPrice(offering.price == null ? '' : String(offering.price)); const start = combineLocalDateTime(date, startTime); if (start) setEndTime(localTime(new Date(new Date(start).getTime() + offering.durationMinutes * 60_000))); if (memberId && offering.assignments.length && !offering.assignments.some(item => item.businessMemberId === memberId)) setMemberId(''); };
  const eligibleMembers = useMemo(() => { const selected = offerings.find(item => item.id === serviceOfferingId); if (!selected?.assignments.length) return members; const ids = new Set(selected.assignments.map(item => item.businessMemberId)); return members.filter(item => ids.has(item.id)); }, [members, offerings, serviceOfferingId]);
  const save = async () => { if (saving) return; const startsAt = combineLocalDateTime(date, startTime); const endsAt = combineLocalDateTime(date, endTime); if (!startsAt || !endsAt || new Date(endsAt) <= new Date(startsAt)) { setError('Enter a valid date and an end time after the start time.'); return; } setSaving(true); setError(null); const body = { customerId: customerId || undefined, assignedMemberId: memberId || undefined, serviceOfferingId: serviceOfferingId || undefined, serviceName: service.trim(), startsAt, endsAt, price: price ? Number(price) : undefined, notes: notes.trim() || undefined, reminderMinutes: reminder ? Number(reminder) : null }; try { if (id) await appointmentsApi.patch(id, body); else await appointmentsApi.create(body); navigation.goBack(); } catch (caught) { setError(caught instanceof ApiError ? caught.message : 'Unable to save appointment.'); } finally { setSaving(false); } };
  const transition = async (status: AppointmentStatus) => { if (!id || saving) return; setSaving(true); setError(null); try { const next = await appointmentsApi.transition(id, status); setAppointment(next); if (status !== 'CONFIRMED') navigation.goBack(); } catch (caught) { setError(caught instanceof ApiError ? caught.message : 'Unable to update appointment.'); } finally { setSaving(false); } };
  const sendConfirmation = async () => { if (!id || saving) return; setSaving(true); setError(null); try { setAppointment(await appointmentsApi.sendConfirmation(id)); Alert.alert('Confirmation sent', 'The customer confirmation was accepted for delivery.'); } catch (caught) { setError(caught instanceof ApiError ? caught.message : 'Unable to send confirmation.'); } finally { setSaving(false); } };
  const savePayment = async () => { if (!id || saving) return; setSaving(true); setError(null); try { setAppointment(await appointmentsApi.updatePayment(id, Number(paid))); Alert.alert('Payment updated', 'The collected amount is now reflected in revenue reporting.'); } catch (caught) { setError(caught instanceof ApiError ? caught.message : 'Unable to update payment.'); } finally { setSaving(false); } };
  if (loading) return <Screen><LoadingState label="Loading appointment…" /></Screen>;
  const closed = appointment ? ['COMPLETED', 'CANCELED', 'NO_SHOW'].includes(appointment.status) : false;
  return <Screen><AppHeader eyebrow={id ? appointment?.status : 'NEW APPOINTMENT'} title={id ? 'Appointment details' : 'Add appointment'} subtitle="Schedule real work and keep the customer journey connected" />
    <ChoiceSection label="Customer" empty="Walk-in / no customer" items={customers.map(item => ({ id: item.id, label: item.name }))} value={customerId} onChange={setCustomerId} disabled={closed} />
    <Text style={styles.label}>Service</Text><View style={styles.choices}>{offerings.map(item => <Choice key={item.id} label={`${item.name} · ${item.durationMinutes} min`} active={serviceOfferingId === item.id} onPress={() => selectService(item)} disabled={closed} />)}</View>{!offerings.length ? <Field label="Service name" value={service} onChangeText={setService} editable={!closed} /> : null}
    <ChoiceSection label="Team member" empty="Unassigned" items={eligibleMembers.map(item => ({ id: item.id, label: item.name }))} value={memberId} onChange={setMemberId} disabled={closed} />
    <Field label="Date (YYYY-MM-DD)" value={date} onChangeText={setDate} editable={!closed} /><View style={styles.row}><View style={styles.flex}><Field label="Start (HH:MM)" value={startTime} onChangeText={setStartTime} editable={!closed} /></View><View style={styles.flex}><Field label="End (HH:MM)" value={endTime} onChangeText={setEndTime} editable={!closed} /></View></View>
    <View style={styles.row}><View style={styles.flex}><Field label="Price" value={price} onChangeText={setPrice} keyboardType="decimal-pad" editable={!closed} /></View><View style={styles.flex}><Field label="Remind me before (minutes)" value={reminder} onChangeText={setReminder} keyboardType="number-pad" editable={!closed} /></View></View><Field label="Notes" value={notes} onChangeText={setNotes} multiline editable={!closed} />
    {appointment ? <View><Text style={styles.label}>Payment · {appointment.paymentStatus === 'partially_paid' ? 'Partially paid' : appointment.paymentStatus === 'paid' ? 'Paid' : 'Unpaid'}{appointment.depositAmount ? ` · Deposit ${appointment.depositAmount}` : ''}</Text><View style={styles.row}><View style={styles.flex}><Field label="Amount collected" value={paid} onChangeText={setPaid} keyboardType="decimal-pad" /></View><View style={styles.flex}><SecondaryButton fullWidth disabled={saving || Number(paid) < 0} label="Update payment" onPress={() => void savePayment()} /></View></View></View> : null}
    {error ? <Text accessibilityRole="alert" style={styles.error}>{error}</Text> : null}{!closed ? <PrimaryButton fullWidth disabled={saving || !service.trim()} label={saving ? 'Saving…' : id ? 'Save appointment' : 'Create appointment'} onPress={() => void save()} /> : null}
    {appointment?.customerId && !appointment.confirmationSentAt && !closed ? <SecondaryButton fullWidth disabled={saving} label="Send customer confirmation" onPress={() => void sendConfirmation()} /> : null}{appointment?.confirmationSentAt ? <Text style={styles.label}>Customer confirmation sent</Text> : null}
    {appointment?.status === 'SCHEDULED' ? <SecondaryButton fullWidth disabled={saving} label="Confirm appointment" onPress={() => void transition('CONFIRMED')} /> : null}{appointment?.status === 'CONFIRMED' ? <PrimaryButton fullWidth disabled={saving} label="Mark completed" onPress={() => void transition('COMPLETED')} /> : null}{appointment && !closed ? <View style={styles.row}><View style={styles.flex}><SecondaryButton fullWidth disabled={saving} label="No show" onPress={() => void transition('NO_SHOW')} /></View><View style={styles.flex}><SecondaryButton fullWidth disabled={saving} label="Cancel" onPress={() => Alert.alert('Cancel appointment?', 'The appointment will remain in history.', [{ text: 'Keep', style: 'cancel' }, { text: 'Cancel appointment', style: 'destructive', onPress: () => void transition('CANCELED') }])} /></View></View> : null}
  </Screen>;
}
function ChoiceSection({ label, empty, items, value, onChange, disabled }: { label: string; empty: string; items: { id: string; label: string }[]; value: string; onChange: (id: string) => void; disabled: boolean }) { return <View><Text style={styles.label}>{label}</Text><View style={styles.choices}><Choice label={empty} active={!value} onPress={() => onChange('')} disabled={disabled} />{items.map(item => <Choice key={item.id} label={item.label} active={value === item.id} onPress={() => onChange(item.id)} disabled={disabled} />)}</View></View>; }
function Choice({ label, active, onPress, disabled }: { label: string; active: boolean; onPress: () => void; disabled: boolean }) { return <Pressable accessibilityRole="button" accessibilityState={{ selected: active, disabled }} disabled={disabled} onPress={onPress} style={[styles.choice, active && styles.choiceActive]}><Text style={[styles.choiceText, active && styles.choiceTextActive]}>{label}</Text></Pressable>; }
function Field({ label, multiline, ...props }: { label: string; value: string; onChangeText: (value: string) => void; multiline?: boolean; keyboardType?: 'decimal-pad' | 'number-pad'; editable?: boolean }) { return <View><Text style={styles.label}>{label}</Text><TextInput {...props} multiline={multiline} placeholderTextColor={colors.textSecondary} style={[styles.input, multiline && styles.multiline, props.editable === false && styles.disabled]} /></View>; }
const styles = StyleSheet.create({ label: { ...typography.caption, color: colors.text, marginBottom: spacing.xs }, choices: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.xs }, choice: { minHeight: 40, justifyContent: 'center', paddingHorizontal: spacing.md, borderRadius: radius.round, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border }, choiceActive: { borderColor: colors.primary, backgroundColor: colors.primarySoft }, choiceText: { ...typography.caption, color: colors.textSecondary }, choiceTextActive: { color: colors.primary }, input: { minHeight: 48, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, borderRadius: radius.md, paddingHorizontal: spacing.md, ...typography.body, color: colors.text }, multiline: { minHeight: 90, paddingTop: spacing.sm, textAlignVertical: 'top' }, disabled: { opacity: .6 }, row: { flexDirection: 'row', gap: spacing.sm }, flex: { flex: 1 }, error: { ...typography.caption, color: colors.negative } });
