import { Ionicons } from '@expo/vector-icons';
import { NativeStackScreenProps } from '@react-navigation/native-stack';
import { useEffect } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { AppHeader, EmptyState, ErrorState, LoadingState, Screen, SectionHeader } from '../components/ui';
import { useAppState } from '../state/AppContext';
import { usePreferences } from '../state/PreferencesContext';
import { colors, radius, spacing, typography } from '../theme';
import { RootStackParamList } from '../types';
import { formatDateTime, titleCase } from '../utils/format';

type Props = NativeStackScreenProps<RootStackParamList, 'AttentionCenter'>;
export function AttentionCenterScreen({ navigation }: Props) {
  const { dashboard, leads, reviews, reminders, state, loadDashboard, loadLeads, loadReviews, loadReminders } = useAppState(); const { attention } = usePreferences(); useEffect(() => { void Promise.all([loadDashboard(), loadLeads(), loadReviews(), loadReminders()]); }, [loadDashboard, loadLeads, loadReminders, loadReviews]); const newLeads = leads.filter(item => item.status === 'new'); const pendingReviews = reviews.filter(item => item.status === 'pending'); const due = reminders.filter(item => item.status === 'due' && new Date(item.dueDate) <= new Date()); const loading = !state.dashboard.loaded && (state.dashboard.loading || state.leads.loading || state.reviews.loading || state.reminders.loading); const error = state.dashboard.error ?? state.leads.error ?? state.reviews.error ?? state.reminders.error;
  if (loading) return <Screen><LoadingState label="Loading your Attention Center…" /></Screen>; if (error && !dashboard) return <Screen><ErrorState message={error} onRetry={() => void Promise.all([loadDashboard(), loadLeads(), loadReviews(), loadReminders()])} /></Screen>;
  const hasItems = (attention.missedCalls && newLeads.length > 0) || (attention.comebacks && due.length > 0) || (attention.reviews && pendingReviews.length > 0) || (attention.businessActivity && Boolean(dashboard?.recentActivity.length));
  return <Screen><AppHeader eyebrow="WHAT NEEDS ACTION" title="Attention Center" subtitle="Your customer recovery queue" />{!hasItems ? <EmptyState title="You’re caught up" message="New recovery actions will appear here." /> : <View style={styles.queue}>{attention.missedCalls && newLeads.length ? <AttentionItem icon="call-outline" tone="primary" title={`${newLeads.length} missed call${newLeads.length === 1 ? '' : 's'}`} context={newLeads[0].customer?.name ?? 'Customer follow-up'} reason="Waiting for a response" time={formatDateTime(newLeads[0].missedCallTime)} action="Follow up" onPress={() => navigation.navigate('LeadDetail', { leadId: newLeads[0].id })} /> : null}{attention.comebacks && due.length ? <AttentionItem icon="refresh-outline" tone="attention" title={`${due.length} customer${due.length === 1 ? '' : 's'} due back`} context={due[0].customer?.name ?? 'Comeback reminder'} reason="Return reminder is due" time={formatDateTime(due[0].dueDate)} action="Bring back" onPress={() => navigation.navigate('Comeback')} /> : null}{attention.reviews && pendingReviews.length ? <AttentionItem icon="star-outline" tone="success" title={`${pendingReviews.length} review request${pendingReviews.length === 1 ? '' : 's'}`} context={pendingReviews[0].customer?.name ?? 'Customer review'} reason={pendingReviews[0].message ? 'Message prepared' : 'Message needs preparation'} time={formatDateTime(pendingReviews[0].createdAt)} action="Request review" onPress={() => navigation.navigate('ReviewDetail', { reviewId: pendingReviews[0].id })} /> : null}</View>}{attention.businessActivity && dashboard?.recentActivity.length ? <View><SectionHeader title="Important activity" />{dashboard.recentActivity.slice(0,8).map(item => <View key={item.id} style={styles.activity}><View style={styles.activityDot} /><View style={styles.copy}><Text style={styles.activityTitle}>{titleCase(item.eventType)}</Text><Text style={styles.meta}>{titleCase(item.entityType)} · {formatDateTime(item.createdAt)}</Text></View></View>)}</View> : null}</Screen>;
}
function AttentionItem({ icon, tone, title, context, reason, time, action, onPress }: { icon: keyof typeof Ionicons.glyphMap; tone: 'primary'|'attention'|'success'; title: string; context: string; reason: string; time: string; action: string; onPress: () => void }) { const color = tone === 'primary' ? colors.primary : tone === 'attention' ? colors.attention : colors.success; return <Pressable onPress={onPress} style={({ pressed }) => [styles.item, { borderLeftColor: color }, pressed && styles.pressed]}><View style={styles.itemTop}><View style={styles.icon}><Ionicons name={icon} size={22} color={color} /></View><View style={styles.copy}><Text style={styles.itemTitle}>{title}</Text><Text style={styles.context}>{context}</Text></View><Ionicons name="chevron-forward" size={20} color={colors.textSecondary} /></View><View style={styles.reason}><Text style={styles.meta}>{reason}</Text><Text style={styles.time}>{time}</Text></View><Text style={[styles.action, { color }]}>{action}</Text></Pressable>; }
const styles = StyleSheet.create({ queue: { gap: spacing.sm }, item: { minHeight: 150, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, borderLeftWidth: 4, borderRadius: radius.md, padding: spacing.md, gap: spacing.sm }, pressed: { opacity: .72 }, itemTop: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm }, icon: { width: 42, height: 42, borderRadius: 21, backgroundColor: colors.background, alignItems: 'center', justifyContent: 'center' }, copy: { flex: 1 }, itemTitle: { ...typography.subheading, color: colors.text }, context: { ...typography.caption, color: colors.textSecondary, marginTop: 2 }, reason: { flexDirection: 'row', justifyContent: 'space-between', gap: spacing.sm }, meta: { ...typography.caption, color: colors.textSecondary }, time: { ...typography.caption, color: colors.textSecondary, textAlign: 'right' }, action: { ...typography.bodyStrong }, activity: { minHeight: 58, flexDirection: 'row', alignItems: 'center', gap: spacing.sm, borderBottomWidth: 1, borderBottomColor: colors.divider }, activityDot: { width: 8, height: 8, borderRadius: 4, backgroundColor: colors.success }, activityTitle: { ...typography.bodyStrong, color: colors.text } });
