import { Ionicons } from '@expo/vector-icons';
import { NativeStackScreenProps } from '@react-navigation/native-stack';
import { KeyboardAvoidingView, Platform, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { AuthForm } from '../components/AuthForm';
import { colors, radius, spacing, typography } from '../theme';
import { RootStackParamList } from '../types';

export function AuthScreen({ navigation, route }: NativeStackScreenProps<RootStackParamList, 'Login'>) {
  return <SafeAreaView style={styles.safe}><KeyboardAvoidingView behavior={Platform.OS === 'ios' ? 'padding' : undefined} style={styles.keyboard}><ScrollView contentContainerStyle={styles.container} keyboardDismissMode={Platform.OS === 'ios' ? 'interactive' : 'on-drag'} keyboardShouldPersistTaps="handled" showsVerticalScrollIndicator={false}><View style={styles.topBar}><Pressable accessibilityLabel="Back to welcome" accessibilityRole="button" hitSlop={8} onPress={() => navigation.goBack()} style={({ pressed }) => [styles.back, pressed && styles.backPressed]}><Ionicons name="chevron-back" size={24} color={colors.text} /></Pressable><View style={styles.brandRow}><View style={styles.mark}><Text style={styles.markText}>C</Text></View><Text style={styles.brand}>CHAKUSA</Text></View><View style={styles.back} /></View><AuthForm defaultMode={route.params?.mode ?? 'login'} onForgotPassword={() => navigation.navigate('ForgotPassword')} /></ScrollView></KeyboardAvoidingView></SafeAreaView>;
}
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: colors.surface }, keyboard: { flex: 1 }, container: { flexGrow: 1, width: '100%', maxWidth: 620, alignSelf: 'center', paddingHorizontal: spacing.lg, paddingTop: spacing.sm, paddingBottom: spacing.lg, gap: spacing.xl }, topBar: { minHeight: 44, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, back: { width: 44, height: 44, borderRadius: radius.round, alignItems: 'center', justifyContent: 'center' }, backPressed: { opacity: 0.55 }, brandRow: { flexDirection: 'row', alignItems: 'center', gap: spacing.xs }, mark: { width: 30, height: 30, borderRadius: radius.md, backgroundColor: colors.primary, alignItems: 'center', justifyContent: 'center' }, markText: { fontSize: 17, fontWeight: '800', color: colors.surface }, brand: { ...typography.caption, letterSpacing: 1.2, color: colors.text } });
