import { useCallback, useEffect, useState } from 'react';
import { Alert, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { TeamMemberDto } from '../apiTypes';
import { AppHeader, EmptyState, LoadingState, PrimaryButton, Screen, SecondaryButton } from '../components/ui';
import { combineLocalDateTime, localDateKey } from '../domain/calendar';
import { ApiError } from '../services/api';
import { availabilityApi, BookingBlockDto, teamApi } from '../services/endpoints';
import { colors, radius, spacing, typography } from '../theme';

export function AvailabilitySettingsScreen() {
  const [blocks, setBlocks] = useState<BookingBlockDto[]>([]); const [members, setMembers] = useState<TeamMemberDto[]>([]); const [loaded, setLoaded] = useState(false); const [creating, setCreating] = useState(false); const [date, setDate] = useState(localDateKey(new Date())); const [start, setStart] = useState('09:00'); const [end, setEnd] = useState('10:00'); const [memberId, setMemberId] = useState(''); const [reason, setReason] = useState(''); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null);
  const load = useCallback(async () => { const from = new Date(); from.setHours(0, 0, 0, 0); const to = new Date(from); to.setDate(to.getDate() + 120); try { const [items, team] = await Promise.all([availabilityApi.blocks(from.toISOString(), to.toISOString()), teamApi.listMembers()]); setBlocks(items); setMembers(team.filter(item => item.status === 'ACTIVE')); setError(null); } catch { setError('Could not load blocked time.'); } finally { setLoaded(true); } }, []);
  useEffect(() => { void load(); }, [load]);
  const create = async () => { const startsAt = combineLocalDateTime(date, start); const endsAt = combineLocalDateTime(date, end); if (!startsAt || !endsAt || new Date(endsAt) <= new Date(startsAt)) { setError('Enter a valid date and end time after the start.'); return; } setSaving(true); setError(null); try { await availabilityApi.createBlock({ assignedMemberId: memberId || null, startsAt, endsAt, reason: reason.trim() || null }); setCreating(false); setReason(''); await load(); } catch (caught) { setError(caught instanceof ApiError ? caught.message : 'Could not block this time.'); } finally { setSaving(false); } };
  const remove = (block: BookingBlockDto) => Alert.alert('Remove blocked time?', 'This time will become available for booking again.', [{ text: 'Keep', style: 'cancel' }, { text: 'Remove', style: 'destructive', onPress: () => void availabilityApi.deleteBlock(block.id).then(load).catch(() => setError('Could not remove blocked time.')) }]);
  return <Screen><AppHeader eyebrow="SCHEDULE" title="Booking availability" subtitle="Set business hours in your profile, then block holidays, leave, or unavailable time here." />
    {!loaded ? <LoadingState label="Loading availability…" /> : blocks.length ? <View style={styles.list}>{blocks.map(block => <View key={block.id} style={styles.card}><View style={styles.copy}><Text style={styles.title}>{block.reason ?? 'Unavailable'}</Text><Text style={styles.meta}>{new Date(block.startsAt).toLocaleString()} – {new Date(block.endsAt).toLocaleTimeString(undefined, { hour: 'numeric', minute: '2-digit' })}</Text><Text style={styles.meta}>{block.assignedMemberId ? members.find(item => item.id === block.assignedMemberId)?.name ?? 'Team member' : 'Whole business'}</Text></View><SecondaryButton compact label="Remove" onPress={() => remove(block)} /></View>)}</View> : <EmptyState icon="calendar-outline" title="No blocked time" message="Your working hours are available unless an appointment already occupies a slot." />}
    {creating ? <View style={styles.form}><Text style={styles.heading}>Block time</Text><Field label="Date (YYYY-MM-DD)" value={date} onChange={setDate} /><View style={styles.row}><View style={styles.flex}><Field label="Start" value={start} onChange={setStart} /></View><View style={styles.flex}><Field label="End" value={end} onChange={setEnd} /></View></View><Text style={styles.label}>Applies to</Text><View style={styles.choices}><Choice label="Whole business" active={!memberId} onPress={() => setMemberId('')} />{members.map(member => <Choice key={member.id} label={member.name} active={memberId === member.id} onPress={() => setMemberId(member.id)} />)}</View><Field label="Reason (optional)" value={reason} onChange={setReason} />{error ? <Text accessibilityRole="alert" style={styles.error}>{error}</Text> : null}<PrimaryButton fullWidth disabled={saving} label={saving ? 'Saving…' : 'Block time'} onPress={() => void create()} /><SecondaryButton fullWidth disabled={saving} label="Cancel" onPress={() => setCreating(false)} /></View> : <PrimaryButton fullWidth icon="add" label="Block unavailable time" onPress={() => setCreating(true)} />}
  </Screen>;
}
function Field({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { return <View><Text style={styles.label}>{label}</Text><TextInput value={value} onChangeText={onChange} style={styles.input} /></View>; }
function Choice({ label, active, onPress }: { label: string; active: boolean; onPress: () => void }) { return <Pressable accessibilityRole="button" accessibilityState={{ selected: active }} onPress={onPress} style={[styles.choice, active && styles.choiceActive]}><Text style={[styles.choiceText, active && styles.choiceTextActive]}>{label}</Text></Pressable>; }
const styles = StyleSheet.create({ list: { gap: spacing.sm }, card: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm, padding: spacing.md, borderRadius: radius.md, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface }, copy: { flex: 1 }, title: { ...typography.bodyStrong, color: colors.text }, meta: { ...typography.caption, color: colors.textSecondary }, form: { gap: spacing.sm, padding: spacing.md, borderRadius: radius.lg, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface }, heading: { ...typography.title, color: colors.text }, label: { ...typography.caption, color: colors.text, marginBottom: spacing.xs }, input: { minHeight: 48, paddingHorizontal: spacing.md, borderRadius: radius.md, borderWidth: 1, borderColor: colors.border, color: colors.text }, row: { flexDirection: 'row', gap: spacing.sm }, flex: { flex: 1 }, choices: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.xs }, choice: { minHeight: 40, justifyContent: 'center', paddingHorizontal: spacing.sm, borderRadius: radius.round, borderWidth: 1, borderColor: colors.border }, choiceActive: { borderColor: colors.primary, backgroundColor: colors.primarySoft }, choiceText: { ...typography.caption, color: colors.textSecondary }, choiceTextActive: { color: colors.primary }, error: { ...typography.caption, color: colors.negative } });
