import * as Clipboard from 'expo-clipboard';
import { useState } from 'react';
import { Alert, Pressable, Share, StyleSheet, Text, TextInput, View } from 'react-native';
import { MessageTone } from '../apiTypes';
import { AppHeader, PrimaryButton, Screen } from '../components/ui';
import { CountryPhoneInput } from '../components/CountryPhoneInput';
import { BusinessHoursEditor } from '../components/BusinessHoursEditor';
import { ServiceListEditor } from '../components/ServiceListEditor';
import { QrCode } from '../components/QrCode';
import { publicBusinessProfileUrl } from '../domain/publicBusinessProfile';
import { parseWeeklyHours, serializeWeeklyHours } from '../domain/businessSetup';
import { ApiError } from '../services/api';
import { businessApi } from '../services/endpoints';
import { useAuth } from '../state/AuthContext';
import { colors, radius, spacing, typography } from '../theme';
import { titleCase } from '../utils/format';

export function BusinessSettingsScreen() {
  const { business, refreshBusiness } = useAuth(); const [name, setName] = useState(business?.name ?? ''); const [industry, setIndustry] = useState(business?.industry ?? ''); const [country, setCountry] = useState(business?.country ?? 'ZW'); const [timezone, setTimezone] = useState(business?.timezone ?? Intl.DateTimeFormat().resolvedOptions().timeZone); const [currency, setCurrency] = useState(business?.currency ?? 'USD'); const [phone, setPhone] = useState(business?.phone ?? ''); const [description, setDescription] = useState(business?.description ?? ''); const [reviewLink, setReviewLink] = useState(business?.googleReviewLink ?? ''); const [services, setServices] = useState<string[]>(business?.defaultServices ?? []); const [hours, setHours] = useState(() => parseWeeklyHours(business?.workingHours)); const [days, setDays] = useState(String(business?.reminderDays ?? 42)); const [tone, setTone] = useState<MessageTone>(business?.preferredTone ?? 'friendly'); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null); const [showQr, setShowQr] = useState(false);
  const save = async () => { if (saving) return; setSaving(true); setError(null); try { await businessApi.patch({ name: name.trim(), industry: industry.trim().toLowerCase() || undefined, country, timezone: timezone.trim(), currency: currency.trim().toUpperCase(), phone: phone.trim() || undefined, description: description.trim(), googleReviewLink: reviewLink.trim() || undefined, defaultServices: services, workingHours: serializeWeeklyHours(hours), reminderDays: Number(days), preferredTone: tone }); await refreshBusiness(); Alert.alert('Settings saved', 'Your business setup is ready across Chakusa.'); } catch (caught) { setError(caught instanceof ApiError ? caught.message : 'Unable to save business settings.'); } finally { setSaving(false); } };
  const profileUrl = business?.publicSlug ? publicBusinessProfileUrl(business.publicSlug) : null;
  const copyProfileUrl = async () => { if (!profileUrl) return; await Clipboard.setStringAsync(profileUrl); Alert.alert('Copied', 'Your business page link was copied.'); };
  const shareProfileUrl = async () => { if (!profileUrl) return; try { await Share.share({ message: `Check out ${name || business?.name || 'my business'} on Chakusa: ${profileUrl}` }); } catch { /* user dismissed the share sheet */ } };
  return <Screen><AppHeader eyebrow="BUSINESS" title="Business profile" subtitle="Settings used across customer recovery" />
    {profileUrl ? <View style={styles.shareCard}>
      <Text style={styles.shareLabel}>Your public business page</Text>
      <Text numberOfLines={1} style={styles.shareUrl}>{profileUrl}</Text>
      <View style={styles.shareActions}>
        <Pressable accessibilityRole="button" onPress={() => void copyProfileUrl()} style={styles.shareButton}><Text style={styles.shareButtonText}>Copy link</Text></Pressable>
        <Pressable accessibilityRole="button" onPress={() => void shareProfileUrl()} style={[styles.shareButton, styles.shareButtonPrimary]}><Text style={[styles.shareButtonText, styles.shareButtonTextPrimary]}>Share</Text></Pressable>
      </View>
      <Pressable accessibilityRole="button" onPress={() => setShowQr(current => !current)} style={styles.qrToggle}><Text style={styles.qrToggleText}>{showQr ? 'Hide QR code' : 'Show QR code'}</Text></Pressable>
      {showQr ? <View style={styles.qrWrap}><QrCode value={profileUrl} /><Text style={styles.qrHint}>Screenshot this to print on a flyer, storefront window, or receipt.</Text></View> : null}
    </View> : null}
    <Field label="Business name" value={name} onChangeText={setName} /><Field label="Industry" value={industry} onChangeText={setIndustry} /><CountryPhoneInput value={phone} onChange={setPhone} onCountryChange={setCountry} defaultCountryCode={country} label="Business phone" /><View style={{ flexDirection: 'row', gap: spacing.sm }}><View style={{ flex: 1 }}><Field label="Currency" value={currency} onChangeText={setCurrency} /></View><View style={{ flex: 1 }}><Field label="Timezone" value={timezone} onChangeText={setTimezone} /></View></View><Field label="Description (shown on your public page)" value={description} onChangeText={setDescription} multiline /><Field label="Google review link" value={reviewLink} onChangeText={setReviewLink} /><ServiceListEditor value={services} onChange={setServices} /><BusinessHoursEditor value={hours} onChange={setHours} /><Field label="Comeback reminder after (days)" value={days} onChangeText={setDays} /><Text style={styles.label}>Preferred message tone</Text><View style={styles.choices}>{(['friendly','professional','casual'] as const).map(value => <Pressable key={value} onPress={() => setTone(value)} style={[styles.choice, tone === value && styles.choiceActive]}><Text style={[styles.choiceText, tone === value && styles.choiceTextActive]}>{titleCase(value)}</Text></Pressable>)}</View>{error ? <Text accessibilityRole="alert" style={styles.error}>{error}</Text> : null}<PrimaryButton disabled={saving || !name.trim() || !services.length} fullWidth label={saving ? 'Saving…' : 'Save business setup'} onPress={() => void save()} /></Screen>;
}
function Field({ label, multiline, ...props }: { label: string; value: string; onChangeText: (value: string) => void; multiline?: boolean }) { return <View><Text style={styles.label}>{label}</Text><TextInput {...props} multiline={multiline} style={[styles.input, multiline && styles.inputMultiline]} /></View>; }
const styles = StyleSheet.create({ shareCard: { backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, borderRadius: radius.md, padding: spacing.md, gap: spacing.xs, marginBottom: spacing.md }, shareLabel: { ...typography.caption, color: colors.text }, shareUrl: { ...typography.body, color: colors.primary }, shareActions: { flexDirection: 'row', gap: spacing.sm, marginTop: spacing.xs }, shareButton: { minHeight: 40, flex: 1, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: colors.border, borderRadius: radius.round }, shareButtonPrimary: { backgroundColor: colors.primary, borderColor: colors.primary }, shareButtonText: { ...typography.caption, color: colors.text, fontWeight: '700' }, shareButtonTextPrimary: { color: colors.surface }, qrToggle: { minHeight: 36, justifyContent: 'center', marginTop: spacing.xs }, qrToggleText: { ...typography.caption, color: colors.primary, fontWeight: '700' }, qrWrap: { alignItems: 'center', gap: spacing.xs, paddingVertical: spacing.sm }, qrHint: { ...typography.caption, color: colors.textSecondary, textAlign: 'center' }, label: { ...typography.caption, color: colors.text, marginBottom: spacing.xs }, input: { minHeight: 48, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, borderRadius: radius.md, paddingHorizontal: spacing.md, ...typography.body, color: colors.text }, inputMultiline: { minHeight: 88, paddingTop: spacing.sm, textAlignVertical: 'top' }, choices: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.xs }, choice: { minHeight: 42, justifyContent: 'center', paddingHorizontal: spacing.md, borderRadius: radius.round, borderWidth: 1, borderColor: colors.border }, choiceActive: { borderColor: colors.primary }, choiceText: { ...typography.caption, color: colors.textSecondary }, choiceTextActive: { color: colors.primary, fontWeight: '700' }, error: { ...typography.caption, color: colors.negative } });
