import * as Clipboard from 'expo-clipboard';
import { useState } from 'react';
import { Alert, Pressable, Share, StyleSheet, Text, TextInput, View } from 'react-native';
import { MessageTone } from '../apiTypes';
import { AppHeader, PrimaryButton, Screen } from '../components/ui';
import { CountryPhoneInput } from '../components/CountryPhoneInput';
import { publicBusinessProfileUrl } from '../domain/publicBusinessProfile';
import { ApiError } from '../services/api';
import { businessApi } from '../services/endpoints';
import { useAuth } from '../state/AuthContext';
import { colors, radius, spacing, typography } from '../theme';
import { titleCase } from '../utils/format';

export function BusinessSettingsScreen() {
  const { business, refreshBusiness } = useAuth(); const [name, setName] = useState(business?.name ?? ''); const [industry, setIndustry] = useState(business?.industry ?? ''); const [country, setCountry] = useState(business?.country ?? 'ZW'); const [phone, setPhone] = useState(business?.phone ?? ''); const [reviewLink, setReviewLink] = useState(business?.googleReviewLink ?? ''); const [services, setServices] = useState((business?.defaultServices ?? []).join(', ')); const [hours, setHours] = useState(typeof business?.workingHours?.summary === 'string' ? business.workingHours.summary : ''); const [days, setDays] = useState(String(business?.reminderDays ?? 42)); const [tone, setTone] = useState<MessageTone>(business?.preferredTone ?? 'friendly'); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null);
  const save = async () => { if (saving) return; setSaving(true); setError(null); try { await businessApi.patch({ name: name.trim(), industry: industry.trim().toLowerCase() || undefined, country, phone: phone.trim() || undefined, googleReviewLink: reviewLink.trim() || undefined, defaultServices: services.split(',').map(item => item.trim()).filter(Boolean), workingHours: { summary: hours.trim() }, reminderDays: Number(days), preferredTone: tone }); await refreshBusiness(); Alert.alert('Settings saved', 'Persisted business settings were reloaded from CHAKUSA.'); } catch (caught) { setError(caught instanceof ApiError ? caught.message : 'Unable to save business settings.'); } finally { setSaving(false); } };
  const profileUrl = business?.publicSlug ? publicBusinessProfileUrl(business.publicSlug) : null;
  const copyProfileUrl = async () => { if (!profileUrl) return; await Clipboard.setStringAsync(profileUrl); Alert.alert('Copied', 'Your business page link was copied.'); };
  const shareProfileUrl = async () => { if (!profileUrl) return; try { await Share.share({ message: `Check out ${name || business?.name || 'my business'} on Chakusa: ${profileUrl}` }); } catch { /* user dismissed the share sheet */ } };
  return <Screen><AppHeader eyebrow="BUSINESS" title="Business profile" subtitle="Settings used across customer recovery" />
    {profileUrl ? <View style={styles.shareCard}>
      <Text style={styles.shareLabel}>Your public business page</Text>
      <Text numberOfLines={1} style={styles.shareUrl}>{profileUrl}</Text>
      <View style={styles.shareActions}>
        <Pressable accessibilityRole="button" onPress={() => void copyProfileUrl()} style={styles.shareButton}><Text style={styles.shareButtonText}>Copy link</Text></Pressable>
        <Pressable accessibilityRole="button" onPress={() => void shareProfileUrl()} style={[styles.shareButton, styles.shareButtonPrimary]}><Text style={[styles.shareButtonText, styles.shareButtonTextPrimary]}>Share</Text></Pressable>
      </View>
    </View> : null}
    <Field label="Business name" value={name} onChangeText={setName} /><Field label="Industry" value={industry} onChangeText={setIndustry} /><CountryPhoneInput value={phone} onChange={setPhone} onCountryChange={setCountry} defaultCountryCode={country} label="Business phone" /><Field label="Google review link" value={reviewLink} onChangeText={setReviewLink} /><Field label="Services (comma separated)" value={services} onChangeText={setServices} /><Field label="Working hours" value={hours} onChangeText={setHours} /><Field label="Reminder timing (days)" value={days} onChangeText={setDays} /><Text style={styles.label}>Preferred tone</Text><View style={styles.choices}>{(['friendly','professional','casual'] as const).map(value => <Pressable key={value} onPress={() => setTone(value)} style={[styles.choice, tone === value && styles.choiceActive]}><Text style={[styles.choiceText, tone === value && styles.choiceTextActive]}>{titleCase(value)}</Text></Pressable>)}</View>{error ? <Text accessibilityRole="alert" style={styles.error}>{error}</Text> : null}<PrimaryButton disabled={saving || !name.trim()} fullWidth label={saving ? 'Saving…' : 'Save settings'} onPress={() => void save()} /></Screen>;
}
function Field({ label, ...props }: { label: string; value: string; onChangeText: (value: string) => void }) { return <View><Text style={styles.label}>{label}</Text><TextInput {...props} style={styles.input} /></View>; }
const styles = StyleSheet.create({ shareCard: { backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, borderRadius: radius.md, padding: spacing.md, gap: spacing.xs, marginBottom: spacing.md }, shareLabel: { ...typography.caption, color: colors.text }, shareUrl: { ...typography.body, color: colors.primary }, shareActions: { flexDirection: 'row', gap: spacing.sm, marginTop: spacing.xs }, shareButton: { minHeight: 40, flex: 1, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: colors.border, borderRadius: radius.round }, shareButtonPrimary: { backgroundColor: colors.primary, borderColor: colors.primary }, shareButtonText: { ...typography.caption, color: colors.text, fontWeight: '700' }, shareButtonTextPrimary: { color: colors.surface }, label: { ...typography.caption, color: colors.text, marginBottom: spacing.xs }, input: { minHeight: 48, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, borderRadius: radius.md, paddingHorizontal: spacing.md, ...typography.body, color: colors.text }, choices: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.xs }, choice: { minHeight: 42, justifyContent: 'center', paddingHorizontal: spacing.md, borderRadius: radius.round, borderWidth: 1, borderColor: colors.border }, choiceActive: { borderColor: colors.primary }, choiceText: { ...typography.caption, color: colors.textSecondary }, choiceTextActive: { color: colors.primary, fontWeight: '700' }, error: { ...typography.caption, color: colors.negative } });
