import * as Clipboard from 'expo-clipboard';
import { useEffect, useState } from 'react';
import { Alert, Linking, Pressable, Share, StyleSheet, Switch, Text, TextInput, View } from 'react-native';
import { MessageTone } from '../apiTypes';
import { AppHeader, PrimaryButton, Screen } from '../components/ui';
import { CountryPhoneInput } from '../components/CountryPhoneInput';
import { BusinessHoursEditor } from '../components/BusinessHoursEditor';
import { QrCode } from '../components/QrCode';
import { publicBusinessProfileUrl } from '../domain/publicBusinessProfile';
import { parseWeeklyHours, serializeWeeklyHours } from '../domain/businessSetup';
import { ApiError } from '../services/api';
import { businessApi, paymentsApi } from '../services/endpoints';
import { useAuth } from '../state/AuthContext';
import { colors, radius, spacing, typography } from '../theme';
import { titleCase } from '../utils/format';

export function BusinessSettingsScreen() {
  const { business, refreshBusiness } = useAuth(); const [name, setName] = useState(business?.name ?? ''); const [industry, setIndustry] = useState(business?.industry ?? ''); const [country, setCountry] = useState(business?.country ?? 'ZW'); const [timezone, setTimezone] = useState(business?.timezone ?? Intl.DateTimeFormat().resolvedOptions().timeZone); const [currency, setCurrency] = useState(business?.currency ?? 'USD'); const [phone, setPhone] = useState(business?.phone ?? ''); const [description, setDescription] = useState(business?.description ?? ''); const [reviewLink, setReviewLink] = useState(business?.googleReviewLink ?? ''); const [hours, setHours] = useState(() => parseWeeklyHours(business?.workingHours)); const [days, setDays] = useState(String(business?.reminderDays ?? 42)); const [minNotice, setMinNotice] = useState(String(business?.bookingMinNoticeMinutes ?? 60)); const [bookingWindow, setBookingWindow] = useState(String(business?.bookingWindowDays ?? 90)); const [slotInterval, setSlotInterval] = useState(String(business?.slotIntervalMinutes ?? 15)); const [cancelNotice, setCancelNotice] = useState(String(business?.cancellationNoticeMinutes ?? 1440)); const [appointmentReminder, setAppointmentReminder] = useState(String(business?.defaultAppointmentReminderMinutes ?? 1440)); const [tone, setTone] = useState<MessageTone>(business?.preferredTone ?? 'friendly'); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null); const [showQr, setShowQr] = useState(false);
  const [messagingConsent, setMessagingConsent] = useState(Boolean(business?.messagingConsentConfirmedAt)); const [paymentReminders, setPaymentReminders] = useState(Boolean(business?.paymentRemindersEnabled)); const [stripeStatus, setStripeStatus] = useState<{ connected: boolean; chargesEnabled: boolean; payoutsEnabled: boolean } | null>(null); const [connectingStripe, setConnectingStripe] = useState(false);
  useEffect(() => { void paymentsApi.connectStatus().then(setStripeStatus).catch(() => setStripeStatus(null)); }, []);
  const save = async () => { if (saving) return; setSaving(true); setError(null); try { await businessApi.patch({ name: name.trim(), industry: industry.trim().toLowerCase() || undefined, country, timezone: timezone.trim(), currency: currency.trim().toUpperCase(), phone: phone.trim() || undefined, description: description.trim(), googleReviewLink: reviewLink.trim() || undefined, workingHours: serializeWeeklyHours(hours), reminderDays: Number(days), bookingMinNoticeMinutes: Number(minNotice), bookingWindowDays: Number(bookingWindow), slotIntervalMinutes: Number(slotInterval), cancellationNoticeMinutes: Number(cancelNotice), defaultAppointmentReminderMinutes: Number(appointmentReminder), preferredTone: tone, messagingConsentConfirmed: messagingConsent, paymentRemindersEnabled: messagingConsent && paymentReminders }); await refreshBusiness(); Alert.alert('Settings saved', 'Your business setup and booking rules are ready across Chakusa.'); } catch (caught) { setError(caught instanceof ApiError ? caught.message : 'Unable to save business settings.'); } finally { setSaving(false); } };
  const connectStripe = async () => { if (connectingStripe) return; setConnectingStripe(true); setError(null); try { const { url } = await paymentsApi.connectLink(); await Linking.openURL(url); } catch (caught) { setError(caught instanceof ApiError ? caught.message : 'Unable to open Stripe setup.'); } finally { setConnectingStripe(false); } };
  const profileUrl = business?.publicSlug ? publicBusinessProfileUrl(business.publicSlug) : null;
  const copyProfileUrl = async () => { if (!profileUrl) return; await Clipboard.setStringAsync(profileUrl); Alert.alert('Copied', 'Your business page link was copied.'); };
  const shareProfileUrl = async () => { if (!profileUrl) return; try { await Share.share({ message: `Check out ${name || business?.name || 'my business'} on Chakusa: ${profileUrl}` }); } catch { /* user dismissed the share sheet */ } };
  return <Screen><AppHeader eyebrow="BUSINESS" title="Business profile" subtitle="Settings used across customer recovery" />
    {profileUrl ? <View style={styles.shareCard}>
      <Text style={styles.shareLabel}>Your public business page</Text>
      <Text numberOfLines={1} style={styles.shareUrl}>{profileUrl}</Text>
      <View style={styles.shareActions}>
        <Pressable accessibilityRole="button" onPress={() => void copyProfileUrl()} style={styles.shareButton}><Text style={styles.shareButtonText}>Copy link</Text></Pressable>
        <Pressable accessibilityRole="button" onPress={() => void shareProfileUrl()} style={[styles.shareButton, styles.shareButtonPrimary]}><Text style={[styles.shareButtonText, styles.shareButtonTextPrimary]}>Share</Text></Pressable>
      </View>
      <Pressable accessibilityRole="button" onPress={() => setShowQr(current => !current)} style={styles.qrToggle}><Text style={styles.qrToggleText}>{showQr ? 'Hide QR code' : 'Show QR code'}</Text></Pressable>
      {showQr ? <View style={styles.qrWrap}><QrCode value={profileUrl} /><Text style={styles.qrHint}>Screenshot this to print on a flyer, storefront window, or receipt.</Text></View> : null}
    </View> : null}
    <Field label="Business name" value={name} onChangeText={setName} /><Field label="Industry" value={industry} onChangeText={setIndustry} /><CountryPhoneInput value={phone} onChange={setPhone} onCountryChange={setCountry} defaultCountryCode={country} label="Business phone" /><View style={{ flexDirection: 'row', gap: spacing.sm }}><View style={{ flex: 1 }}><Field label="Currency" value={currency} onChangeText={setCurrency} /></View><View style={{ flex: 1 }}><Field label="Timezone" value={timezone} onChangeText={setTimezone} /></View></View><Field label="Description (shown on your public page)" value={description} onChangeText={setDescription} multiline /><Field label="Google review link" value={reviewLink} onChangeText={setReviewLink} /><BusinessHoursEditor value={hours} onChange={setHours} />
    <Text style={styles.label}>Online booking rules</Text><View style={styles.choices}><View style={{ flexGrow: 1, width: '46%' }}><Field label="Minimum notice (minutes)" value={minNotice} onChangeText={setMinNotice} /></View><View style={{ flexGrow: 1, width: '46%' }}><Field label="Booking window (days)" value={bookingWindow} onChangeText={setBookingWindow} /></View><View style={{ flexGrow: 1, width: '46%' }}><Field label="Slot interval (minutes)" value={slotInterval} onChangeText={setSlotInterval} /></View><View style={{ flexGrow: 1, width: '46%' }}><Field label="Cancellation notice (minutes)" value={cancelNotice} onChangeText={setCancelNotice} /></View><View style={{ flexGrow: 1, width: '46%' }}><Field label="Appointment reminder (minutes)" value={appointmentReminder} onChangeText={setAppointmentReminder} /></View></View>
    <Text style={styles.label}>Payments and customer messaging</Text><View style={styles.setupCard}><View style={styles.toggleRow}><View style={styles.toggleCopy}><Text style={styles.toggleTitle}>Customer messaging responsibility</Text><Text style={styles.toggleDetail}>I confirm that my business has the permission required to message customers and will honor opt-outs.</Text></View><Switch accessibilityLabel="Confirm customer messaging responsibility" value={messagingConsent} onValueChange={value => { setMessagingConsent(value); if (!value) setPaymentReminders(false); }} /></View><View style={styles.toggleRow}><View style={styles.toggleCopy}><Text style={styles.toggleTitle}>Automatic payment reminders</Text><Text style={styles.toggleDetail}>Send one balance reminder using an existing secure Stripe Checkout link.</Text></View><Switch accessibilityLabel="Automatic payment reminders" disabled={!messagingConsent} value={messagingConsent && paymentReminders} onValueChange={setPaymentReminders} /></View><Text style={styles.toggleTitle}>Stripe payments</Text><Text style={styles.toggleDetail}>{stripeStatus?.chargesEnabled && stripeStatus.payoutsEnabled ? 'Connected and ready to accept payments.' : stripeStatus?.connected ? 'Finish Stripe verification to accept payments.' : 'Connect your business to accept deposits and balances.'}</Text><Pressable accessibilityRole="button" disabled={connectingStripe} onPress={() => void connectStripe()} style={styles.shareButton}><Text style={styles.shareButtonText}>{connectingStripe ? 'Opening Stripe…' : stripeStatus?.connected ? 'Continue Stripe setup' : 'Connect Stripe'}</Text></Pressable></View>
    <Field label="Comeback reminder after (days)" value={days} onChangeText={setDays} /><Text style={styles.label}>Preferred message tone</Text><View style={styles.choices}>{(['friendly','professional','casual'] as const).map(value => <Pressable key={value} onPress={() => setTone(value)} style={[styles.choice, tone === value && styles.choiceActive]}><Text style={[styles.choiceText, tone === value && styles.choiceTextActive]}>{titleCase(value)}</Text></Pressable>)}</View>{error ? <Text accessibilityRole="alert" style={styles.error}>{error}</Text> : null}<PrimaryButton disabled={saving || !name.trim()} fullWidth label={saving ? 'Saving…' : 'Save business setup'} onPress={() => void save()} /></Screen>;
}
function Field({ label, multiline, ...props }: { label: string; value: string; onChangeText: (value: string) => void; multiline?: boolean }) { return <View><Text style={styles.label}>{label}</Text><TextInput {...props} multiline={multiline} style={[styles.input, multiline && styles.inputMultiline]} /></View>; }
const styles = StyleSheet.create({ shareCard: { backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, borderRadius: radius.md, padding: spacing.md, gap: spacing.xs, marginBottom: spacing.md }, shareLabel: { ...typography.caption, color: colors.text }, shareUrl: { ...typography.body, color: colors.primary }, shareActions: { flexDirection: 'row', gap: spacing.sm, marginTop: spacing.xs }, shareButton: { minHeight: 40, flex: 1, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: colors.border, borderRadius: radius.round }, shareButtonPrimary: { backgroundColor: colors.primary, borderColor: colors.primary }, shareButtonText: { ...typography.caption, color: colors.text, fontWeight: '700' }, shareButtonTextPrimary: { color: colors.surface }, qrToggle: { minHeight: 36, justifyContent: 'center', marginTop: spacing.xs }, qrToggleText: { ...typography.caption, color: colors.primary, fontWeight: '700' }, qrWrap: { alignItems: 'center', gap: spacing.xs, paddingVertical: spacing.sm }, qrHint: { ...typography.caption, color: colors.textSecondary, textAlign: 'center' }, label: { ...typography.caption, color: colors.text, marginBottom: spacing.xs }, input: { minHeight: 48, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, borderRadius: radius.md, paddingHorizontal: spacing.md, ...typography.body, color: colors.text }, inputMultiline: { minHeight: 88, paddingTop: spacing.sm, textAlignVertical: 'top' }, choices: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.xs }, choice: { minHeight: 42, justifyContent: 'center', paddingHorizontal: spacing.md, borderRadius: radius.round, borderWidth: 1, borderColor: colors.border }, choiceActive: { borderColor: colors.primary }, choiceText: { ...typography.caption, color: colors.textSecondary }, choiceTextActive: { color: colors.primary, fontWeight: '700' }, setupCard: { padding: spacing.md, gap: spacing.md, borderWidth: 1, borderColor: colors.border, borderRadius: radius.md, backgroundColor: colors.surface }, toggleRow: { flexDirection: 'row', gap: spacing.sm, alignItems: 'center' }, toggleCopy: { flex: 1 }, toggleTitle: { ...typography.bodyStrong, color: colors.text }, toggleDetail: { ...typography.caption, color: colors.textSecondary }, error: { ...typography.caption, color: colors.negative } });
