import { Ionicons } from '@expo/vector-icons';
import { useFocusEffect, useNavigation } from '@react-navigation/native';
import { NativeStackNavigationProp } from '@react-navigation/native-stack';
import { useCallback, useMemo, useState } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { AppointmentDto } from '../apiTypes';
import { AppHeader, EmptyState, ErrorState, IconButton, LoadingState, Screen, StatusBadge } from '../components/ui';
import { endOfDay, localDateKey, startOfDay, weekDates } from '../domain/calendar';
import { appointmentsApi } from '../services/endpoints';
import { colors, radius, shadows, spacing, typography } from '../theme';
import { RootStackParamList } from '../types';
import { formatMoney } from '../utils/format';

export function CalendarScreen() {
  const navigation = useNavigation<NativeStackNavigationProp<RootStackParamList>>(); const [selected, setSelected] = useState(startOfDay(new Date())); const [mode, setMode] = useState<'day'|'week'|'agenda'>('day'); const [items, setItems] = useState<AppointmentDto[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null);
  const week = useMemo(() => weekDates(selected), [selected]);
  const range = useMemo(() => { if (mode === 'day') return { from: startOfDay(selected), to: endOfDay(selected) }; const from = mode === 'week' ? startOfDay(week[0]) : startOfDay(selected); const to = new Date(from); to.setDate(to.getDate() + (mode === 'week' ? 7 : 30)); return { from, to }; }, [mode, selected, week]);
  const grouped = useMemo(() => items.reduce<Record<string, AppointmentDto[]>>((result, item) => { const key = localDateKey(new Date(item.startsAt)); (result[key] ??= []).push(item); return result; }, {}), [items]);
  const load = useCallback(async () => { setLoading(true); setError(null); try { setItems(await appointmentsApi.list(range.from.toISOString(), range.to.toISOString())); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Unable to load appointments.'); } finally { setLoading(false); } }, [range]);
  useFocusEffect(useCallback(() => { void load(); }, [load]));
  return <Screen refreshing={loading && items.length > 0} onRefresh={() => void load()}><AppHeader eyebrow="SCHEDULE" title="Calendar" subtitle={selected.toLocaleDateString(undefined, { weekday: 'long', month: 'long', day: 'numeric' })} right={<View style={{ flexDirection: 'row', gap: spacing.xs }}><IconButton icon="options-outline" label="Booking availability" onPress={() => navigation.navigate('AvailabilitySettings')} /><IconButton icon="add" label="Create appointment" onPress={() => navigation.navigate('AppointmentEditor', { date: localDateKey(selected) })} /></View>} />
    <View accessibilityRole="tablist" style={styles.modes}>{(['day','week','agenda'] as const).map(item => <Pressable key={item} accessibilityRole="tab" accessibilityState={{ selected: mode === item }} onPress={() => setMode(item)} style={[styles.mode, mode === item && styles.modeActive]}><Text style={[styles.modeText, mode === item && styles.activeText]}>{item === 'agenda' ? '30-day agenda' : item[0].toUpperCase() + item.slice(1)}</Text></Pressable>)}</View>
    <View style={styles.week}>{week.map(date => { const active = localDateKey(date) === localDateKey(selected); return <Pressable key={localDateKey(date)} accessibilityRole="button" accessibilityState={{ selected: active }} onPress={() => setSelected(date)} style={[styles.day, active && styles.dayActive]}><Text style={[styles.weekday, active && styles.activeText]}>{date.toLocaleDateString(undefined, { weekday: 'narrow' })}</Text><Text style={[styles.dayNumber, active && styles.activeText]}>{date.getDate()}</Text></Pressable>; })}</View>
    {loading && !items.length ? <LoadingState label="Loading appointments…" /> : error ? <ErrorState message={error} onRetry={() => void load()} /> : items.length ? mode === 'day' ? <View style={styles.list}>{items.map(item => <AppointmentCard key={item.id} item={item} onPress={() => navigation.navigate('AppointmentEditor', { appointmentId: item.id })} />)}</View> : <View style={styles.list}>{Object.entries(grouped).map(([key, dayItems]) => <View key={key} style={styles.dayGroup}><Text style={styles.dateHeading}>{new Date(`${key}T12:00:00`).toLocaleDateString(undefined, { weekday: 'long', month: 'short', day: 'numeric' })}</Text>{dayItems.map(item => <AppointmentCard key={item.id} item={item} onPress={() => navigation.navigate('AppointmentEditor', { appointmentId: item.id })} />)}</View>)}</View> : <EmptyState icon="calendar-outline" title="No appointments" message={`Your ${mode === 'day' ? 'day' : mode === 'week' ? 'week' : 'next 30 days'} is clear. Add an appointment when you are ready.`} />}
  </Screen>;
}
function AppointmentCard({ item, onPress }: { item: AppointmentDto; onPress: () => void }) { const start = new Date(item.startsAt); const end = new Date(item.endsAt); return <Pressable accessibilityRole="button" onPress={onPress} style={({ pressed }) => [styles.card, pressed && styles.pressed]}><View style={styles.time}><Text style={styles.timeText}>{start.toLocaleTimeString(undefined, { hour: 'numeric', minute: '2-digit' })}</Text><Text style={styles.endTime}>{end.toLocaleTimeString(undefined, { hour: 'numeric', minute: '2-digit' })}</Text></View><View style={styles.rail} /><View style={styles.copy}><Text style={styles.service}>{item.serviceName}</Text><Text style={styles.meta}>{item.customer?.name ?? 'Walk-in customer'}{item.assignedMember ? ` · ${item.assignedMember.user.fullName}` : ''}</Text>{item.price != null ? <Text style={styles.price}>{formatMoney(item.price)}</Text> : null}</View><StatusBadge label={item.status === 'NO_SHOW' ? 'No show' : item.status[0] + item.status.slice(1).toLowerCase()} /><Ionicons name="chevron-forward" size={17} color={colors.tabInactive} /></Pressable>; }
const styles = StyleSheet.create({ modes: { flexDirection: 'row', gap: spacing.xs }, mode: { flex: 1, minHeight: 42, alignItems: 'center', justifyContent: 'center', borderRadius: radius.round, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, paddingHorizontal: spacing.xs }, modeActive: { backgroundColor: colors.primary, borderColor: colors.primary }, modeText: { ...typography.caption, color: colors.text, textAlign: 'center' }, week: { flexDirection: 'row', gap: spacing.xxs, backgroundColor: colors.surface, borderRadius: radius.lg, padding: spacing.xs, borderWidth: 1, borderColor: colors.border }, day: { flex: 1, minHeight: 58, borderRadius: radius.md, alignItems: 'center', justifyContent: 'center', gap: 2 }, dayActive: { backgroundColor: colors.primary }, weekday: { ...typography.micro, color: colors.textSecondary }, dayNumber: { ...typography.bodyStrong, color: colors.text }, activeText: { color: colors.surface }, list: { gap: spacing.sm }, dayGroup: { gap: spacing.sm }, dateHeading: { ...typography.bodyStrong, color: colors.text, marginTop: spacing.sm }, card: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm, backgroundColor: colors.surface, borderRadius: radius.md, padding: spacing.md, borderWidth: 1, borderColor: colors.border, ...shadows.card }, pressed: { opacity: .75 }, time: { width: 70 }, timeText: { ...typography.bodyStrong, color: colors.text }, endTime: { ...typography.micro, color: colors.textSecondary }, rail: { width: 3, alignSelf: 'stretch', borderRadius: 2, backgroundColor: colors.primary }, copy: { flex: 1 }, service: { ...typography.bodyStrong, color: colors.text }, meta: { ...typography.caption, color: colors.textSecondary }, price: { ...typography.caption, color: colors.success } });
