import { Ionicons } from '@expo/vector-icons';
import { useFocusEffect, useNavigation } from '@react-navigation/native';
import { NativeStackNavigationProp } from '@react-navigation/native-stack';
import { useCallback, useMemo, useState } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { AppointmentDto } from '../apiTypes';
import { AppHeader, EmptyState, ErrorState, IconButton, LoadingState, Screen, StatusBadge } from '../components/ui';
import { endOfDay, localDateKey, startOfDay, weekDates } from '../domain/calendar';
import { appointmentsApi } from '../services/endpoints';
import { colors, radius, shadows, spacing, typography } from '../theme';
import { RootStackParamList } from '../types';
import { formatMoney } from '../utils/format';

export function CalendarScreen() {
  const navigation = useNavigation<NativeStackNavigationProp<RootStackParamList>>(); const [selected, setSelected] = useState(startOfDay(new Date())); const [items, setItems] = useState<AppointmentDto[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null);
  const week = useMemo(() => weekDates(selected), [selected]);
  const load = useCallback(async () => { setLoading(true); setError(null); try { setItems(await appointmentsApi.list(startOfDay(selected).toISOString(), endOfDay(selected).toISOString())); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Unable to load appointments.'); } finally { setLoading(false); } }, [selected]);
  useFocusEffect(useCallback(() => { void load(); }, [load]));
  return <Screen refreshing={loading && items.length > 0} onRefresh={() => void load()}><AppHeader eyebrow="SCHEDULE" title="Calendar" subtitle={selected.toLocaleDateString(undefined, { weekday: 'long', month: 'long', day: 'numeric' })} right={<IconButton icon="add" label="Create appointment" onPress={() => navigation.navigate('AppointmentEditor', { date: localDateKey(selected) })} />} />
    <View style={styles.week}>{week.map(date => { const active = localDateKey(date) === localDateKey(selected); return <Pressable key={localDateKey(date)} accessibilityRole="button" accessibilityState={{ selected: active }} onPress={() => setSelected(date)} style={[styles.day, active && styles.dayActive]}><Text style={[styles.weekday, active && styles.activeText]}>{date.toLocaleDateString(undefined, { weekday: 'narrow' })}</Text><Text style={[styles.dayNumber, active && styles.activeText]}>{date.getDate()}</Text></Pressable>; })}</View>
    {loading && !items.length ? <LoadingState label="Loading appointments…" /> : error ? <ErrorState message={error} onRetry={() => void load()} /> : items.length ? <View style={styles.list}>{items.map(item => <AppointmentCard key={item.id} item={item} onPress={() => navigation.navigate('AppointmentEditor', { appointmentId: item.id })} />)}</View> : <EmptyState icon="calendar-outline" title="No appointments" message="Your schedule is clear. Add an appointment for this day." />}
  </Screen>;
}
function AppointmentCard({ item, onPress }: { item: AppointmentDto; onPress: () => void }) { const start = new Date(item.startsAt); const end = new Date(item.endsAt); return <Pressable accessibilityRole="button" onPress={onPress} style={({ pressed }) => [styles.card, pressed && styles.pressed]}><View style={styles.time}><Text style={styles.timeText}>{start.toLocaleTimeString(undefined, { hour: 'numeric', minute: '2-digit' })}</Text><Text style={styles.endTime}>{end.toLocaleTimeString(undefined, { hour: 'numeric', minute: '2-digit' })}</Text></View><View style={styles.rail} /><View style={styles.copy}><Text style={styles.service}>{item.serviceName}</Text><Text style={styles.meta}>{item.customer?.name ?? 'Walk-in customer'}{item.assignedMember ? ` · ${item.assignedMember.user.fullName}` : ''}</Text>{item.price != null ? <Text style={styles.price}>{formatMoney(item.price)}</Text> : null}</View><StatusBadge label={item.status === 'NO_SHOW' ? 'No show' : item.status[0] + item.status.slice(1).toLowerCase()} /><Ionicons name="chevron-forward" size={17} color={colors.tabInactive} /></Pressable>; }
const styles = StyleSheet.create({ week: { flexDirection: 'row', gap: spacing.xxs, backgroundColor: colors.surface, borderRadius: radius.lg, padding: spacing.xs, borderWidth: 1, borderColor: colors.border }, day: { flex: 1, minHeight: 58, borderRadius: radius.md, alignItems: 'center', justifyContent: 'center', gap: 2 }, dayActive: { backgroundColor: colors.primary }, weekday: { ...typography.micro, color: colors.textSecondary }, dayNumber: { ...typography.bodyStrong, color: colors.text }, activeText: { color: colors.surface }, list: { gap: spacing.sm }, card: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm, backgroundColor: colors.surface, borderRadius: radius.md, padding: spacing.md, borderWidth: 1, borderColor: colors.border, ...shadows.card }, pressed: { opacity: .75 }, time: { width: 70 }, timeText: { ...typography.bodyStrong, color: colors.text }, endTime: { ...typography.micro, color: colors.textSecondary }, rail: { width: 3, alignSelf: 'stretch', borderRadius: 2, backgroundColor: colors.primary }, copy: { flex: 1 }, service: { ...typography.bodyStrong, color: colors.text }, meta: { ...typography.caption, color: colors.textSecondary }, price: { ...typography.caption, color: colors.success } });
