import { NativeStackScreenProps } from '@react-navigation/native-stack';
import { useEffect, useState } from 'react';
import { Alert, Modal, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { ReminderDto } from '../apiTypes';
import { AppHeader, EmptyState, ErrorState, IconButton, LoadingState, PrimaryButton, ReminderCard, Screen, SecondaryButton, SectionHeader, StatusBadge, UsageCard } from '../components/ui';
import { ApiError } from '../services/api';
import { remindersApi } from '../services/endpoints';
import { copyMessage, openSms, openWhatsApp } from '../services/messaging';
import { useAppState } from '../state/AppContext';
import { usePlanExperience } from '../state/PlanExperienceContext';
import { colors, radius, spacing, typography } from '../theme';
import { RootStackParamList } from '../types';
import { titleCase } from '../utils/format';

type Props = NativeStackScreenProps<RootStackParamList, 'Comeback'>;
export function ComebackScreen({ navigation }: Props) {
  const { reminders, customers, state, loadReminders, loadCustomers, loadDashboard } = useAppState(); const { usage, refresh: refreshPlan } = usePlanExperience(); const [selected, setSelected] = useState<ReminderDto | null>(null); const [creating, setCreating] = useState(false); const [customerId, setCustomerId] = useState(''); const [service, setService] = useState(''); const [lastVisit, setLastVisit] = useState(''); const [dueDate, setDueDate] = useState(''); const [mutation, setMutation] = useState<string | null>(null); const [error, setError] = useState<string | null>(null);
  useEffect(() => { void loadReminders(); if (!state.customers.loaded) void loadCustomers(); }, [loadCustomers, loadReminders, state.customers.loaded]); const due = reminders.filter(item => item.isDueNow);
  const runDevice = async (action: () => Promise<unknown>, label: string) => { try { await action(); Alert.alert(label); } catch { Alert.alert('Couldn’t open this action', 'Check that the required app is available.'); } };
  const create = async () => { if (mutation) return; setMutation('create'); setError(null); try { await remindersApi.create({ customerId: customerId || undefined, serviceName: service.trim() || undefined, lastVisitDate: lastVisit ? new Date(`${lastVisit}T12:00:00`).toISOString() : undefined, dueDate: dueDate ? new Date(`${dueDate}T12:00:00`).toISOString() : undefined }); void refreshPlan(); setCreating(false); setService(''); setLastVisit(''); setDueDate(''); await Promise.all([loadReminders(), loadDashboard()]); } catch (caught) { setError(caught instanceof ApiError ? caught.message : 'Unable to create reminder.'); } finally { setMutation(null); } };
  const generate = async () => { if (!selected || mutation) return; setMutation('generate'); setError(null); try { const result = await remindersApi.generateMessage(selected.id); setSelected(current => current ? { ...current, message: result.message } : current); } catch (caught) { setError(caught instanceof ApiError ? caught.message : 'Unable to prepare message.'); } finally { setMutation(null); } };
  const transition = async (kind: 'sent'|'completed'|'dismissed') => { if (!selected || mutation) return; setMutation(kind); setError(null); try { const result = kind === 'sent' ? await remindersApi.markSent(selected.id) : kind === 'completed' ? await remindersApi.markCompleted(selected.id) : await remindersApi.dismiss(selected.id); setSelected(current => current ? { ...current, ...result } : result); await Promise.all([loadReminders(), loadDashboard()]); Alert.alert(kind === 'sent' ? 'Message marked as sent' : `Reminder ${titleCase(kind)}`, kind === 'sent' ? 'This records your manual send. CHAKUSA did not deliver the message.' : undefined); if (kind !== 'sent') setSelected(null); } catch (caught) { setError(caught instanceof ApiError ? caught.message : 'Unable to update reminder.'); } finally { setMutation(null); } };
  return <><Screen><AppHeader eyebrow="CUSTOMER RECOVERY" title="Comeback reminders" subtitle={`${due.length} customer${due.length === 1 ? '' : 's'} due`} right={<IconButton icon="add" label="Create reminder" onPress={() => setCreating(true)} />} />{usage ? <UsageCard label="Open reminders" current={usage.openReminders.current} limit={usage.openReminders.limit} onViewPro={() => navigation.navigate('Pro')} /> : null}{!state.reminders.loaded && state.reminders.loading ? <LoadingState label="Loading reminders…" /> : state.reminders.error ? <ErrorState message={state.reminders.error} onRetry={() => void loadReminders()} /> : <><SectionHeader title="Customers due" />{due.length ? <View style={styles.list}>{due.map(reminder => <ReminderCard key={reminder.id} reminder={reminder} onPress={() => setSelected(reminder)} />)}</View> : <EmptyState title="You’re caught up" message="Upcoming customer reminders will appear here." />}<SectionHeader title="Completed" /><Text style={styles.completed}>{reminders.filter(item => item.status === 'completed').length} completed reminders</Text></>}</Screen>
    <Modal visible={Boolean(selected)} transparent animationType="slide" onRequestClose={() => setSelected(null)}><Pressable style={styles.overlay} onPress={() => !mutation && setSelected(null)}><Pressable style={styles.sheet} onPress={() => undefined}>{selected ? <><Text style={styles.sheetTitle}>{selected.customer?.name ?? 'Comeback reminder'}</Text><Text style={styles.sheetMeta}>{selected.serviceName ?? 'Service not specified'}</Text>{selected.message ? <View style={styles.message}><StatusBadge label={selected.status === 'sent' ? 'Message marked as sent' : 'Message prepared'} /><Text style={styles.messageText}>{selected.message}</Text></View> : <PrimaryButton disabled={Boolean(mutation)} fullWidth label={mutation === 'generate' ? 'Preparing…' : 'Prepare message'} onPress={() => void generate()} />}{selected.message ? <><SecondaryButton disabled={Boolean(mutation)} fullWidth icon="copy-outline" label="Copy message" onPress={() => void runDevice(() => copyMessage(selected.message!), 'Message copied')} /><SecondaryButton disabled={Boolean(mutation) || !selected.customer?.phone} fullWidth icon="chatbubble-outline" label="Open SMS" onPress={() => void runDevice(() => openSms(selected.customer!.phone!, selected.message!), 'Opening SMS')} /><SecondaryButton disabled={Boolean(mutation) || !selected.customer?.phone} fullWidth icon="logo-whatsapp" label="Open WhatsApp" onPress={() => void runDevice(() => openWhatsApp(selected.customer!.phone!, selected.message!), 'Opening WhatsApp')} />{selected.status === 'due' ? <PrimaryButton disabled={Boolean(mutation)} fullWidth label={mutation === 'sent' ? 'Saving…' : 'Mark message as sent'} onPress={() => void transition('sent')} /> : null}</> : null}<View style={styles.lastActions}><SecondaryButton disabled={Boolean(mutation)} compact label={mutation === 'completed' ? 'Saving…' : 'Complete'} onPress={() => void transition('completed')} /><SecondaryButton disabled={Boolean(mutation)} compact label="Dismiss" onPress={() => void transition('dismissed')} /></View>{error ? <Text style={styles.error}>{error}</Text> : null}</> : null}</Pressable></Pressable></Modal>
    <Modal visible={creating} transparent animationType="slide" onRequestClose={() => setCreating(false)}><Pressable style={styles.overlay} onPress={() => !mutation && setCreating(false)}><Pressable style={styles.sheet} onPress={() => undefined}><Text style={styles.sheetTitle}>New comeback reminder</Text><Text style={styles.label}>Customer</Text><View style={styles.choices}>{customers.map(customer => <Pressable key={customer.id} onPress={() => setCustomerId(customer.id)} style={[styles.choice, customerId === customer.id && styles.choiceActive]}><Text style={[styles.choiceText, customerId === customer.id && styles.choiceTextActive]}>{customer.name}</Text></Pressable>)}</View><Field label="Service" value={service} onChangeText={setService} /><Field label="Last visit (YYYY-MM-DD)" value={lastVisit} onChangeText={setLastVisit} /><Field label="Due date (optional, YYYY-MM-DD)" value={dueDate} onChangeText={setDueDate} /><Text style={styles.helper}>Leave due date empty to use the business reminder timing.</Text>{error ? <Text style={styles.error}>{error}</Text> : null}<PrimaryButton disabled={Boolean(mutation) || (!lastVisit && !dueDate)} fullWidth label={mutation === 'create' ? 'Creating…' : 'Create reminder'} onPress={() => void create()} /></Pressable></Pressable></Modal>
  </>;
}
function Field({ label, ...props }: { label: string; value: string; onChangeText: (value: string) => void }) { return <View><Text style={styles.label}>{label}</Text><TextInput {...props} style={styles.input} /></View>; }
const styles = StyleSheet.create({ list: { gap: spacing.sm }, completed: { ...typography.body, color: colors.textSecondary }, overlay: { flex: 1, backgroundColor: colors.overlay, justifyContent: 'flex-end' }, sheet: { backgroundColor: colors.surface, borderTopLeftRadius: radius.xl, borderTopRightRadius: radius.xl, padding: spacing.xl, paddingBottom: 40, gap: spacing.sm }, sheetTitle: { ...typography.heading, color: colors.text }, sheetMeta: { ...typography.body, color: colors.textSecondary }, message: { backgroundColor: colors.background, borderRadius: radius.md, padding: spacing.md, marginVertical: spacing.sm, gap: spacing.sm }, messageText: { ...typography.body, color: colors.text }, lastActions: { flexDirection: 'row', gap: spacing.xs }, label: { ...typography.caption, color: colors.text, marginTop: spacing.xs }, input: { minHeight: 48, backgroundColor: colors.background, borderWidth: 1, borderColor: colors.border, borderRadius: radius.md, paddingHorizontal: spacing.md, ...typography.body, color: colors.text }, choices: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.xs }, choice: { minHeight: 40, justifyContent: 'center', paddingHorizontal: spacing.sm, borderRadius: radius.round, borderWidth: 1, borderColor: colors.border }, choiceActive: { borderColor: colors.primary }, choiceText: { ...typography.caption, color: colors.textSecondary }, choiceTextActive: { color: colors.primary, fontWeight: '700' }, helper: { ...typography.caption, color: colors.textSecondary }, error: { ...typography.caption, color: colors.negative } });
