import { RouteProp, useNavigation, useRoute } from '@react-navigation/native';
import { NativeStackNavigationProp } from '@react-navigation/native-stack';
import { useEffect, useMemo, useState } from 'react';
import { Modal, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { AppHeader, CustomerRow, EmptyState, ErrorState, IconButton, LoadingState, PrimaryButton, Screen, SearchBar, SecondaryButton, UsageCard } from '../components/ui';
import { CountryPhoneInput } from '../components/CountryPhoneInput';
import { AudienceSummary } from '../components/AudienceSummary';
import { AudienceCenterDto, SmartAudienceKey } from '../apiTypes';
import { ApiError } from '../services/api';
import { customersApi } from '../services/endpoints';
import { useAppState } from '../state/AppContext';
import { usePlanExperience } from '../state/PlanExperienceContext';
import { colors, radius, spacing, typography } from '../theme';
import { MainTabParamList, RootStackParamList } from '../types';

export function CustomersScreen() {
  const navigation = useNavigation<NativeStackNavigationProp<RootStackParamList>>(); const route = useRoute<RouteProp<MainTabParamList, 'Customers'>>(); const { customers, customerTotal, customerPage, state, loadCustomers } = useAppState(); const { usage, refresh: refreshPlan } = usePlanExperience(); const [search, setSearch] = useState(''); const [showCreate, setShowCreate] = useState(false); const [name, setName] = useState(''); const [phone, setPhone] = useState(''); const [email, setEmail] = useState(''); const [notes, setNotes] = useState(''); const [saving, setSaving] = useState(false); const [formError, setFormError] = useState<string | null>(null); const [audiences, setAudiences] = useState<AudienceCenterDto | null>(null); const [audienceKey, setAudienceKey] = useState<SmartAudienceKey | null>(route.params?.audienceKey ?? null);
  useEffect(() => { const timer = setTimeout(() => void loadCustomers(search), 300); return () => clearTimeout(timer); }, [loadCustomers, search]);
  useEffect(() => { void customersApi.audiences().then(setAudiences).catch(() => setAudiences(null)); }, []);
  useEffect(() => { if (route.params?.audienceKey) setAudienceKey(route.params.audienceKey); }, [route.params?.audienceKey]);
  const visibleCustomers = useMemo(() => !audienceKey || !audiences ? customers : customers.filter(customer => audiences.audiences.find(item => item.key === audienceKey)?.customerIds.includes(customer.id)), [audienceKey, audiences, customers]);
  const create = async () => { if (saving) return; setSaving(true); setFormError(null); try { const customer = await customersApi.create({ name: name.trim(), phone: phone.trim() || undefined, email: email.trim() || undefined, notes: notes.trim() || undefined }); void refreshPlan(); setShowCreate(false); setName(''); setPhone(''); setEmail(''); setNotes(''); await loadCustomers(search); navigation.navigate('CustomerProfile', { customerId: customer.id }); } catch (error) { setFormError(error instanceof ApiError ? error.message : 'Unable to create customer.'); } finally { setSaving(false); } };
  return <><Screen><AppHeader title="Customers" subtitle={`${customerTotal} customer${customerTotal === 1 ? '' : 's'}`} right={<View style={styles.headerActions}><IconButton icon="download-outline" label="Import customers" onPress={() => navigation.navigate('CustomersImport')} /><IconButton icon="person-add-outline" label="Create customer" onPress={() => setShowCreate(true)} /></View>} />{usage ? <UsageCard label="Customers" current={usage.customers.current} limit={usage.customers.limit} onViewPro={() => navigation.navigate('Pro')} /> : null}{audiences ? <AudienceSummary data={audiences} selected={audienceKey} onSelect={setAudienceKey} /> : null}<SearchBar value={search} onChangeText={setSearch} placeholder="Search name, phone, or email" />{!state.customers.loaded && state.customers.loading ? <LoadingState label="Loading customers…" /> : state.customers.error ? <ErrorState message={state.customers.error} onRetry={() => void loadCustomers(search)} /> : visibleCustomers.length ? <View>{visibleCustomers.map(customer => <CustomerRow key={customer.id} customer={customer} onPress={() => navigation.navigate('CustomerProfile', { customerId: customer.id })} />)}</View> : <EmptyState title={audienceKey ? 'No matching customers' : search ? 'No customers found' : 'No customers yet'} message={audienceKey ? 'Load more customers or choose another audience.' : search ? 'Try a different search.' : 'Create your first customer to begin recovery.'} icon="people-outline" />}{customers.length < customerTotal ? <PrimaryButton disabled={state.customers.loading} fullWidth label={state.customers.loading ? 'Loading…' : 'Load more customers'} onPress={() => void loadCustomers(search, customerPage + 1, true)} /> : null}</Screen>
    <Modal visible={showCreate} transparent animationType="slide" onRequestClose={() => setShowCreate(false)}><Pressable style={styles.overlay} onPress={() => !saving && setShowCreate(false)}><Pressable style={styles.sheet} onPress={() => undefined}><Text style={styles.sheetTitle}>New customer</Text><Field label="Name" value={name} onChangeText={setName} /><CountryPhoneInput value={phone} onChange={setPhone} /><Field label="Email" value={email} onChangeText={setEmail} keyboardType="email-address" autoCapitalize="none" /><Field label="Notes" value={notes} onChangeText={setNotes} />{formError ? <Text style={styles.error}>{formError}</Text> : null}<PrimaryButton disabled={saving || !name.trim()} fullWidth label={saving ? 'Creating…' : 'Create customer'} onPress={() => void create()} /><SecondaryButton disabled={saving} fullWidth label="Cancel" onPress={() => setShowCreate(false)} /></Pressable></Pressable></Modal>
  </>;
}
function Field({ label, ...props }: { label: string; value: string; onChangeText: (value: string) => void; keyboardType?: 'email-address'; autoCapitalize?: 'none' }) { return <View><Text style={styles.label}>{label}</Text><TextInput {...props} style={styles.input} /></View>; }
const styles = StyleSheet.create({ headerActions: { flexDirection: 'row', gap: spacing.xs }, overlay: { flex: 1, backgroundColor: colors.overlay, justifyContent: 'flex-end' }, sheet: { backgroundColor: colors.surface, borderTopLeftRadius: radius.xl, borderTopRightRadius: radius.xl, padding: spacing.xl, paddingBottom: 40, gap: spacing.md }, sheetTitle: { ...typography.heading, color: colors.text }, label: { ...typography.caption, color: colors.text, marginBottom: spacing.xs }, input: { minHeight: 48, backgroundColor: colors.background, borderWidth: 1, borderColor: colors.border, borderRadius: radius.md, paddingHorizontal: spacing.md, ...typography.body, color: colors.text }, error: { ...typography.caption, color: colors.negative } });
