import { useCallback, useEffect, useState } from 'react';
import { Alert, Share, StyleSheet, Text, View } from 'react-native';
import { AppHeader, EmptyState, ErrorState, LoadingState, PrimaryButton, Screen, SecondaryButton, StatusBadge } from '../components/ui';
import type { CalendarSubscriptionDto } from '../apiTypes';
import { calendarApi } from '../services/endpoints';
import { colors, radius, spacing, typography } from '../theme';
import { formatDateTime } from '../utils/format';

export function ExternalCalendarScreen() {
  const [items, setItems] = useState<CalendarSubscriptionDto[]>([]); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null);
  const load = useCallback(async () => { setLoading(true); setError(null); try { setItems(await calendarApi.listSubscriptions()); } catch (e) { setError(e instanceof Error ? e.message : 'Could not load calendar subscriptions.'); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  const create = async () => { if (busy) return; setBusy(true); try { const created = await calendarApi.createSubscription(); await Share.share({ title: 'Chakusa calendar subscription', message: `Add this read-only calendar URL to Apple Calendar, Google Calendar, or Outlook:\n\n${created.feedUrl}\n\nKeep it private. Revoke it in Chakusa if it is shared accidentally.` }); await load(); } catch (e) { Alert.alert('Could not create calendar link', e instanceof Error ? e.message : 'Please try again.'); } finally { setBusy(false); } };
  const revoke = (item: CalendarSubscriptionDto) => Alert.alert('Revoke this calendar link?', 'Calendar apps will stop receiving updates from this link. This cannot be undone.', [{ text: 'Cancel', style: 'cancel' }, { text: 'Revoke', style: 'destructive', onPress: async () => { setBusy(true); try { await calendarApi.revokeSubscription(item.id); await load(); } catch (e) { Alert.alert('Could not revoke link', e instanceof Error ? e.message : 'Please try again.'); } finally { setBusy(false); } } }]);
  if (loading) return <Screen><LoadingState label="Loading calendar settings…" /></Screen>; if (error) return <Screen><ErrorState message={error} onRetry={() => void load()} /></Screen>;
  return <Screen style={styles.screen}><AppHeader title="External calendar" subtitle="Keep a read-only Chakusa calendar in Apple, Google, or Outlook." /><View style={styles.notice}><Text style={styles.noticeTitle}>Private subscription links</Text><Text style={styles.noticeText}>Links include business name, service names, times, and cancellation state only. Treat each link like a password and revoke it if exposed.</Text></View><PrimaryButton label={busy ? 'Working…' : 'Create calendar link'} icon="add-outline" disabled={busy} onPress={() => void create()} />{items.length === 0 ? <EmptyState title="No calendar links" message="Create one to subscribe from your calendar app." icon="calendar-outline" /> : <View style={styles.list}>{items.map(item => <View key={item.id} style={styles.card}><View style={styles.row}><View style={styles.copy}><Text style={styles.label}>{item.label}</Text><Text style={styles.meta}>Created {formatDateTime(item.createdAt)}</Text>{item.lastAccessedAt ? <Text style={styles.meta}>Last refreshed {formatDateTime(item.lastAccessedAt)}</Text> : null}</View><StatusBadge label={item.revokedAt ? 'Revoked' : 'Active'} /></View>{!item.revokedAt ? <SecondaryButton label="Revoke link" icon="close-circle-outline" disabled={busy} onPress={() => revoke(item)} /> : null}</View>)}</View>}</Screen>;
}
const styles = StyleSheet.create({ screen: { gap: spacing.lg }, notice: { padding: spacing.lg, borderRadius: radius.lg, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface }, noticeTitle: { ...typography.bodyStrong, color: colors.text }, noticeText: { ...typography.caption, color: colors.textSecondary, marginTop: spacing.xs, lineHeight: 20 }, list: { gap: spacing.md }, card: { padding: spacing.lg, borderRadius: radius.lg, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface, gap: spacing.md }, row: { flexDirection: 'row', gap: spacing.sm, alignItems: 'flex-start' }, copy: { flex: 1 }, label: { ...typography.bodyStrong, color: colors.text }, meta: { ...typography.caption, color: colors.textSecondary, marginTop: 3 } });
