import { NativeStackScreenProps } from '@react-navigation/native-stack';
import { useCallback, useEffect, useMemo, useState } from 'react';
import { Alert, StyleSheet, Text, View } from 'react-native';
import { LeadDto, LeadStatus } from '../apiTypes';
import { AppHeader, Divider, EmptyState, ErrorState, InfoRow, LoadingState, PrimaryButton, Screen, SecondaryButton, SectionHeader, StatusBadge, Timeline } from '../components/ui';
import { ApiError } from '../services/api';
import { leadsApi } from '../services/endpoints';
import { copyMessage, openSms, openWhatsApp } from '../services/messaging';
import { useAppState } from '../state/AppContext';
import { colors, radius, spacing, typography } from '../theme';
import { RootStackParamList, TimelineItem } from '../types';
import { formatDateTime, formatDuration, formatMoney, titleCase } from '../utils/format';

type Props = NativeStackScreenProps<RootStackParamList, 'LeadDetail'>;
export function LeadDetailScreen({ route, navigation }: Props) {
  const { loadLeads, loadDashboard } = useAppState(); const [lead, setLead] = useState<LeadDto | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [mutation, setMutation] = useState<string | null>(null);
  const load = useCallback(async () => { setLoading(true); setError(null); try { setLead(await leadsApi.get(route.params.leadId)); } catch (caught) { setError(caught instanceof ApiError ? caught.message : 'Unable to load lead.'); } finally { setLoading(false); } }, [route.params.leadId]); useEffect(() => { void load(); }, [load]);
  const timeline = useMemo<TimelineItem[]>(() => lead ? [{ id: 'missed', date: 'MISSED', title: 'Incoming call', detail: formatDateTime(lead.missedCallTime), tone: 'attention' }, ...(lead.contactedAt ? [{ id: 'contacted', date: 'CONTACTED', title: 'Follow-up recorded', detail: formatDateTime(lead.contactedAt), tone: 'success' as const }] : []), ...(lead.bookedAt ? [{ id: 'booked', date: 'BOOKED', title: 'Appointment booked', detail: formatDateTime(lead.bookedAt), tone: 'success' as const }] : []), ...(lead.wonAt ? [{ id: 'won', date: 'WON', title: 'Lead won', detail: formatDateTime(lead.wonAt), value: formatMoney(lead.estimatedValue), tone: 'success' as const }] : []), ...(lead.lostAt ? [{ id: 'lost', date: 'LOST', title: 'Lead lost', detail: formatDateTime(lead.lostAt) }] : [])] : [], [lead]);
  const runDevice = async (action: () => Promise<unknown>, label: string) => { try { await action(); Alert.alert(label); } catch { Alert.alert('Couldn’t open this action', 'Check that the required app is available.'); } };
  const generate = async () => { if (!lead || mutation) return; setMutation('generate'); setError(null); try { const result = await leadsApi.generateMessage(lead.id); setLead(current => current ? { ...current, generatedReply: result.message } : current); } catch (caught) { setError(caught instanceof ApiError ? caught.message : 'Unable to prepare message.'); } finally { setMutation(null); } };
  const transition = async (status: Exclude<LeadStatus,'new'>) => { if (!lead || mutation) return; setMutation(status); setError(null); try { const result = await leadsApi.transition(lead.id, status); setLead(current => current ? { ...current, ...result } : result); await Promise.all([loadLeads(), loadDashboard()]); Alert.alert(`Marked ${titleCase(status)}`, status === 'contacted' ? 'The follow-up is recorded. CHAKUSA did not send a message.' : 'The lead status was saved.'); } catch (caught) { setError(caught instanceof ApiError ? caught.message : 'Unable to update lead.'); } finally { setMutation(null); } };
  if (loading && !lead) return <Screen><LoadingState label="Loading lead…" /></Screen>; if (error && !lead) return <Screen><ErrorState message={error} onRetry={() => void load()} /></Screen>; if (!lead) return <Screen><EmptyState title="Lead not found" message="This lead is no longer available." /></Screen>;
  const phone = lead.customer?.phone ?? ''; const message = lead.generatedReply;
  return <Screen><AppHeader eyebrow="LEAD" title={lead.customer?.name ?? 'Unassigned lead'} subtitle={phone || 'No phone number'} right={<StatusBadge label={titleCase(lead.status)} />} /><View style={styles.summary}><InfoRow icon="cut-outline" label="Service" value={lead.serviceRequested ?? 'Not specified'} /><Divider /><InfoRow icon="flame-outline" label="Urgency" value={titleCase(lead.urgency)} /><Divider /><InfoRow icon="call-outline" label="Missed call" value={formatDateTime(lead.missedCallTime)} /><Divider /><InfoRow icon="cash-outline" label="Estimated value" value={formatMoney(lead.estimatedValue)} /></View>{lead.responseTimeSeconds != null ? <View style={styles.response}><Text style={styles.responseLabel}>RESPONSE TIME</Text><Text style={styles.responseMinutes}>{formatDuration(lead.responseTimeSeconds)}</Text></View> : null}<View><SectionHeader title="Notes" /><View style={styles.note}><Text style={styles.noteText}>{lead.notes ?? 'No notes'}</Text></View></View><View><SectionHeader title="Message" />{message ? <View style={styles.message}><StatusBadge label="Message prepared" /><Text style={styles.messageText}>{message}</Text><View style={styles.messageActions}><SecondaryButton disabled={Boolean(mutation)} compact icon="copy-outline" label="Copy" onPress={() => void runDevice(() => copyMessage(message), 'Message copied')} /><SecondaryButton disabled={Boolean(mutation) || !phone} compact icon="chatbubble-outline" label="Open SMS" onPress={() => void runDevice(() => openSms(phone, message), 'Opening SMS')} /><SecondaryButton disabled={Boolean(mutation) || !phone} compact icon="logo-whatsapp" label="Open WhatsApp" onPress={() => void runDevice(() => openWhatsApp(phone, message), 'Opening WhatsApp')} /></View></View> : <PrimaryButton disabled={Boolean(mutation)} label={mutation === 'generate' ? 'Preparing…' : 'Prepare message'} onPress={() => void generate()} />}</View>{error ? <Text accessibilityRole="alert" style={styles.error}>{error}</Text> : null}<View><SectionHeader title="Update lead" /><View style={styles.statusActions}>{(['contacted','booked','won','lost'] as const).map(status => <SecondaryButton key={status} disabled={Boolean(mutation)} compact label={mutation === status ? 'Saving…' : `Mark ${titleCase(status)}`} onPress={() => void transition(status)} />)}</View></View><View><SectionHeader title="Timeline" /><Timeline items={timeline} /></View>{lead.customerId ? <PrimaryButton fullWidth icon="person-outline" label="View customer profile" onPress={() => navigation.navigate('CustomerProfile', { customerId: lead.customerId! })} /> : null}</Screen>;
}
const styles = StyleSheet.create({ summary: { backgroundColor: colors.surface, borderRadius: radius.md, borderWidth: 1, borderColor: colors.border, paddingHorizontal: spacing.md }, response: { backgroundColor: colors.surface, borderRadius: radius.md, borderWidth: 1, borderColor: colors.attention, padding: spacing.md }, responseLabel: { ...typography.micro, color: colors.textSecondary }, responseMinutes: { ...typography.bodyStrong, color: colors.text, marginTop: 2 }, note: { backgroundColor: colors.surface, borderRadius: radius.md, borderWidth: 1, borderColor: colors.border, padding: spacing.md, marginTop: spacing.sm }, noteText: { ...typography.body, color: colors.text }, message: { backgroundColor: colors.surface, borderRadius: radius.md, borderWidth: 1, borderColor: colors.border, padding: spacing.md, gap: spacing.md, marginTop: spacing.sm }, messageText: { ...typography.body, color: colors.text }, messageActions: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.xs }, statusActions: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.xs, marginTop: spacing.sm }, error: { ...typography.caption, color: colors.negative } });
