import { useNavigation } from '@react-navigation/native';
import { NativeStackNavigationProp } from '@react-navigation/native-stack';
import { useEffect, useMemo, useState } from 'react';
import { Modal, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { LeadStatus } from '../apiTypes';
import { AppHeader, EmptyState, ErrorState, FilterTabs, IconButton, LeadCard, LoadingState, PrimaryButton, Screen, SearchBar, SecondaryButton } from '../components/ui';
import { CountryPhoneInput } from '../components/CountryPhoneInput';
import { ApiError } from '../services/api';
import { customersApi, leadsApi } from '../services/endpoints';
import { useAppState } from '../state/AppContext';
import { colors, radius, spacing, typography } from '../theme';
import { RootStackParamList } from '../types';
import { titleCase } from '../utils/format';

const filters = ['all', 'new', 'contacted', 'booked', 'won', 'lost'] as const;
export function LeadsScreen() {
  const navigation = useNavigation<NativeStackNavigationProp<RootStackParamList>>(); const { leads, leadTotal, customers, state, loadLeads, loadCustomers } = useAppState(); const [filter, setFilter] = useState<(typeof filters)[number]>('all'); const [search, setSearch] = useState(''); const [creating, setCreating] = useState(false); const [callerMode, setCallerMode] = useState<'existing'|'new'>('existing'); const [customerId, setCustomerId] = useState(''); const [callerName, setCallerName] = useState(''); const [callerPhone, setCallerPhone] = useState(''); const [service, setService] = useState(''); const [value, setValue] = useState(''); const [notes, setNotes] = useState(''); const [urgency, setUrgency] = useState<'low'|'medium'|'high'>('medium'); const [saving, setSaving] = useState(false); const [formError, setFormError] = useState<string | null>(null);
  useEffect(() => { void loadLeads(filter === 'all' ? undefined : filter); }, [filter, loadLeads]); useEffect(() => { if (!state.customers.loaded) void loadCustomers(); }, [loadCustomers, state.customers.loaded]);
  const visible = useMemo(() => leads.filter(lead => `${lead.customer?.name ?? ''} ${lead.serviceRequested ?? ''}`.toLowerCase().includes(search.toLowerCase())), [leads, search]);
  const create = async () => { if (saving) return; setSaving(true); setFormError(null); try { let selectedCustomerId = customerId || undefined; if (callerMode === 'new') { const customer = await customersApi.create({ name: callerName.trim(), phone: callerPhone }); selectedCustomerId = customer.id; await loadCustomers(); } const lead = await leadsApi.create({ customerId: selectedCustomerId, source: 'missed_call', missedCallTime: new Date().toISOString(), serviceRequested: service.trim() || undefined, urgency, estimatedValue: value ? Number(value) : undefined, notes: notes.trim() || undefined }); setCreating(false); setService(''); setValue(''); setNotes(''); setCallerName(''); setCallerPhone(''); await loadLeads(filter === 'all' ? undefined : filter); navigation.navigate('LeadDetail', { leadId: lead.id }); } catch (error) { setFormError(error instanceof ApiError ? error.message : 'Unable to create lead.'); } finally { setSaving(false); } };
  return <><Screen><AppHeader title="Leads" subtitle={`${leadTotal} lead${leadTotal === 1 ? '' : 's'}`} right={<IconButton icon="add" label="Create missed-call lead" onPress={() => setCreating(true)} />} /><SearchBar value={search} onChangeText={setSearch} placeholder="Search visible leads" /><FilterTabs options={filters} value={filter} onChange={setFilter} />{!state.leads.loaded && state.leads.loading ? <LoadingState label="Loading leads…" /> : state.leads.error ? <ErrorState message={state.leads.error} onRetry={() => void loadLeads(filter === 'all' ? undefined : filter)} /> : visible.length ? <View style={styles.list}>{visible.map(lead => <LeadCard key={lead.id} lead={lead} onPress={() => navigation.navigate('LeadDetail', { leadId: lead.id })} />)}</View> : <EmptyState title={search ? 'No leads found' : 'No leads here'} message={search ? 'Try a different search.' : 'Create a missed-call lead to begin follow-up.'} icon="call-outline" />}</Screen>
    <Modal visible={creating} transparent animationType="slide" onRequestClose={() => setCreating(false)}><Pressable style={styles.overlay} onPress={() => !saving && setCreating(false)}><Pressable style={styles.sheet} onPress={() => undefined}><Text style={styles.sheetTitle}>Missed-call lead</Text><View style={styles.segment}><Pressable onPress={() => setCallerMode('existing')} style={[styles.segmentItem, callerMode === 'existing' && styles.segmentActive]}><Text style={[styles.segmentText, callerMode === 'existing' && styles.segmentTextActive]}>Existing customer</Text></Pressable><Pressable onPress={() => setCallerMode('new')} style={[styles.segmentItem, callerMode === 'new' && styles.segmentActive]}><Text style={[styles.segmentText, callerMode === 'new' && styles.segmentTextActive]}>New caller</Text></Pressable></View>{callerMode === 'existing' ? <><Text style={styles.label}>Customer</Text><View style={styles.choices}>{customers.map(customer => <Pressable key={customer.id} onPress={() => setCustomerId(customer.id)} style={[styles.choice, customerId === customer.id && styles.choiceActive]}><Text style={[styles.choiceText, customerId === customer.id && styles.choiceTextActive]}>{customer.name}</Text></Pressable>)}</View></> : <><Field label="Caller name" value={callerName} onChangeText={setCallerName} /><CountryPhoneInput value={callerPhone} onChange={setCallerPhone} label="Caller phone" /></>}<Field label="Service requested" value={service} onChangeText={setService} /><Field label="Estimated value" value={value} onChangeText={setValue} keyboardType="decimal-pad" /><Field label="Notes" value={notes} onChangeText={setNotes} /><Text style={styles.label}>Urgency</Text><View style={styles.choices}>{(['low','medium','high'] as const).map(item => <Pressable key={item} onPress={() => setUrgency(item)} style={[styles.choice, urgency === item && styles.choiceActive]}><Text style={[styles.choiceText, urgency === item && styles.choiceTextActive]}>{titleCase(item)}</Text></Pressable>)}</View>{formError ? <Text style={styles.error}>{formError}</Text> : null}<PrimaryButton disabled={saving || (callerMode === 'existing' ? !customerId : !callerName.trim() || callerPhone.length < 7)} fullWidth label={saving ? 'Creating…' : 'Create lead'} onPress={() => void create()} /><SecondaryButton disabled={saving} fullWidth label="Cancel" onPress={() => setCreating(false)} /></Pressable></Pressable></Modal>
  </>;
}
function Field({ label, ...props }: { label: string; value: string; onChangeText: (value: string) => void; keyboardType?: 'decimal-pad' }) { return <View><Text style={styles.label}>{label}</Text><TextInput {...props} style={styles.input} /></View>; }
const styles = StyleSheet.create({ list: { gap: spacing.sm }, overlay: { flex: 1, backgroundColor: colors.overlay, justifyContent: 'flex-end' }, sheet: { maxHeight: '94%', backgroundColor: colors.surface, borderTopLeftRadius: radius.xl, borderTopRightRadius: radius.xl, padding: spacing.xl, paddingBottom: 40, gap: spacing.md }, sheetTitle: { ...typography.heading, color: colors.text }, label: { ...typography.caption, color: colors.text }, input: { minHeight: 48, backgroundColor: colors.background, borderWidth: 1, borderColor: colors.border, borderRadius: radius.md, paddingHorizontal: spacing.md, ...typography.body, color: colors.text }, choices: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.xs }, choice: { minHeight: 40, justifyContent: 'center', paddingHorizontal: spacing.sm, borderRadius: radius.round, borderWidth: 1, borderColor: colors.border }, choiceActive: { borderColor: colors.primary }, choiceText: { ...typography.caption, color: colors.textSecondary }, choiceTextActive: { color: colors.primary, fontWeight: '700' }, helper: { ...typography.caption, color: colors.textSecondary }, error: { ...typography.caption, color: colors.negative }, segment: { height: 44, flexDirection: 'row', padding: 3, borderRadius: radius.md, backgroundColor: colors.background }, segmentItem: { flex: 1, alignItems: 'center', justifyContent: 'center', borderRadius: radius.sm }, segmentActive: { backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border }, segmentText: { ...typography.caption, color: colors.textSecondary }, segmentTextActive: { color: colors.text, fontWeight: '700' } });
