import { Ionicons } from '@expo/vector-icons';
import { useState } from 'react';
import { Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { AuthForm } from '../components/AuthForm';
import { CountryPhoneInput } from '../components/CountryPhoneInput';
import { PrimaryButton, Screen, SecondaryButton } from '../components/ui';
import { GOAL_COPY, toggleGoal, type BusinessGoal } from '../domain/onboarding';
import { INDUSTRY_EXPERIENCES, industryExperience } from '../domain/industryExperience';
import { businessApi } from '../services/endpoints';
import { useAuth } from '../state/AuthContext';
import { usePreferences, type TeamSize } from '../state/PreferencesContext';
import { colors, radius, spacing, typography } from '../theme';

const TEAM_SIZES: { id: TeamSize; label: string }[] = [
  { id: 'just_me', label: 'Just me' },
  { id: 'small', label: '2-4 people' },
  { id: 'medium', label: '5-9 people' },
  { id: 'large', label: '10+ people' },
];
const GOALS = Object.keys(GOAL_COPY) as BusinessGoal[];

export function PremiumFtueScreen() {
  const { status, business, refreshBusiness } = useAuth(); const preferences = usePreferences();
  const [name, setName] = useState(business?.name ?? ''); const [phone, setPhone] = useState(business?.phone ?? ''); const [hours, setHours] = useState(typeof business?.workingHours?.summary === 'string' ? business.workingHours.summary : 'Mon-Sat, 9:00 AM-6:00 PM'); const [services, setServices] = useState<string[]>(business?.defaultServices ?? []); const [reviewLink, setReviewLink] = useState(business?.googleReviewLink ?? ''); const [saving, setSaving] = useState(false); const step = preferences.onboardingStep;
  const selected = industryExperience(preferences.industry); const next = () => preferences.setOnboardingStep(Math.min(11, step + 1));
  const saveBusiness = async (body: Parameters<typeof businessApi.patch>[0]) => { setSaving(true); try { if (!business) await businessApi.create({ name: name.trim(), industry: preferences.industry || undefined, phone: phone || undefined }); else await businessApi.patch(body); await refreshBusiness(); next(); } finally { setSaving(false); } };
  if (status === 'anonymous' && step === 0) return <Screen><View style={styles.welcome}><Text style={styles.kicker}>CHAKUSA</Text><View style={styles.hero}><Ionicons name="sparkles-outline" size={48} color={colors.primary} /></View><Text style={styles.title}>Recover customers.{`\n`}Build your reputation.{`\n`}Bring them back.</Text><Text style={styles.copy}>A clear, calm place to keep every customer opportunity moving.</Text><PrimaryButton fullWidth label="Create account" onPress={() => preferences.setOnboardingStep(1)} /><SecondaryButton fullWidth label="Sign in" onPress={() => preferences.setOnboardingStep(1)} /></View></Screen>;
  if (status === 'anonymous') return <Screen><View style={styles.auth}><Text style={styles.kicker}>CHAKUSA</Text><Text style={styles.title}>Your customer recovery starts here.</Text><Text style={styles.copy}>Sign in or create an account to set up your business.</Text><AuthForm defaultMode="register" onSuccess={() => preferences.setOnboardingStep(2)} /></View></Screen>;
  if (step <= 2) return <Screen><Header step={1} /><Text style={styles.title}>What kind of business do you run?</Text><Text style={styles.copy}>We’ll tailor the language and service suggestions to you.</Text><View style={styles.grid}>{INDUSTRY_EXPERIENCES.map(item => <Pressable key={item.id} accessibilityRole="button" accessibilityState={{ selected: preferences.industry === item.id }} onPress={() => preferences.setIndustry(item.id)} style={[styles.card, preferences.industry === item.id && styles.selected]}><Ionicons name={item.icon} size={22} color={colors.primary} /><Text style={styles.cardTitle}>{item.label}</Text></Pressable>)}</View><PrimaryButton fullWidth disabled={!selected} label="Continue" onPress={next} /></Screen>;
  if (step === 3) return <Screen><Header step={2} /><Text style={styles.title}>What is your business called?</Text><Text style={styles.copy}>This is the name customers will recognise.</Text><TextInput accessibilityLabel="Business name" value={name} onChangeText={setName} placeholder="Business name" placeholderTextColor={colors.textSecondary} style={styles.input} /><PrimaryButton fullWidth disabled={!name.trim() || saving} label={saving ? 'Saving…' : 'Continue'} onPress={() => void saveBusiness({ name: name.trim(), industry: preferences.industry })} /></Screen>;
  if (step === 4) return <Screen><Header step={3} /><Text style={styles.title}>What number should customers reach?</Text><Text style={styles.copy}>Use the business number you want associated with customer follow-up.</Text><CountryPhoneInput label="Business phone" value={phone} onChange={setPhone} /><PrimaryButton fullWidth disabled={phone.length < 7 || saving} label={saving ? 'Saving…' : 'Continue'} onPress={() => void saveBusiness({ phone })} /></Screen>;
  if (step === 5) return <Screen><Header step={4} /><Text style={styles.title}>When are you open?</Text><Text style={styles.copy}>Chakusa uses this so automatic follow-up never goes out outside your hours.</Text><TextInput accessibilityLabel="Business hours" value={hours} onChangeText={setHours} placeholder="Mon-Sat, 9:00 AM-6:00 PM" placeholderTextColor={colors.textSecondary} style={styles.input} /><PrimaryButton fullWidth disabled={!hours.trim() || saving} label={saving ? 'Saving…' : 'Continue'} onPress={() => void saveBusiness({ workingHours: { summary: hours.trim() } })} /></Screen>;
  if (step === 6) return <Screen><Header step={5} /><Text style={styles.title}>What's your team size?</Text><Text style={styles.copy}>This helps Chakusa recommend the right plan as you grow.</Text><View style={styles.list}>{TEAM_SIZES.map(item => <Pressable key={item.id} accessibilityRole="radio" accessibilityState={{ checked: preferences.teamSize === item.id }} onPress={() => preferences.setTeamSize(item.id)} style={[styles.row, preferences.teamSize === item.id && styles.selected]}><Text style={styles.cardTitle}>{item.label}</Text>{preferences.teamSize === item.id ? <Ionicons name="checkmark-circle" size={20} color={colors.success} /> : null}</Pressable>)}</View><PrimaryButton fullWidth disabled={!preferences.teamSize} label="Continue" onPress={next} /></Screen>;
  if (step === 7) return <Screen><Header step={6} /><Text style={styles.title}>Choose your services</Text><Text style={styles.copy}>Start with suggestions for your business. You can change these later.</Text><View style={styles.grid}>{(selected?.services ?? []).map(service => { const active = services.includes(service); return <Pressable key={service} accessibilityRole="checkbox" accessibilityState={{ checked: active }} onPress={() => setServices(value => active ? value.filter(item => item !== service) : [...value, service])} style={[styles.card, active && styles.selected]}><Text style={styles.cardTitle}>{service}</Text><Ionicons name={active ? 'checkmark-circle' : 'add-circle-outline'} size={20} color={active ? colors.success : colors.textSecondary} /></Pressable>; })}</View><PrimaryButton fullWidth disabled={!services.length || saving} label={saving ? 'Saving…' : 'Continue'} onPress={() => void saveBusiness({ defaultServices: services })} /></Screen>;
  if (step === 8) return <Screen><Header step={7} /><Text style={styles.title}>What's costing you the most right now?</Text><Text style={styles.copy}>Chakusa will focus on this first. You can pick more than one.</Text><View style={styles.list}>{GOALS.map(goal => { const active = preferences.goals.includes(goal); return <Pressable key={goal} accessibilityRole="checkbox" accessibilityState={{ checked: active }} onPress={() => preferences.setGoals(toggleGoal(preferences.goals, goal))} style={[styles.row, active && styles.selected]}><View style={styles.goalCopy}><Text style={styles.cardTitle}>{GOAL_COPY[goal].label}</Text><Text style={styles.body}>{GOAL_COPY[goal].detail}</Text></View><Ionicons name={active ? 'checkmark-circle' : 'add-circle-outline'} size={20} color={active ? colors.success : colors.textSecondary} /></Pressable>; })}</View><PrimaryButton fullWidth disabled={!preferences.goals.length} label="Continue" onPress={next} /></Screen>;
  if (step === 9) return <Screen><Header step={8} /><View style={styles.hero}><Ionicons name="star-outline" size={42} color={colors.primary} /></View><Text style={styles.title}>Grow your reputation</Text><Text style={styles.copy}>Paste the Google review link customers should open. Chakusa will use this exact link in review requests.</Text><TextInput accessibilityLabel="Google review link" autoCapitalize="none" autoCorrect={false} keyboardType="url" value={reviewLink} onChangeText={setReviewLink} placeholder="https://g.page/r/.../review" placeholderTextColor={colors.textSecondary} style={styles.input} /><PrimaryButton fullWidth disabled={!/^https:\/\//i.test(reviewLink.trim()) || saving} label={saving ? 'Saving…' : 'Save review link'} onPress={() => void saveBusiness({ googleReviewLink: reviewLink.trim() })} /><SecondaryButton fullWidth disabled={saving} label="Skip for now" onPress={next} /></Screen>;
  if (step === 10) return <Screen><Header step={9} /><View style={styles.hero}><Ionicons name="shield-checkmark-outline" size={42} color={colors.success} /></View><Text style={styles.title}>Your Recovery Engine</Text><Text style={styles.copy}>Chakusa will show the engine’s real activation status and any required permissions as they become available.</Text><PrimaryButton fullWidth label="Continue" onPress={next} /></Screen>;
  return <Screen><View style={styles.success}><View style={styles.successIcon}><Ionicons name="checkmark" size={38} color={colors.surface} /></View><Text style={styles.title}>Your business is ready.</Text><Text style={styles.copy}>Your dashboard will guide you to the next meaningful action.</Text><PrimaryButton fullWidth label="Go to dashboard" onPress={() => preferences.completeOnboarding()} /></View></Screen>;
}
function Header({ step }: { step: number }) { return <Text style={styles.kicker}>SETUP · {step} OF 9</Text>; }
const styles = StyleSheet.create({ welcome: { minHeight: 620, justifyContent: 'center', gap: spacing.lg }, auth: { gap: spacing.lg, paddingTop: spacing.xxl }, kicker: { ...typography.micro, color: colors.primary, letterSpacing: 1 }, title: { ...typography.title, color: colors.text }, copy: { ...typography.body, color: colors.textSecondary }, body: { ...typography.body, color: colors.textSecondary }, grid: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm }, list: { gap: spacing.sm }, card: { width: '48%', minHeight: 80, borderWidth: 1, borderColor: colors.border, borderRadius: radius.lg, padding: spacing.md, backgroundColor: colors.surface, justifyContent: 'space-between', gap: spacing.sm }, row: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', minHeight: 64, borderWidth: 1, borderColor: colors.border, borderRadius: radius.lg, padding: spacing.md, backgroundColor: colors.surface, gap: spacing.sm }, goalCopy: { flex: 1, gap: spacing.xs }, selected: { borderColor: colors.primary, backgroundColor: colors.primarySoft }, cardTitle: { ...typography.bodyStrong, color: colors.text }, input: { minHeight: 54, backgroundColor: colors.surface, borderRadius: radius.md, borderWidth: 1, borderColor: colors.border, paddingHorizontal: spacing.md, ...typography.body, color: colors.text }, hero: { height: 164, borderRadius: radius.xl, backgroundColor: colors.primarySoft, alignItems: 'center', justifyContent: 'center' }, success: { minHeight: 540, alignItems: 'center', justifyContent: 'center', gap: spacing.lg }, successIcon: { width: 74, height: 74, borderRadius: 37, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.success } });
