import { useEffect } from 'react';
import { Linking, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { PublicPage, publicPageTitle } from '../domain/publicRoutes';
import { colors, radius, spacing, typography } from '../theme';

type Section = { title: string; paragraphs?: string[]; bullets?: string[] };
const effective = 'Effective date: August 18, 2026';
const privacy: Section[] = [
  { title: '1. About Chakusa', paragraphs: ['Chakusa is an independent software service operated under the Chakusa name.', 'Chakusa provides customer-recovery and relationship-management tools for businesses, including lead management, customer records, review requests, private feedback, comeback reminders, messaging tools, notifications, analytics, and automation features where available.', 'For privacy questions or requests, contact support@chakusa.com. Website: https://chakusa.com.'] },
  { title: '2. Scope', paragraphs: ['This Privacy Policy explains how Chakusa collects, uses, stores, shares, and protects personal information when people use the Chakusa mobile application, website, public feedback pages, and related services. It also explains the choices and rights available to users.', "Businesses using Chakusa may enter information about their own customers. Where applicable, the business determines why it uses that customer information and Chakusa processes the information to provide the service on the business's behalf."] },
  { title: '3. Information we collect', paragraphs: ['Depending on how Chakusa is used, we may process the following categories of information.'], bullets: ['Account information: name, email address, authentication information, account identifiers, linked sign-in provider information, and session and security information.', 'Business information: business name, industry, country, phone number, services, Google review link, follow-up preferences, and notification preferences where available.', 'Customer information entered by a business: customer name, phone number, email address where provided, service information, lead history, review-request history, reminder history, feedback, and customer activity.', 'Lead and recovery information: lead source and status, requested service, estimated value, response information, booking and outcome information, and recovered revenue information.', 'Review and feedback information: review requests and status, ratings, private comments or feedback, service context, and public feedback-link state.', 'Messaging information: message content generated or stored in Chakusa, recipient phone number, message type, delivery/provider information where available, and automated messaging activity where enabled.', 'Missed-call detection information (Android, optional): for Android users who enable Chakusa’s Recovery Engine, the phone number and timestamp of a missed call, used only to create a lead. Chakusa does not access call recordings, call audio, or call history through this feature.', 'Contacts permission (Android, optional): where a user grants contacts access, Chakusa uses it only so the Android operating system will also screen missed calls from numbers already saved as a contact. Chakusa does not read, store, upload, or otherwise use the address book beyond this system-level check.', 'Device and technical information: device platform, push-notification token, application version, basic request and security information, IP address where required for security, fraud prevention, abuse protection, or rate limiting, and error and diagnostic information where monitoring is enabled.', 'Subscription and usage information: Free or Pro plan, subscription status, feature entitlement state, product usage and applicable limits, and purchase or transaction information provided by Apple or Google when paid purchasing becomes available.'], },
  { title: 'Payment information', paragraphs: ['We do not intentionally request payment-card details directly inside Chakusa. When store-based subscriptions become available, payment processing will be handled through the applicable app store or approved payment provider.'] },
  { title: '4. How we use information', bullets: ['Create and secure accounts.', 'Provide Chakusa features.', 'Manage businesses, customers, leads, reviews, feedback, and reminders.', 'Generate customer follow-up messages.', 'Provide notifications, messaging, and automation features where enabled.', 'Calculate product usage and recovered-revenue information.', 'Provide customer support.', 'Detect fraud, abuse, and security incidents.', 'Maintain service reliability and enforce plan and usage rules.', 'Comply with applicable legal obligations and improve Chakusa based on product usage and performance.'], paragraphs: ['We do not sell personal information.'] },
  { title: '5. Business customer data', paragraphs: ['Businesses using Chakusa are responsible for ensuring that they have an appropriate basis to collect, upload, use, and communicate with their customers. A business should not enter personal information into Chakusa that it does not have the right to use.', 'Businesses are also responsible for complying with applicable communication, marketing, privacy, consent, and consumer-protection requirements when contacting customers.'] },
  { title: '6. Customer communications', paragraphs: ['Chakusa may help businesses prepare or, for eligible paid features, send customer communications. Free users may generate and copy messages for manual sending through their own communication applications.', 'Where provider-based messaging or automation is enabled, Chakusa may use third-party communications providers to transmit messages.', 'Businesses remain responsible for ensuring that messages they send through Chakusa are lawful, expected, and appropriately consented to. Businesses must honor customer opt-out requests and must not use Chakusa to send spam, unlawful marketing, harassment, deceptive communications, or prohibited content.'] },
  { title: '7. Review requests and private feedback', paragraphs: ["Businesses may send customers secure Chakusa links to provide ratings or private feedback. These links use opaque security tokens and are designed not to expose internal business or customer identifiers.", "A business's Google review option may also be displayed when configured. Chakusa does not condition access to the Google review option on whether a customer gives a positive or negative rating."] },
  { title: '8. Automation', paragraphs: ['Eligible Chakusa features may automate actions such as customer follow-up. Businesses are responsible for enabling and configuring automation appropriately and for ensuring that automated communications comply with applicable laws and customer consent requirements.', 'Chakusa may stop automated execution when a subscription expires, is canceled, or otherwise loses the required entitlement.'] },
  { title: '9. Third-party service providers', paragraphs: ['Chakusa may rely on third-party providers to operate the service. Depending on the feature used, these may include providers for:'], bullets: ['Cloud hosting and databases.', 'Authentication.', 'Push notifications.', 'Communications and SMS delivery.', 'Email delivery.', 'Application monitoring.', 'Apple App Store services.', 'Google Play services.'], },
  { title: 'Provider processing', paragraphs: ['For example, where Twilio messaging is enabled, customer phone numbers and message content may be processed by Twilio to deliver communications. Third-party providers process information according to their own contracts, privacy terms, and applicable law. The production list of service providers may change as Chakusa infrastructure develops.'] },
  { title: '10. Push notifications', paragraphs: ['Chakusa may send push notifications for relevant business events. Users can control operating-system notification permission through their device settings. Where Chakusa offers in-app notification preferences, the exact effect of those preferences will be described in the application.'] },
  { title: '11. Public feedback links', paragraphs: ['Public feedback pages may be accessed without creating a Chakusa account. Chakusa limits the information displayed through these links to information needed to complete the feedback experience, such as the business name, service context, feedback state, and configured review option.', 'Public tokens should not be shared unnecessarily.'] },
  { title: '12. Security', paragraphs: ['Chakusa uses technical and organizational measures intended to protect information, including authentication controls, tenant separation, secure session handling, access controls, rate limiting, hashed security tokens, and encrypted transport in production.', 'No internet service can guarantee absolute security. Users are responsible for protecting their account credentials and devices.'] },
  { title: '13. Data retention', paragraphs: ['We retain information for as long as reasonably necessary to provide Chakusa, maintain security, comply with legal obligations, resolve disputes, and enforce agreements.', "When an account is deleted, Chakusa deletes account and associated business data through the service's account-deletion process, subject to information that may need to be retained temporarily in backups, security records, transaction records, or where required by law.", 'Retention periods may vary according to the type of information and applicable legal requirements.'] },
  { title: '14. Account deletion', paragraphs: ['Users can request account deletion from within the Chakusa application. Users may also review deletion instructions at https://chakusa.com/delete-account or contact support@chakusa.com.', 'Account deletion is separate from canceling an App Store or Google Play subscription. If a user has an active store subscription when deletion occurs, the user may need to cancel that subscription through the applicable store to stop future renewals.'] },
  { title: '15. Data rights', paragraphs: ['Depending on where a person lives, they may have rights relating to personal information, which can include rights to:'], bullets: ['Request access or correction.', 'Request deletion.', 'Object to or restrict certain processing.', 'Request portability.', 'Withdraw consent where processing relies on consent.'], },
  { title: 'Rights requests', paragraphs: ['Requests can be sent to support@chakusa.com. We may need to verify identity before fulfilling certain requests. If the information is controlled by a business using Chakusa, the individual may need to contact that business directly.'] },
  { title: '16. International processing', paragraphs: ['Chakusa is designed for businesses in multiple countries. Information may therefore be processed in countries other than the country where the user or customer is located. Where required, appropriate safeguards will be used for international transfers of personal information.'] },
  { title: '17. Children', paragraphs: ["Chakusa is designed for businesses and is not intended for children to create or operate business accounts. We do not knowingly design the service to collect children's personal information for consumer use."] },
  { title: '18. Changes to this Privacy Policy', paragraphs: ['We may update this Privacy Policy when Chakusa changes or when legal requirements change. The updated version will show a revised effective date. Material changes may also be communicated through the application or website where appropriate.'] },
  { title: '19. Contact', paragraphs: ['For privacy questions or requests: support@chakusa.com. Website: https://chakusa.com.'] },
];

const terms: Section[] = [
  { title: '1. Acceptance', paragraphs: ['These Terms of Use govern access to and use of Chakusa. Chakusa is an independent software service operated under the Chakusa name.', 'By creating an account, accessing Chakusa, or using the service, you agree to these Terms and the Privacy Policy. If you use Chakusa on behalf of a business, you confirm that you have authority to use the service for that business.'] },
  { title: '2. The service', paragraphs: ['Chakusa provides software tools designed to help businesses manage customer recovery and follow-up activities. Features may change as Chakusa develops.'], bullets: ['Lead management and missed-call recovery.', 'Customer records.', 'Review requests and private feedback.', 'Comeback reminders.', 'Message preparation and notifications.', 'Analytics, provider-based messaging, automation, and subscription features where available.'] },
  { title: '3. Account responsibility', bullets: ['Provide accurate account information.', 'Protect login credentials and maintain control of authorized devices.', 'Accept responsibility for activity performed through your account.', 'Keep business information current.', 'Notify support if you reasonably believe your account has been compromised.'] },
  { title: '4. Business and customer data', paragraphs: ['You retain responsibility for the business and customer information you submit to Chakusa. You represent that you have the lawful right to collect, use, store, and process information you enter into the service.', 'You must not use Chakusa to obtain, store, or process personal information unlawfully.'] },
  { title: '5. Customer communications', paragraphs: ['Chakusa may assist you in preparing or sending communications to customers.'], bullets: ['Communications must be lawful.', 'Customers must have provided any consent required by applicable law.', 'Sender-identification requirements must be followed.', 'Opt-out requests must be respected.', 'Marketing and promotional rules must be followed.'], },
  { title: 'Prohibited communications', paragraphs: ['You may not use Chakusa to send spam, harassment, fraudulent messages, deceptive content, illegal material, or communications prohibited by applicable messaging providers or law.'] },
  { title: '6. Reviews and feedback', paragraphs: ['Chakusa may help businesses request reviews and collect private feedback. You must not manipulate, fabricate, purchase, or improperly suppress genuine customer reviews, or use Chakusa to misrepresent customer sentiment.', 'Where Chakusa provides both private feedback and a public review option, users must not configure or use the service in a manner intended to deceptively prevent dissatisfied customers from accessing legitimate public review options.'] },
  { title: '7. Free service', paragraphs: ['Chakusa may offer a Free plan with usage limits on customers, leads, review requests, reminders, templates, or other resources. Current limits are displayed in the application and may change as the product evolves.', 'Existing data will not be intentionally removed merely because a user reaches a Free-plan usage limit.'] },
  { title: '8. Chakusa paid plans', paragraphs: ['Chakusa may offer Pro and Business plans. Current pricing, currency, taxes, promotional pricing, introductory offers, and availability are displayed by the applicable store or purchasing platform before purchase.', 'A marketing or informational price displayed outside checkout is not a guarantee of the final localized store price.'], bullets: ['Removal of applicable Free resource limits.', 'Provider-based outbound messaging.', 'Automation.', 'Additional templates.', 'Team capabilities where included in the selected plan.', 'Other paid capabilities described in the application.'], },
  { title: 'Feature availability', paragraphs: ['Feature availability may depend on subscription status, supported countries, provider availability, configuration, and technical requirements.'] },
  { title: '9. Subscriptions', paragraphs: ['When paid subscriptions become available, subscription-specific terms shown at checkout form part of these Terms. If a subscription is described as auto-renewing, it will continue for successive billing periods unless canceled according to the applicable store or purchasing platform’s rules.', 'Before purchase, Chakusa will display or make available material subscription information including plan name, billing period, localized price, key included features, automatic renewal information, cancellation information, and links to these Terms and the Privacy Policy.', 'Apple App Store and Google Play purchases are also subject to the applicable store’s terms.'] },
  { title: '10. Free trials and introductory offers', paragraphs: ['Chakusa may offer trials or introductory offers in the future. If offered, the duration, eligibility, renewal price, conversion terms, and cancellation requirements will be disclosed before enrollment. No trial is guaranteed unless it is shown in the applicable purchase offer.'] },
  { title: '11. Cancellation', paragraphs: ['Users may cancel an auto-renewing subscription through the platform through which the subscription was purchased. Cancellation normally stops future renewal but does not necessarily end access immediately. Access may continue through the paid billing period, subject to the purchasing platform’s rules.', 'Deleting a Chakusa account does not automatically guarantee cancellation of a subscription managed by Apple or Google. Users should cancel an active store subscription separately where required.'] },
  { title: '12. Restore purchases', paragraphs: ['Where required by the applicable platform, Chakusa will provide functionality to restore eligible purchases once store purchasing is enabled.'] },
  { title: '13. Refunds', paragraphs: ['Refund eligibility for purchases made through Apple or Google is generally determined under the applicable store’s policies and applicable law. Chakusa does not promise refunds outside rights provided by law or the purchasing platform.'] },
  { title: '14. Messaging and provider usage', paragraphs: ['Some paid functionality may depend on third-party communications providers. Messaging can create variable third-party costs depending on destination, message type, country, provider, and message volume.', 'Chakusa may in the future include a defined amount of provider usage with a subscription and may charge separately for additional usage, top-ups, or approved overages. No specific allowance, top-up price, or overage rate applies unless clearly displayed and accepted as part of the relevant product offer.'] },
  { title: '15. Automation', paragraphs: ['Automation can perform actions without requiring the user to manually initiate each action.'], bullets: ['Configure automation correctly.', 'Review message content.', 'Maintain accurate customer contact information.', 'Ensure recipients may lawfully receive communications.', 'Disable automation when it should no longer operate.'], },
  { title: 'Automation availability', paragraphs: ['Chakusa may disable automation where a subscription is no longer entitled, a provider is unavailable, security or abuse concerns arise, customer opt-out information requires blocking a send, or applicable legal or provider requirements require it.'] },
  { title: '16. Acceptable use', bullets: ['Do not violate law, infringe rights, send unlawful spam, harass or threaten people, or impersonate others.', 'Do not distribute malware, attempt unauthorized access, bypass usage or subscription controls, or probe or disrupt Chakusa infrastructure.', 'Do not abuse public feedback links, manipulate customer reviews, or exploit or reverse engineer protected portions of the service except where permitted by law.'] },
  { title: '17. Suspension', paragraphs: ['Chakusa may restrict or suspend access when reasonably necessary to protect users, prevent abuse or fraud, respond to security threats, enforce these Terms, comply with legal requirements, or protect third-party messaging or infrastructure services.', 'Where practical, we will attempt to resolve legitimate account issues fairly.'] },
  { title: '18. Third-party services', paragraphs: ['Chakusa relies on third-party platforms and service providers. Certain functionality may depend on internet connectivity, mobile operating systems, app stores, messaging providers, authentication providers, hosting infrastructure, and external review platforms.', 'Chakusa does not control the availability or policies of third-party services.'] },
  { title: '19. Intellectual property', paragraphs: ['Chakusa and its software, branding, interfaces, designs, and original service content are protected by applicable intellectual-property laws. These Terms give you a limited right to use Chakusa for its intended purpose and do not transfer ownership of Chakusa software or branding.', 'You retain rights in business and customer data that you lawfully provide to the service.'] },
  { title: '20. Service availability', paragraphs: ['We aim to provide a reliable service, but Chakusa may occasionally be unavailable due to maintenance, network failures, third-party failures, security incidents, updates, or circumstances outside reasonable control. We do not guarantee uninterrupted or error-free operation.'] },
  { title: '21. Business decisions', paragraphs: ['Chakusa provides software tools and operational information. It does not guarantee additional revenue, bookings, customer responses, positive reviews, customer retention, successful message delivery, or specific business outcomes.', 'Recovered-revenue figures and similar analytics depend on information recorded in the service.'] },
  { title: '22. Disclaimer', paragraphs: ['To the extent permitted by applicable law, Chakusa is provided on an “as available” basis. Nothing in these Terms excludes rights or warranties that cannot legally be excluded.'] },
  { title: '23. Limitation of liability', paragraphs: ['To the maximum extent permitted by applicable law, Chakusa will not be liable for indirect, incidental, special, consequential, or similar losses arising from use of the service, including loss caused by user-configured messaging, inaccurate customer information, third-party providers, or business decisions based on service data.', 'Nothing in these Terms limits liability where limitation is prohibited by applicable law.'] },
  { title: '24. Account deletion', paragraphs: ['Users may request account deletion through the Chakusa application. Deletion information is also available at https://chakusa.com/delete-account.', 'Account deletion may permanently remove business data associated with the account. Users should export or retain information they are legally required to keep before requesting deletion where applicable. Store subscriptions may need to be canceled separately.'] },
  { title: '25. Privacy', paragraphs: ['Use of Chakusa is also governed by the Privacy Policy: https://chakusa.com/privacy.'] },
  { title: '26. Changes to the service or Terms', paragraphs: ['We may modify Chakusa as the product develops and update these Terms when features, commercial arrangements, or legal requirements change. If changes are material, we may provide reasonable notice through the service or website.', 'Continued use after updated Terms become effective constitutes acceptance where permitted by law.'] },
  { title: '27. Termination', paragraphs: ['Users may stop using Chakusa at any time. Sections that by their nature should survive termination, including provisions relating to intellectual property, responsibility for prior conduct, disclaimers, and liability, continue to apply where legally appropriate.'] },
  { title: '28. Applicable law', paragraphs: ['These Terms are subject to applicable law. Nothing in these Terms removes mandatory consumer rights or other protections that apply based on a user’s jurisdiction.'] },
  { title: '29. Contact', paragraphs: ['Questions about Chakusa or these Terms can be sent to support@chakusa.com. Website: https://chakusa.com.'] },
];

const supportSections: Section[] = [{ title: 'Need help with Chakusa?', paragraphs: ['Contact support@chakusa.com.'], bullets: ['Account access.', 'Business setup.', 'Leads and customers.', 'Review requests.', 'Comeback reminders.', 'Notification issues.', 'Plan and usage questions.', 'Account deletion.', 'Technical problems.'] }, { title: 'Related information', paragraphs: ['Account deletion: https://chakusa.com/delete-account.', 'Privacy Policy: https://chakusa.com/privacy.', 'Terms of Use: https://chakusa.com/terms.'] }, { title: 'Important', paragraphs: ['When contacting support, do not send passwords, authentication tokens, payment credentials, or unnecessary customer personal information.'] }];
const deletionSections: Section[] = [{ title: 'Delete your account in the app', paragraphs: ['The existing authenticated in-app flow is the primary self-service deletion method.'], bullets: ['Open Chakusa.', 'Open Settings.', 'Go to Danger Zone.', 'Select Delete Account.', 'Complete the required identity confirmation.', 'Confirm deletion.'] }, { title: 'If you cannot access the application', paragraphs: ['Request help at support@chakusa.com. Please contact us from the email address associated with your Chakusa account where possible.', 'For security, we may need to verify that you are the account owner before processing a deletion request. Never send your password or authentication token.'] }, { title: 'What deletion affects', paragraphs: ['Deleting your Chakusa account may permanently remove your account, business information, and associated business data from the active service.', 'Some information may be retained where reasonably necessary for security, fraud prevention, transaction records, backups, dispute resolution, or legal obligations.'] }, { title: 'Important for paid subscriptions', paragraphs: ['Deleting a Chakusa account is separate from canceling a subscription billed through Apple App Store or Google Play. If you have an active store subscription, cancel it through the applicable store to prevent future renewals.'] }];

const configs = {
  privacy: { heading: 'CHAKUSA PRIVACY POLICY', meta: effective, sections: privacy },
  terms: { heading: 'CHAKUSA TERMS OF USE', meta: effective, sections: terms },
  support: { heading: 'CHAKUSA SUPPORT', meta: 'Public support information', sections: supportSections },
  'delete-account': { heading: 'DELETE YOUR CHAKUSA ACCOUNT', meta: 'Public account-deletion instructions', sections: deletionSections },
} as const;

export function PublicDocumentScreen({ page }: { page: PublicPage }) {
  const config = configs[page];
  useEffect(() => { if (typeof document !== 'undefined') document.title = publicPageTitle(page); }, [page]);
  return <SafeAreaView style={styles.page}><ScrollView contentContainerStyle={styles.scroll}><View style={styles.document}><Text style={styles.brand}>CHAKUSA</Text><Text accessibilityRole="header" style={styles.title}>{config.heading}</Text><Text style={styles.meta}>{config.meta}</Text><View style={styles.rule} />{config.sections.map(section => <View key={section.title} style={styles.section}><Text accessibilityRole="header" style={styles.heading}>{section.title}</Text>{section.paragraphs?.map(paragraph => <Text key={paragraph} style={styles.body}>{paragraph}</Text>)}{section.bullets ? <View style={styles.list}>{section.bullets.map(item => <View key={item} style={styles.listRow}><Text style={styles.bullet}>•</Text><Text style={styles.listText}>{item}</Text></View>)}</View> : null}</View>)}{page === 'support' || page === 'delete-account' ? <Link href="mailto:support@chakusa.com" label="Email support@chakusa.com" primary /> : null}<Footer /></View></ScrollView></SafeAreaView>;
}
function Link({ href, label, primary = false }: { href: string; label: string; primary?: boolean }) { return <Pressable accessibilityRole="link" accessibilityLabel={label} onPress={() => void Linking.openURL(href)} style={({ pressed }) => [styles.linkButton, primary && styles.primary, pressed && styles.pressed]}><Text style={[styles.linkText, primary && styles.primaryText]}>{label}</Text></Pressable>; }
function Footer() { return <View style={styles.footer}><View style={styles.footerLinks}><Link href="https://chakusa.com/privacy" label="Privacy" /><Link href="https://chakusa.com/terms" label="Terms" /><Link href="https://chakusa.com/support" label="Support" /><Link href="https://chakusa.com/delete-account" label="Delete Account" /></View><Text style={styles.copyright}>© Chakusa</Text></View>; }
const styles = StyleSheet.create({ page: { flex: 1, backgroundColor: colors.background }, scroll: { padding: spacing.lg }, document: { width: '100%', maxWidth: 780, alignSelf: 'center', backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, borderRadius: radius.xl, padding: spacing.xxl }, brand: { ...typography.micro, color: colors.primary, letterSpacing: 2, marginBottom: spacing.md }, title: { ...typography.title, color: colors.text }, meta: { ...typography.caption, color: colors.textSecondary, marginTop: spacing.xs }, rule: { height: 1, backgroundColor: colors.divider, marginVertical: spacing.xl }, section: { gap: spacing.sm, marginBottom: spacing.xl }, heading: { ...typography.heading, color: colors.text }, body: { ...typography.body, color: colors.textSecondary }, list: { gap: spacing.sm }, listRow: { flexDirection: 'row', alignItems: 'flex-start', gap: spacing.sm }, bullet: { ...typography.body, color: colors.primary }, listText: { ...typography.body, color: colors.textSecondary, flex: 1 }, linkButton: { minHeight: 44, justifyContent: 'center', paddingHorizontal: spacing.sm, borderRadius: radius.sm }, linkText: { ...typography.bodyStrong, color: colors.primary }, primary: { backgroundColor: colors.primary, alignItems: 'center', marginBottom: spacing.xl }, primaryText: { color: colors.surface }, pressed: { opacity: 0.7 }, footer: { borderTopWidth: 1, borderTopColor: colors.divider, paddingTop: spacing.xl, gap: spacing.lg }, footerLinks: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm }, copyright: { ...typography.caption, color: colors.textSecondary } });
