import { Ionicons } from '@expo/vector-icons';
import { useCallback, useEffect, useState } from 'react';
import { ActivityIndicator, Pressable, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { ApiError } from '../services/api';
import { PublicBookingDetails, publicBusinessProfileApi } from '../services/publicBusinessProfile';
import { colors, radius, shadows, spacing, typography } from '../theme';

export function PublicBookingManagementScreen({ slug, token }: { slug: string | null; token: string | null }) {
  const [booking, setBooking] = useState<PublicBookingDetails | null>(null); const [busy, setBusy] = useState(true); const [error, setError] = useState<string | null>(null);
  const load = useCallback(async () => { if (!slug || !token) { setError('This booking link is invalid.'); setBusy(false); return; } setBusy(true); try { setBooking(await publicBusinessProfileApi.getBooking(slug, token)); setError(null); } catch { setError('This booking link is invalid or expired.'); } finally { setBusy(false); } }, [slug, token]);
  useEffect(() => { void load(); }, [load]);
  const cancel = async () => { if (!slug || !token || busy) return; setBusy(true); try { setBooking(await publicBusinessProfileApi.cancelBooking(slug, token)); setError(null); } catch (caught) { setError(caught instanceof ApiError ? caught.message : 'Could not cancel this booking.'); } finally { setBusy(false); } };
  return <SafeAreaView style={styles.page}><View style={styles.shell}><Text style={styles.brand}>CHAKUSA</Text><View style={styles.card}>{busy && !booking ? <ActivityIndicator color={colors.primary} /> : error && !booking ? <State icon="link-outline" title={error} /> : booking ? <><State icon={booking.status === 'CANCELED' ? 'close-circle-outline' : 'calendar-outline'} title={booking.business.name} /><Text style={styles.service}>{booking.serviceName}</Text><Text style={styles.when}>{new Date(booking.startsAt).toLocaleString()}</Text>{booking.assignedMember ? <Text style={styles.meta}>With {booking.assignedMember.user.fullName}</Text> : null}<Text style={styles.status}>{booking.status === 'CANCELED' ? 'Canceled' : booking.status[0] + booking.status.slice(1).toLowerCase()}</Text>{['SCHEDULED', 'CONFIRMED'].includes(booking.status) ? <Pressable accessibilityRole="button" disabled={busy} onPress={() => void cancel()} style={styles.cancel}><Text style={styles.cancelText}>{busy ? 'Canceling…' : 'Cancel appointment'}</Text></Pressable> : null}{error ? <Text accessibilityRole="alert" style={styles.error}>{error}</Text> : null}</> : null}</View><Text style={styles.footer}>Powered by Chakusa</Text></View></SafeAreaView>;
}
function State({ icon, title }: { icon: keyof typeof Ionicons.glyphMap; title: string }) { return <View style={styles.state}><Ionicons name={icon} size={44} color={colors.primary} /><Text style={styles.title}>{title}</Text></View>; }
const styles = StyleSheet.create({ page: { flex: 1, backgroundColor: colors.background }, shell: { flex: 1, width: '100%', maxWidth: 520, alignSelf: 'center', justifyContent: 'center', padding: spacing.lg }, brand: { ...typography.micro, color: colors.primary, letterSpacing: 2, textAlign: 'center', marginBottom: spacing.md }, card: { gap: spacing.md, padding: spacing.xxl, borderRadius: radius.xl, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface, ...shadows.card }, state: { alignItems: 'center', gap: spacing.sm }, title: { ...typography.title, color: colors.text, textAlign: 'center' }, service: { ...typography.heading, color: colors.text, textAlign: 'center' }, when: { ...typography.bodyStrong, color: colors.text, textAlign: 'center' }, meta: { ...typography.body, color: colors.textSecondary, textAlign: 'center' }, status: { ...typography.caption, color: colors.primary, textAlign: 'center', textTransform: 'uppercase' }, cancel: { minHeight: 50, alignItems: 'center', justifyContent: 'center', borderRadius: radius.md, backgroundColor: colors.negativeSoft }, cancelText: { ...typography.bodyStrong, color: colors.negative }, error: { ...typography.caption, color: colors.negative, textAlign: 'center' }, footer: { ...typography.caption, color: colors.textSecondary, textAlign: 'center', marginTop: spacing.lg } });
