import { useNavigation } from '@react-navigation/native';
import { NativeStackNavigationProp } from '@react-navigation/native-stack';
import { useEffect, useMemo, useState } from 'react';
import { Modal, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { ReviewStatus } from '../apiTypes';
import { AppHeader, EmptyState, ErrorState, FilterTabs, IconButton, LoadingState, MetricCard, PrimaryButton, ReviewCard, Screen, SecondaryButton } from '../components/ui';
import { ApiError } from '../services/api';
import { reviewsApi } from '../services/endpoints';
import { useAppState } from '../state/AppContext';
import { colors, radius, spacing, typography } from '../theme';
import { RootStackParamList } from '../types';

const filters = ['all', 'pending', 'sent', 'opened', 'reviewed', 'feedback_received'] as const;
export function ReviewsScreen() {
  const navigation = useNavigation<NativeStackNavigationProp<RootStackParamList>>(); const { reviews, feedback, customers, state, loadReviews, loadFeedback, loadCustomers } = useAppState(); const [filter, setFilter] = useState<(typeof filters)[number]>('all'); const [creating, setCreating] = useState(false); const [customerId, setCustomerId] = useState(''); const [serviceName, setServiceName] = useState(''); const [saving, setSaving] = useState(false); const [formError, setFormError] = useState<string | null>(null);
  useEffect(() => { void Promise.all([loadReviews(), loadFeedback()]); if (!state.customers.loaded) void loadCustomers(); }, [loadCustomers, loadFeedback, loadReviews, state.customers.loaded]);
  const visible = useMemo(() => reviews.filter(review => filter === 'all' || review.status === filter as ReviewStatus), [filter, reviews]); const sentCount = reviews.filter(item => item.status !== 'pending').length; const reviewedCount = reviews.filter(item => item.status === 'reviewed').length;
  const create = async () => { if (saving) return; setSaving(true); setFormError(null); try { const review = await reviewsApi.create({ customerId: customerId || undefined, serviceName: serviceName.trim() || undefined }); setCreating(false); setServiceName(''); await loadReviews(); navigation.navigate('ReviewDetail', { reviewId: review.id }); } catch (error) { setFormError(error instanceof ApiError ? error.message : 'Unable to create review request.'); } finally { setSaving(false); } };
  return <><Screen><AppHeader title="Reviews" subtitle="Honest feedback from every customer" right={<IconButton icon="add" label="Create review request" onPress={() => setCreating(true)} />} /><View style={styles.metrics}><MetricCard label="Requests sent" value={String(sentCount)} /><MetricCard label="Reviews received" value={String(reviewedCount)} /><MetricCard label="Private feedback" value={String(feedback.length)} /></View><FilterTabs options={filters} value={filter} onChange={setFilter} />{!state.reviews.loaded && state.reviews.loading ? <LoadingState label="Loading review requests…" /> : state.reviews.error ? <ErrorState message={state.reviews.error} onRetry={() => void loadReviews()} /> : visible.length ? <View style={styles.list}>{visible.map(review => <ReviewCard key={review.id} review={review} onPress={() => navigation.navigate('ReviewDetail', { reviewId: review.id })} />)}</View> : <EmptyState title="No review requests" message="Create a request after completing a customer service." icon="star-outline" />}</Screen>
    <Modal visible={creating} transparent animationType="slide" onRequestClose={() => setCreating(false)}><Pressable style={styles.overlay} onPress={() => !saving && setCreating(false)}><Pressable style={styles.sheet} onPress={() => undefined}><Text style={styles.sheetTitle}>New review request</Text><Text style={styles.label}>Customer</Text><View style={styles.choices}>{customers.map(customer => <Pressable key={customer.id} onPress={() => setCustomerId(customer.id)} style={[styles.choice, customerId === customer.id && styles.choiceActive]}><Text style={[styles.choiceText, customerId === customer.id && styles.choiceTextActive]}>{customer.name}</Text></Pressable>)}</View><Text style={styles.label}>Service</Text><TextInput value={serviceName} onChangeText={setServiceName} style={styles.input} />{formError ? <Text style={styles.error}>{formError}</Text> : null}<PrimaryButton disabled={saving} fullWidth label={saving ? 'Creating…' : 'Create request'} onPress={() => void create()} /><SecondaryButton disabled={saving} fullWidth label="Cancel" onPress={() => setCreating(false)} /></Pressable></Pressable></Modal>
  </>;
}
const styles = StyleSheet.create({ metrics: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm }, list: { gap: spacing.sm }, overlay: { flex: 1, backgroundColor: colors.overlay, justifyContent: 'flex-end' }, sheet: { backgroundColor: colors.surface, borderTopLeftRadius: radius.xl, borderTopRightRadius: radius.xl, padding: spacing.xl, paddingBottom: 40, gap: spacing.md }, sheetTitle: { ...typography.heading, color: colors.text }, label: { ...typography.caption, color: colors.text }, input: { minHeight: 48, backgroundColor: colors.background, borderWidth: 1, borderColor: colors.border, borderRadius: radius.md, paddingHorizontal: spacing.md, ...typography.body, color: colors.text }, choices: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.xs }, choice: { minHeight: 40, justifyContent: 'center', paddingHorizontal: spacing.sm, borderRadius: radius.round, borderWidth: 1, borderColor: colors.border }, choiceActive: { borderColor: colors.primary }, choiceText: { ...typography.caption, color: colors.textSecondary }, choiceTextActive: { color: colors.primary, fontWeight: '700' }, error: { ...typography.caption, color: colors.negative } });
