import { Ionicons } from '@expo/vector-icons';
import { useCallback, useEffect, useState } from 'react';
import { Alert, Modal, Pressable, ScrollView, StyleSheet, Switch, Text, TextInput, View } from 'react-native';
import { ServiceOfferingDto, TeamMemberDto } from '../apiTypes';
import { AppHeader, EmptyState, ErrorState, LoadingState, PrimaryButton, Screen, SecondaryButton, StatusBadge } from '../components/ui';
import { ApiError } from '../services/api';
import { ServiceOfferingInput, servicesApi, teamApi } from '../services/endpoints';
import { colors, radius, shadows, spacing, typography } from '../theme';
import { formatMoney } from '../utils/format';
import { useAuth } from '../state/AuthContext';

interface Draft { name: string; description: string; category: string; sortOrder: string; duration: string; preparation: string; cleanup: string; price: string; deposit: string; active: boolean; publiclyBookable: boolean; memberIds: string[] }
const blank: Draft = { name: '', description: '', category: '', sortOrder: '0', duration: '60', preparation: '0', cleanup: '0', price: '', deposit: '', active: true, publiclyBookable: true, memberIds: [] };
const toDraft = (service: ServiceOfferingDto): Draft => ({ name: service.name, description: service.description ?? '', category: service.category ?? '', sortOrder: String(service.sortOrder), duration: String(service.durationMinutes), preparation: String(service.preparationMinutes), cleanup: String(service.cleanupMinutes), price: service.price == null ? '' : String(service.price), deposit: service.depositAmount == null ? '' : String(service.depositAmount), active: service.active, publiclyBookable: service.publiclyBookable, memberIds: service.assignments.map(item => item.businessMemberId) });

export function ServiceCatalogScreen() {
  const { business, role } = useAuth(); const [services, setServices] = useState<ServiceOfferingDto[]>([]); const [members, setMembers] = useState<TeamMemberDto[]>([]); const [loaded, setLoaded] = useState(false); const [error, setError] = useState<string | null>(null); const [editing, setEditing] = useState<ServiceOfferingDto | 'new' | null>(null); const [draft, setDraft] = useState<Draft>(blank); const [saving, setSaving] = useState(false);
  const canEdit = role === 'OWNER' || role === 'ADMIN';
  const load = useCallback(async () => { try { const [catalog, team] = await Promise.all([servicesApi.list(), teamApi.listMembers()]); setServices(catalog); setMembers(team.filter(member => member.status === 'ACTIVE')); setError(null); } catch { setError('Could not load your service catalog.'); } finally { setLoaded(true); } }, []);
  useEffect(() => { void load(); }, [load]);
  const open = (service?: ServiceOfferingDto) => { setDraft(service ? toDraft(service) : blank); setEditing(service ?? 'new'); setError(null); };
  const input = (): ServiceOfferingInput => ({ name: draft.name.trim(), description: draft.description.trim() || null, category: draft.category.trim() || null, sortOrder: Number(draft.sortOrder), durationMinutes: Number(draft.duration), preparationMinutes: Number(draft.preparation), cleanupMinutes: Number(draft.cleanup), price: draft.price ? Number(draft.price) : null, depositAmount: draft.deposit ? Number(draft.deposit) : null, active: draft.active, publiclyBookable: draft.publiclyBookable, memberIds: draft.memberIds });
  const valid = draft.name.trim() && Number(draft.sortOrder) >= 0 && Number(draft.duration) >= 5 && Number(draft.preparation) >= 0 && Number(draft.cleanup) >= 0 && (!draft.price || Number(draft.price) >= 0) && (!draft.deposit || Number(draft.deposit) >= 0) && (!draft.price || !draft.deposit || Number(draft.deposit) <= Number(draft.price));
  const save = async () => { if (!valid || saving || !editing) return; setSaving(true); setError(null); try { if (editing === 'new') await servicesApi.create(input()); else await servicesApi.patch(editing.id, input()); setEditing(null); await load(); } catch (caught) { setError(caught instanceof ApiError ? caught.message : 'Could not save this service.'); } finally { setSaving(false); } };
  const archive = (service: ServiceOfferingDto) => Alert.alert('Archive this service?', 'Existing appointments keep their service details. Customers will no longer be able to book it.', [{ text: 'Keep service', style: 'cancel' }, { text: 'Archive', style: 'destructive', onPress: () => void servicesApi.archive(service.id).then(load).catch(() => Alert.alert('Could not archive service', 'Please try again.')) }]);
  const toggleMember = (id: string) => setDraft(current => ({ ...current, memberIds: current.memberIds.includes(id) ? current.memberIds.filter(value => value !== id) : [...current.memberIds, id] }));
  return <><Screen><AppHeader eyebrow="BUSINESS SETUP" title="Services" subtitle="Control duration, pricing, booking availability, and who can provide each service." />
    {!loaded ? <LoadingState label="Loading services…" /> : error && !services.length ? <ErrorState message={error} onRetry={() => void load()} /> : !services.length ? <EmptyState icon="pricetag-outline" title="Add your first service" message="Services power availability, public booking, calendar timing, and deposits." /> : <View style={styles.list}>{services.map(service => <Pressable key={service.id} accessibilityRole="button" onPress={() => canEdit && open(service)} style={({ pressed }) => [styles.card, pressed && styles.pressed]}><View style={styles.cardTop}><View style={styles.serviceIcon}><Ionicons name="pricetag-outline" size={20} color={colors.primary} /></View><View style={styles.copy}><Text style={styles.name}>{service.name}</Text><Text style={styles.detail}>{service.durationMinutes} min{service.price == null ? '' : ` · ${formatMoney(service.price, business?.currency ?? 'USD')}`}</Text></View><StatusBadge label={service.active ? service.publiclyBookable ? 'Public' : 'Private' : 'Archived'} /></View>{service.description ? <Text style={styles.description}>{service.description}</Text> : null}<Text style={styles.meta}>{service.assignments.length ? `${service.assignments.length} assigned team member${service.assignments.length === 1 ? '' : 's'}` : 'Available with every active team member'}{service.preparationMinutes || service.cleanupMinutes ? ` · ${service.preparationMinutes + service.cleanupMinutes} min total buffer` : ''}</Text>{canEdit ? <View style={styles.actions}><SecondaryButton compact label="Edit" onPress={() => open(service)} /><SecondaryButton compact label="Archive" onPress={() => archive(service)} /></View> : null}</Pressable>)}</View>}
    {canEdit ? <PrimaryButton fullWidth icon="add" label="Add service" onPress={() => open()} /> : null}
  </Screen>
  <Modal visible={Boolean(editing)} transparent animationType="slide" onRequestClose={() => !saving && setEditing(null)}>
    <View style={styles.overlay}><View style={styles.sheet}><ScrollView contentContainerStyle={styles.sheetContent} keyboardShouldPersistTaps="handled" showsVerticalScrollIndicator={false}>
      <Text style={styles.sheetTitle}>{editing === 'new' ? 'New service' : 'Edit service'}</Text>
      <Text style={styles.label}>Service name</Text><TextInput accessibilityLabel="Service name" value={draft.name} onChangeText={name => setDraft(current => ({ ...current, name }))} style={styles.input} />
      <Text style={styles.label}>Description</Text><TextInput accessibilityLabel="Service description" multiline value={draft.description} onChangeText={description => setDraft(current => ({ ...current, description }))} style={[styles.input, styles.multiline]} />
      <Text style={styles.label}>Category</Text><TextInput accessibilityLabel="Service category" placeholder="e.g. Hair, Nails, Consulting" value={draft.category} onChangeText={category => setDraft(current => ({ ...current, category }))} style={styles.input} />
      <View style={styles.fields}><NumberField label="Display order" value={draft.sortOrder} onChange={sortOrder => setDraft(current => ({ ...current, sortOrder }))} /><NumberField label="Duration (min)" value={draft.duration} onChange={duration => setDraft(current => ({ ...current, duration }))} /><NumberField label="Price" value={draft.price} onChange={price => setDraft(current => ({ ...current, price }))} /><NumberField label="Deposit" value={draft.deposit} onChange={deposit => setDraft(current => ({ ...current, deposit }))} /><NumberField label="Preparation" value={draft.preparation} onChange={preparation => setDraft(current => ({ ...current, preparation }))} /><NumberField label="Cleanup" value={draft.cleanup} onChange={cleanup => setDraft(current => ({ ...current, cleanup }))} /></View>
      <Toggle label="Active" detail="Available for internal scheduling" value={draft.active} onChange={active => setDraft(current => ({ ...current, active }))} />
      <Toggle label="Public booking" detail="Customers can select this service" value={draft.publiclyBookable} onChange={publiclyBookable => setDraft(current => ({ ...current, publiclyBookable }))} />
      <Text style={styles.label}>Team members</Text><Text style={styles.helper}>Leave everyone unselected to make this service available with every active member.</Text>
      <View style={styles.members}>{members.map(member => { const selected = draft.memberIds.includes(member.id); return <Pressable key={member.id} accessibilityRole="checkbox" accessibilityState={{ checked: selected }} onPress={() => toggleMember(member.id)} style={[styles.member, selected && styles.memberSelected]}><Text style={styles.memberText}>{member.name}</Text><Ionicons name={selected ? 'checkmark-circle' : 'ellipse-outline'} size={20} color={selected ? colors.success : colors.tabInactive} /></Pressable>; })}</View>
      {error ? <Text accessibilityRole="alert" style={styles.error}>{error}</Text> : null}<PrimaryButton fullWidth disabled={!valid || saving} label={saving ? 'Saving…' : 'Save service'} onPress={() => void save()} /><SecondaryButton fullWidth disabled={saving} label="Cancel" onPress={() => setEditing(null)} />
    </ScrollView></View></View>
  </Modal></>;
}
function NumberField({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { return <View style={styles.numberField}><Text style={styles.label}>{label}</Text><TextInput accessibilityLabel={label} keyboardType="decimal-pad" value={value} onChangeText={onChange} style={styles.input} /></View>; }
function Toggle({ label, detail, value, onChange }: { label: string; detail: string; value: boolean; onChange: (value: boolean) => void }) { return <View style={styles.toggle}><View style={styles.copy}><Text style={styles.name}>{label}</Text><Text style={styles.detail}>{detail}</Text></View><Switch accessibilityLabel={label} value={value} onValueChange={onChange} trackColor={{ false: colors.border, true: colors.success }} thumbColor={colors.surface} /></View>; }
const styles = StyleSheet.create({ list: { gap: spacing.sm }, card: { padding: spacing.md, gap: spacing.sm, backgroundColor: colors.surface, borderRadius: radius.lg, borderWidth: 1, borderColor: colors.border, ...shadows.card }, cardTop: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm }, serviceIcon: { width: 42, height: 42, borderRadius: 21, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.primarySoft }, copy: { flex: 1, minWidth: 0 }, name: { ...typography.bodyStrong, color: colors.text }, detail: { ...typography.caption, color: colors.textSecondary }, description: { ...typography.body, color: colors.text }, meta: { ...typography.caption, color: colors.textSecondary }, actions: { flexDirection: 'row', gap: spacing.xs }, pressed: { opacity: .72 }, overlay: { flex: 1, justifyContent: 'flex-end', backgroundColor: colors.overlay }, sheet: { maxHeight: '94%', backgroundColor: colors.background, borderTopLeftRadius: radius.xl, borderTopRightRadius: radius.xl, overflow: 'hidden' }, sheetContent: { padding: spacing.lg, paddingBottom: spacing.xxxl, gap: spacing.sm }, sheetTitle: { ...typography.heading, color: colors.text }, label: { ...typography.caption, color: colors.text }, input: { minHeight: 48, paddingHorizontal: spacing.md, borderRadius: radius.md, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface, ...typography.body, color: colors.text }, multiline: { minHeight: 72, paddingTop: spacing.sm, textAlignVertical: 'top' }, fields: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.xs }, numberField: { width: '31%', minWidth: 96, flexGrow: 1, gap: spacing.xs }, toggle: { minHeight: 58, flexDirection: 'row', alignItems: 'center', gap: spacing.sm }, helper: { ...typography.caption, color: colors.textSecondary }, members: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.xs }, member: { minHeight: 42, flexDirection: 'row', alignItems: 'center', gap: spacing.xs, paddingHorizontal: spacing.sm, borderRadius: radius.round, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface }, memberSelected: { borderColor: colors.success }, memberText: { ...typography.caption, color: colors.text }, error: { ...typography.caption, color: colors.negative } });
