import { Ionicons } from '@expo/vector-icons';
import { useNavigation } from '@react-navigation/native';
import { NativeStackNavigationProp } from '@react-navigation/native-stack';
import { Alert, Pressable, StyleSheet, Switch, Text, View } from 'react-native';
import { AppHeader, Screen } from '../components/ui';
import { useAuth } from '../state/AuthContext';
import { AttentionPreferences, usePreferences } from '../state/PreferencesContext';
import { colors, radius, spacing, typography } from '../theme';
import { RootStackParamList } from '../types';
import { titleCase } from '../utils/format';

export function SettingsScreen() {
  const navigation = useNavigation<NativeStackNavigationProp<RootStackParamList>>();
  const { business, user, logout, logoutAll, linkGoogle } = useAuth();
  const preferences = usePreferences();
  const setPreference = (key: keyof AttentionPreferences, value: boolean) => preferences.setAttention({ ...preferences.attention, [key]: value });
  return <Screen>
    <AppHeader eyebrow="ACCOUNT" title={user?.fullName ?? 'Your account'} subtitle={user?.email} />
    <Group title="Profile"><Row icon="person-circle-outline" label="Name" value={user?.fullName ?? ''} /><Row icon="mail-outline" label="Email" value={user?.email ?? ''} last /></Group>
    <Group title="Business"><Row icon="storefront-outline" label="Business profile" value={business?.name ?? 'Not set'} onPress={() => navigation.navigate('BusinessSettings')} /><Row icon="call-outline" label="Phone and country" value={business?.phone ?? 'Not set'} onPress={() => navigation.navigate('BusinessSettings')} /><Row icon="cut-outline" label="Services" value={`${business?.defaultServices?.length ?? 0} services`} onPress={() => navigation.navigate('BusinessSettings')} /><Row icon="star-outline" label="Review link" value={business?.googleReviewLink ? 'Configured' : 'Not set'} onPress={() => navigation.navigate('BusinessSettings')} last /></Group>
    <Group title="Messaging"><Row icon="chatbubble-ellipses-outline" label="Message tone" value={titleCase(business?.preferredTone ?? 'friendly')} onPress={() => navigation.navigate('BusinessSettings')} /><Row icon="document-text-outline" label="Message templates" onPress={() => navigation.navigate('Templates')} last /></Group>
    <Group title="Follow-up"><Row icon="time-outline" label="Comeback timing" value={`${business?.reminderDays ?? 42} days`} onPress={() => navigation.navigate('BusinessSettings')} last /></Group>
    <Group title="Attention preferences"><ToggleRow icon="call-outline" label="Missed calls" value={preferences.attention.missedCalls} onChange={value => setPreference('missedCalls', value)} /><ToggleRow icon="star-outline" label="Review requests" value={preferences.attention.reviews} onChange={value => setPreference('reviews', value)} /><ToggleRow icon="refresh-outline" label="Comeback reminders" value={preferences.attention.comebacks} onChange={value => setPreference('comebacks', value)} /><ToggleRow icon="pulse-outline" label="Business activity" value={preferences.attention.businessActivity} onChange={value => setPreference('businessActivity', value)} last /></Group>
    <Group title="Security"><Row icon="shield-checkmark-outline" label="Authenticated account" value={user?.email ?? ''} /><Row icon="logo-google" label={user?.authProviders?.includes('GOOGLE') ? 'Google account linked' : 'Link Google account'} onPress={() => { void linkGoogle().then(linked => { if (linked) Alert.alert('Google account linked', 'You can now sign in to Chakusa with Google.'); }).catch(error => Alert.alert('Could not link Google', error instanceof Error ? error.message : 'Please try again.')); }} /><Row icon="log-out-outline" label="Sign out all devices" onPress={() => Alert.alert('Sign out all devices?', 'Every Chakusa session will need to sign in again.', [{ text: 'Cancel', style: 'cancel' }, { text: 'Sign out all', style: 'destructive', onPress: () => { void logoutAll().catch(error => Alert.alert('Could not sign out', error instanceof Error ? error.message : 'Please try again.')); } }])} /><Row icon="trash-outline" label="Delete account" onPress={() => navigation.navigate('DeleteAccount')} last /></Group>
    <Pressable accessibilityRole="button" onPress={() => { void logout().catch(error => Alert.alert('Could not log out', error instanceof Error ? error.message : 'Please try again.')); }} style={styles.logout}><Ionicons name="log-out-outline" size={20} color={colors.negative} /><Text style={styles.logoutText}>Log out</Text></Pressable>
  </Screen>;
}
function Group({ title, children }: { title: string; children: React.ReactNode }) { return <View><Text style={styles.groupTitle}>{title}</Text><View style={styles.group}>{children}</View></View>; }
function Row({ icon, label, value, onPress, last }: { icon: keyof typeof Ionicons.glyphMap; label: string; value?: string; onPress?: () => void; last?: boolean }) { return <Pressable disabled={!onPress} onPress={onPress} style={[styles.row, !last && styles.rowBorder]}><View style={styles.icon}><Ionicons name={icon} size={20} color={colors.textSecondary} /></View><Text style={styles.label}>{label}</Text><Text numberOfLines={1} style={styles.value}>{value}</Text>{onPress ? <Ionicons name="chevron-forward" size={18} color={colors.tabInactive} /> : null}</Pressable>; }
function ToggleRow({ icon, label, value, onChange, last }: { icon: keyof typeof Ionicons.glyphMap; label: string; value: boolean; onChange: (value: boolean) => void; last?: boolean }) { return <View style={[styles.row, !last && styles.rowBorder]}><View style={styles.icon}><Ionicons name={icon} size={20} color={colors.textSecondary} /></View><Text style={styles.label}>{label}</Text><Switch accessibilityLabel={label} value={value} onValueChange={onChange} trackColor={{ false: colors.border, true: colors.success }} thumbColor={colors.surface} /></View>; }
const styles = StyleSheet.create({ groupTitle: { ...typography.caption, color: colors.textSecondary, marginBottom: spacing.xs, paddingLeft: spacing.xxs }, group: { backgroundColor: colors.surface, borderRadius: radius.md, borderWidth: 1, borderColor: colors.border, paddingHorizontal: spacing.md }, row: { minHeight: 56, flexDirection: 'row', alignItems: 'center', gap: spacing.sm }, rowBorder: { borderBottomWidth: 1, borderBottomColor: colors.divider }, icon: { width: 28, alignItems: 'center' }, label: { ...typography.body, color: colors.text, flex: 1 }, value: { ...typography.caption, color: colors.textSecondary, maxWidth: '42%' }, logout: { minHeight: 54, borderRadius: radius.md, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, flexDirection: 'row', gap: spacing.sm, alignItems: 'center', justifyContent: 'center' }, logoutText: { ...typography.bodyStrong, color: colors.negative } });
