import { Ionicons } from '@expo/vector-icons';
import { useNavigation } from '@react-navigation/native';
import { NativeStackNavigationProp } from '@react-navigation/native-stack';
import { useState } from 'react';
import { Alert, Pressable, StyleSheet, Switch, Text, View } from 'react-native';
import appConfig from '../../app.json';
import { AppHeader, Screen } from '../components/ui';
import { SUPPORT_EMAIL, SUPPORT_URL } from '../config';
import { subscriptionPeriodCopy, subscriptionStatusLabel } from '../domain/billing';
import { formatAppVersion, supportDestination } from '../domain/trustSettings';
import { openExternalDestination } from '../services/externalDestinations';
import { useAuth } from '../state/AuthContext';
import { useBilling } from '../state/BillingContext';
import { usePlanExperience } from '../state/PlanExperienceContext';
import { AttentionPreferences, usePreferences } from '../state/PreferencesContext';
import { colors, radius, spacing, typography } from '../theme';
import { RootStackParamList } from '../types';

const support = supportDestination(SUPPORT_URL, SUPPORT_EMAIL); const expoConfig = appConfig.expo as typeof appConfig.expo & { ios?: { buildNumber?: string }; android?: { versionCode?: number } }; const version = formatAppVersion(expoConfig.version, expoConfig.ios?.buildNumber ?? expoConfig.android?.versionCode);
export function SettingsCompletionScreen() {
  const navigation = useNavigation<NativeStackNavigationProp<RootStackParamList>>(); const { business, user, role, logout, logoutAll } = useAuth(); const preferences = usePreferences(); const { plan, status, features, usage, subscription } = usePlanExperience(); const billing = useBilling(); const [sessionAction, setSessionAction] = useState<'logout'|'all'|null>(null); const owner = role === 'OWNER';
  const planLabel = plan === 'BUSINESS' ? 'Chakusa Business' : plan !== 'PRO' ? 'Free plan' : status === 'TRIALING' ? 'Pro trial' : status === 'GRACE_PERIOD' ? 'Pro — payment issue' : status === 'EXPIRED' || status === 'CANCELED' ? 'Free limits apply' : 'Chakusa Pro';
  const setPreference = (key: keyof AttentionPreferences, value: boolean) => preferences.setAttention({ ...preferences.attention, [key]: value });
  const runSessionAction = async (kind: 'logout'|'all') => { if (sessionAction) return; setSessionAction(kind); try { if (kind === 'all') await logoutAll(); else await logout(); } catch { Alert.alert('Could not log out', 'Please check your connection and try again.'); } finally { setSessionAction(null); } };
  return <Screen><AppHeader eyebrow="SETTINGS" title={user?.fullName ?? 'Your account'} subtitle={`${business?.name ?? ''}${role ? ` · ${role[0]}${role.slice(1).toLowerCase()}` : ''}`} />
    {owner ? <Group title="BUSINESS"><Row icon="storefront-outline" label="Business details" value={business?.name ?? 'Not set'} onPress={() => navigation.navigate('BusinessSettings')} /><Row icon="briefcase-outline" label="Industry" value={business?.industry ?? 'Not set'} onPress={() => navigation.navigate('BusinessSettings')} /><Row icon="flag-outline" label="Business phone" value={business?.phone ?? 'Not set'} onPress={() => navigation.navigate('BusinessSettings')} /><Row icon="cut-outline" label="Services" value={`${business?.defaultServices?.length ?? 0} configured`} onPress={() => navigation.navigate('BusinessSettings')} last /></Group> : null}
    <Group title="TEAM"><Row icon="people-outline" label="Team" value={features?.teamManagement ? 'Chakusa Business' : 'View Business'} onPress={() => navigation.navigate('Team')} last /></Group>
    <Group title="PREFERENCES"><Text style={styles.helper}>These controls change what appears in your in-app attention view on this device.</Text>{([['missedCalls','Missed calls'],['reviews','Review requests'],['comebacks','Comeback reminders'],['businessActivity','Business activity']] as const).map(([key,label], index) => <ToggleRow key={key} label={label} value={preferences.attention[key]} onChange={value => setPreference(key, value)} last={index === 3} />)}</Group>
    <Group title="SUBSCRIPTION & PLAN"><Row icon="card-outline" label="Current plan" value={planLabel} onPress={owner ? () => navigation.navigate('Pro') : undefined} />{subscription ? <Row icon="calendar-outline" label={subscriptionStatusLabel(subscription)} value={subscriptionPeriodCopy(subscription) ?? undefined} /> : null}<Row icon="flash-outline" label="Automation" value={features?.automation ? 'Available' : 'Paid feature'} onPress={() => navigation.navigate('Automation')} /><Row icon="analytics-outline" label="Usage" value={usage ? `${usage.leads.current}/${usage.leads.limit ?? '∞'} leads` : 'View'} />{owner && subscription?.provider ? <Row icon="settings-outline" label="Manage Subscription" onPress={() => void billing.manage()} /> : null}{owner ? <Row icon="sparkles-outline" label="Plans" value="Free · Pro · Business" onPress={() => navigation.navigate('Pro')} last /> : null}</Group>
    <Group title="ACCOUNT & SECURITY"><Row icon="person-circle-outline" label="Account information" value={user?.email} onPress={() => navigation.navigate('AccountInformation')} /><Row icon="exit-outline" label={sessionAction === 'logout' ? 'Logging out…' : 'Log out of this device'} disabled={Boolean(sessionAction)} onPress={() => Alert.alert('Log out of this device?', 'Your other signed-in devices will stay connected.', [{ text: 'Cancel', style: 'cancel' }, { text: 'Log out', style: 'destructive', onPress: () => void runSessionAction('logout') }])} /><Row icon="log-out-outline" label={sessionAction === 'all' ? 'Logging out…' : 'Log out of all devices'} disabled={Boolean(sessionAction)} onPress={() => Alert.alert('Log out of all devices?', 'Every Chakusa session, including this device, will need to sign in again.', [{ text: 'Cancel', style: 'cancel' }, { text: 'Log out everywhere', style: 'destructive', onPress: () => void runSessionAction('all') }])} last /></Group>
    <Group title="HELP"><Row icon="help-circle-outline" label="Help / FAQ" onPress={() => navigation.navigate('Help')} /><Row icon="chatbubble-outline" label="Contact Support" value={support ? 'Open' : 'Not configured'} onPress={() => void openExternalDestination(support, 'Contact Support')} last /></Group>
    <Group title="LEGAL"><Row icon="shield-checkmark-outline" label="Privacy Policy" onPress={() => navigation.navigate('LegalDocument', { page: 'privacy' })} /><Row icon="document-text-outline" label="Terms of Use" onPress={() => navigation.navigate('LegalDocument', { page: 'terms' })} last /></Group>
    <Group title="DANGER ZONE" destructive><Row icon="trash-outline" label="Delete Account" destructive onPress={() => navigation.navigate('DeleteAccount')} last /></Group><Group title="ABOUT"><Row icon="information-circle-outline" label="Chakusa" value={version} last /></Group>
  </Screen>;
}
function Group({ title, children, destructive = false }: { title: string; children: React.ReactNode; destructive?: boolean }) { return <View><Text style={[styles.groupTitle, destructive && styles.destructive]}>{title}</Text><View style={[styles.group, destructive && styles.dangerGroup]}>{children}</View></View>; }
function Row({ icon, label, value, onPress, last, destructive = false, disabled = false }: { icon: keyof typeof Ionicons.glyphMap; label: string; value?: string; onPress?: () => void; last?: boolean; destructive?: boolean; disabled?: boolean }) { return <Pressable accessibilityRole={onPress ? 'button' : undefined} accessibilityState={{ disabled }} accessibilityLabel={value ? `${label}, ${value}` : label} disabled={!onPress || disabled} onPress={onPress} style={({ pressed }) => [styles.row, !last && styles.rowBorder, pressed && styles.pressed, disabled && styles.disabled]}><Ionicons name={icon} size={20} color={destructive ? colors.negative : colors.textSecondary} /><Text style={[styles.label, destructive && styles.destructive]}>{label}</Text>{value ? <Text numberOfLines={1} style={styles.value}>{value}</Text> : null}{onPress ? <Ionicons name="chevron-forward" size={18} color={colors.tabInactive} /> : null}</Pressable>; }
function ToggleRow({ label, value, onChange, last }: { label: string; value: boolean; onChange: (value: boolean) => void; last?: boolean }) { return <View style={[styles.row, !last && styles.rowBorder]}><Ionicons name="notifications-outline" size={20} color={colors.textSecondary} /><Text style={styles.label}>{label}</Text><Switch accessibilityLabel={`${label} in-app attention preference`} value={value} onValueChange={onChange} trackColor={{ false: colors.border, true: colors.success }} thumbColor={colors.surface} /></View>; }
const styles = StyleSheet.create({ groupTitle: { ...typography.micro, color: colors.textSecondary, marginBottom: spacing.xs, letterSpacing: 1 }, group: { backgroundColor: colors.surface, borderRadius: radius.md, borderWidth: 1, borderColor: colors.border, paddingHorizontal: spacing.md }, dangerGroup: { borderColor: colors.negative }, row: { minHeight: 56, flexDirection: 'row', alignItems: 'center', gap: spacing.sm }, rowBorder: { borderBottomWidth: 1, borderBottomColor: colors.divider }, label: { ...typography.body, color: colors.text, flex: 1 }, value: { ...typography.caption, color: colors.textSecondary, maxWidth: '42%' }, helper: { ...typography.caption, color: colors.textSecondary, paddingVertical: spacing.sm }, destructive: { color: colors.negative }, pressed: { opacity: 0.7 }, disabled: { opacity: 0.5 } });
