import * as Clipboard from 'expo-clipboard';
import { NativeStackScreenProps } from '@react-navigation/native-stack';
import { useFocusEffect } from '@react-navigation/native';
import { useCallback, useEffect, useRef, useState } from 'react';
import { Alert, AppState, Modal, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { TeamInvitationDto, TeamMemberDto, TeamSeatSummaryDto } from '../apiTypes';
import { AppHeader, ErrorState, LoadingState, PrimaryButton, Screen, SecondaryButton, StatusBadge } from '../components/ui';
import { canMutateTeam, invitationStatusLabel, inviteNeedsManualDelivery, invitePayload, inviteResultCopy, isValidInviteEmail, membershipLabel, remainingSeatCopy, roleLabel, seatDetailCopy, seatUsageCopy, shouldReactivate, teamAvailable, teamErrorCopy } from '../domain/team';
import { ApiError } from '../services/api';
import { teamApi } from '../services/endpoints';
import { useAuth } from '../state/AuthContext';
import { usePlanExperience } from '../state/PlanExperienceContext';
import { colors, radius, spacing, typography } from '../theme';
import { RootStackParamList } from '../types';
import { formatDate } from '../utils/format';

type Props = NativeStackScreenProps<RootStackParamList, 'Team'>;
export function TeamScreen({ navigation }: Props) {
  const { role, business, restore } = useAuth(); const { plan, status, features } = usePlanExperience();
  const [members, setMembers] = useState<TeamMemberDto[]>([]); const [invitations, setInvitations] = useState<TeamInvitationDto[]>([]); const [summary, setSummary] = useState<TeamSeatSummaryDto['seats'] | null>(null); const [loaded, setLoaded] = useState(false); const [refreshing, setRefreshing] = useState(false); const [error, setError] = useState<string | null>(null); const [summaryError, setSummaryError] = useState(false); const [mutation, setMutation] = useState<string | null>(null); const [inviteOpen, setInviteOpen] = useState(false); const [email, setEmail] = useState(''); const [inviteRole, setInviteRole] = useState<'ADMIN'|'STAFF'>('STAFF'); const [inviteResult, setInviteResult] = useState<{ email: string; emailSent: boolean; link: string } | null>(null); const [transferTarget, setTransferTarget] = useState<TeamMemberDto | null>(null); const [transferConfirmation, setTransferConfirmation] = useState(''); const loadingRef = useRef<Promise<void> | null>(null);
  const available = teamAvailable(plan, status, features?.teamManagement ?? null); const canManage = canMutateTeam(role, available); const owner = role === 'OWNER';
  const load = useCallback(async () => { if (loadingRef.current) return loadingRef.current; const request = (async () => { const [teamResult, summaryResult] = await Promise.allSettled([Promise.all([teamApi.listMembers(), owner ? teamApi.listInvitations() : Promise.resolve([])]), teamApi.getSummary()]); if (teamResult.status === 'fulfilled') { setMembers(teamResult.value[0]); setInvitations(teamResult.value[1]); setError(null); } else setError('Couldn’t load your team. Check your connection and try again.'); if (summaryResult.status === 'fulfilled') { setSummary(summaryResult.value.seats); setSummaryError(false); } else setSummaryError(true); setLoaded(true); })(); loadingRef.current = request; try { await request; } finally { loadingRef.current = null; } }, [owner]);
  useFocusEffect(useCallback(() => { void load(); return () => setInviteResult(null); }, [load]));
  useEffect(() => { const subscription = AppState.addEventListener('change', next => { if (next === 'active') void load(); }); return () => subscription.remove(); }, [load]);
  const refresh = () => { setRefreshing(true); void load().finally(() => setRefreshing(false)); };
  const mutate = async (key: string, action: () => Promise<unknown>) => { if (mutation) return; setMutation(key); setError(null); try { await action(); await load(); } catch (caught) { setError(caught instanceof ApiError ? teamErrorCopy(caught.code, caught.message) : teamErrorCopy()); } finally { setMutation(null); } };
  const submitInvite = async () => { if (!isValidInviteEmail(email) || mutation) return; setMutation('invite'); setError(null); try { const created = await teamApi.invite(invitePayload(email, inviteRole)); setInviteResult({ email: created.email, emailSent: created.emailSent, link: `https://chakusa.com/team-invite/${encodeURIComponent(created.token)}` }); setEmail(''); setInviteOpen(false); await load(); } catch (caught) { setError(caught instanceof ApiError ? teamErrorCopy(caught.code, caught.message) : teamErrorCopy()); } finally { setMutation(null); } };
  const remove = (member: TeamMemberDto) => Alert.alert('Remove from team?', `This removes ${member.name}’s access to this Business. It does not delete their Chakusa account.`, [{ text: 'Cancel', style: 'cancel' }, { text: 'Remove from team', style: 'destructive', onPress: () => void mutate(`remove-${member.id}`, () => teamApi.removeMember(member.id)) }]);
  const revoke = (invite: TeamInvitationDto) => Alert.alert('Revoke invitation?', `${invite.invitedEmail} will no longer be able to use this invitation.`, [{ text: 'Keep invitation', style: 'cancel' }, { text: 'Revoke', style: 'destructive', onPress: () => void mutate(`revoke-${invite.id}`, () => teamApi.revokeInvitation(invite.id)) }]);
  const transfer = async () => { if (!transferTarget || transferConfirmation.trim() !== business?.name.trim() || mutation) return; setMutation('transfer'); setError(null); try { const nextOwner = transferTarget.name; await teamApi.transferOwnership(transferTarget.id, transferConfirmation); setTransferTarget(null); setTransferConfirmation(''); await restore(); await load(); Alert.alert('Ownership transferred', `${nextOwner} is now the owner. You remain an administrator.`); } catch (caught) { setError(caught instanceof ApiError ? teamErrorCopy(caught.code, caught.message) : teamErrorCopy()); } finally { setMutation(null); } };
  const pending = invitations.filter(item => item.status === 'PENDING');
  return <><Screen refreshing={refreshing} onRefresh={refresh}><AppHeader eyebrow="TEAM" title="Chakusa Business" subtitle="Run Chakusa with your team." />
    {!available ? <View style={styles.locked}><Text style={styles.heading}>Team access is unavailable on your current plan</Text><Text style={styles.body}>Existing team records are preserved. Upgrade to Chakusa Business to invite or manage team members.</Text>{owner ? <PrimaryButton fullWidth label="View Business" onPress={() => navigation.navigate('Pro')} /> : null}</View> : null}
    {!loaded ? <LoadingState label="Loading team…" /> : error && !members.length ? <ErrorState message={error} onRetry={() => void load()} /> : <>
      <View style={styles.card}><Text style={styles.heading}>Seats</Text>{summary ? <><Text style={styles.seats}>{seatUsageCopy(summary)}</Text><Text style={styles.caption}>{seatDetailCopy(summary)}</Text><Text style={styles.caption}>{remainingSeatCopy(summary)}</Text>{summaryError ? <Text style={styles.error}>Couldn’t refresh seats. Last known values are shown.</Text> : null}</> : <ErrorState message="Couldn’t load seat information. Your team is still available." onRetry={() => void load()} />}</View>
      <View style={styles.section}><Text style={styles.heading}>Members</Text>{members.map(member => <MemberRow key={member.id} member={member} canManage={canManage} busy={Boolean(mutation)} onRole={() => void mutate(`role-${member.id}`, () => teamApi.changeRole(member.id, member.role === 'ADMIN' ? 'STAFF' : 'ADMIN'))} onRemove={() => remove(member)} onReactivate={() => void mutate(`reactivate-${member.id}`, () => teamApi.reactivateMember(member.id))} onTransfer={() => { setTransferTarget(member); setTransferConfirmation(''); }} />)}</View>
      {owner ? <View style={styles.section}><View style={styles.sectionTop}><Text style={styles.heading}>Pending invitations</Text>{canManage ? <Pressable accessibilityRole="button" onPress={() => setInviteOpen(true)} style={styles.inlineAction}><Text style={styles.inlineActionText}>Invite member</Text></Pressable> : null}</View>{pending.length ? pending.map(item => <View key={item.id} style={styles.row}><View style={styles.copy}><Text style={styles.name}>{item.invitedEmail}</Text><Text style={styles.caption}>{roleLabel(item.role)} · Expires {formatDate(item.expiresAt)}</Text><Text style={styles.caption}>{invitationStatusLabel(item.status)}</Text></View>{canManage ? <SecondaryButton compact disabled={Boolean(mutation)} label="Revoke" onPress={() => revoke(item)} /> : null}</View>) : <Text style={styles.body}>No pending invitations.</Text>}</View> : null}
    </>}
    {inviteResult ? <View style={styles.manual}><Text style={styles.heading}>Invitation created</Text><Text style={styles.body}>{inviteResultCopy(inviteResult.email, inviteResult.emailSent)}</Text>{inviteNeedsManualDelivery(inviteResult.emailSent) ? <Text style={styles.body}>Copy this link and send it to the team member to complete delivery manually.</Text> : null}<PrimaryButton fullWidth label="Copy invitation link" onPress={() => void Clipboard.setStringAsync(inviteResult.link).then(() => setInviteResult(null))} /><SecondaryButton fullWidth label="Dismiss" onPress={() => setInviteResult(null)} /></View> : null}
    {error && members.length ? <Text accessibilityRole="alert" style={styles.error}>{error} Existing team information is still shown.</Text> : null}
  </Screen><Modal visible={inviteOpen} transparent animationType="fade" onRequestClose={() => setInviteOpen(false)}><View style={styles.overlay}><View accessibilityViewIsModal style={styles.dialog}><Text style={styles.heading}>Invite team member</Text><Text style={styles.label}>Email</Text><TextInput accessibilityLabel="Team member email" autoCapitalize="none" keyboardType="email-address" value={email} onChangeText={setEmail} style={styles.input} /><Text style={styles.label}>Role</Text><View accessibilityRole="radiogroup" style={styles.roles}><RoleChoice role="ADMIN" selected={inviteRole === 'ADMIN'} onPress={() => setInviteRole('ADMIN')} copy="Helps manage daily business operations." /><RoleChoice role="STAFF" selected={inviteRole === 'STAFF'} onPress={() => setInviteRole('STAFF')} copy="Works with customers, leads, reviews, and daily tasks." /></View><PrimaryButton fullWidth disabled={!isValidInviteEmail(email) || Boolean(mutation)} label={mutation === 'invite' ? 'Sending invitation…' : 'Send invitation'} onPress={() => void submitInvite()} /><SecondaryButton fullWidth disabled={Boolean(mutation)} label="Cancel" onPress={() => setInviteOpen(false)} /></View></View></Modal><Modal visible={Boolean(transferTarget)} transparent animationType="fade" onRequestClose={() => setTransferTarget(null)}><View style={styles.overlay}><View accessibilityViewIsModal style={styles.dialog}><Text style={styles.heading}>Transfer business ownership</Text><Text style={styles.body}>{transferTarget?.name} will control billing, team access, and account deletion. You will become an administrator.</Text><Text style={styles.label}>Type {business?.name} to confirm</Text><TextInput accessibilityLabel="Business name confirmation" autoCapitalize="none" value={transferConfirmation} onChangeText={setTransferConfirmation} style={styles.input} /><PrimaryButton fullWidth disabled={transferConfirmation.trim() !== business?.name.trim() || Boolean(mutation)} label={mutation === 'transfer' ? 'Transferring ownership…' : 'Transfer ownership'} onPress={() => void transfer()} /><SecondaryButton fullWidth disabled={Boolean(mutation)} label="Cancel" onPress={() => setTransferTarget(null)} /></View></View></Modal></>;
}
function MemberRow({ member, canManage, busy, onRole, onRemove, onReactivate, onTransfer }: { member: TeamMemberDto; canManage: boolean; busy: boolean; onRole: () => void; onRemove: () => void; onReactivate: () => void; onTransfer: () => void }) { const mutable = canManage && member.role !== 'OWNER'; return <View accessible accessibilityLabel={`${member.name}, ${member.email}, ${roleLabel(member.role)}, ${membershipLabel(member.status)}`} style={[styles.row, member.status === 'SUSPENDED' && styles.suspended]}><View style={styles.copy}><Text style={styles.name}>{member.name}</Text><Text style={styles.body}>{member.email}</Text><View style={styles.meta}><StatusBadge label={roleLabel(member.role)} /><Text style={styles.caption}>{membershipLabel(member.status)} · Joined {formatDate(member.joinedAt)}</Text></View></View>{mutable ? <View style={styles.actions}>{member.status === 'ACTIVE' ? <><SecondaryButton compact disabled={busy} label={`Make ${member.role === 'ADMIN' ? 'Staff' : 'Admin'}`} onPress={onRole} /><SecondaryButton compact disabled={busy} label="Transfer ownership" onPress={onTransfer} /><SecondaryButton compact disabled={busy} label="Remove from team" onPress={onRemove} /></> : shouldReactivate(member, canManage) ? <SecondaryButton compact disabled={busy} label="Reactivate" onPress={onReactivate} /> : null}</View> : null}</View>; }
function RoleChoice({ role, selected, copy, onPress }: { role: 'ADMIN'|'STAFF'; selected: boolean; copy: string; onPress: () => void }) { return <Pressable accessibilityRole="radio" accessibilityState={{ checked: selected }} onPress={onPress} style={[styles.role, selected && styles.roleSelected]}><Text style={styles.name}>{roleLabel(role)}</Text><Text style={styles.caption}>{copy}</Text></Pressable>; }
const styles = StyleSheet.create({ locked: { padding: spacing.lg, borderRadius: radius.md, backgroundColor: colors.attentionSoft, borderWidth: 1, borderColor: colors.attention, gap: spacing.md }, card: { backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, borderRadius: radius.md, padding: spacing.lg, gap: spacing.xs }, section: { backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, borderRadius: radius.md, padding: spacing.lg, gap: spacing.sm }, sectionTop: { minHeight: 44, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: spacing.md }, heading: { ...typography.subheading, color: colors.text }, seats: { ...typography.heading, color: colors.text }, body: { ...typography.body, color: colors.textSecondary }, caption: { ...typography.caption, color: colors.textSecondary }, row: { minHeight: 64, borderTopWidth: 1, borderTopColor: colors.divider, paddingVertical: spacing.md, gap: spacing.sm }, suspended: { opacity: 0.72 }, copy: { flex: 1, gap: spacing.xxs }, name: { ...typography.bodyStrong, color: colors.text }, meta: { flexDirection: 'row', alignItems: 'center', flexWrap: 'wrap', gap: spacing.xs }, actions: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.xs }, inlineAction: { minHeight: 44, justifyContent: 'center' }, inlineActionText: { ...typography.bodyStrong, color: colors.primary }, manual: { padding: spacing.lg, borderRadius: radius.md, backgroundColor: colors.primarySoft, borderWidth: 1, borderColor: colors.primary, gap: spacing.md }, error: { ...typography.caption, color: colors.negative }, overlay: { flex: 1, backgroundColor: colors.overlay, justifyContent: 'center', padding: spacing.lg }, dialog: { backgroundColor: colors.surface, borderRadius: radius.xl, padding: spacing.xl, gap: spacing.md }, label: { ...typography.caption, color: colors.text }, input: { minHeight: 50, borderWidth: 1, borderColor: colors.border, borderRadius: radius.md, paddingHorizontal: spacing.md, ...typography.body }, roles: { gap: spacing.sm }, role: { minHeight: 64, padding: spacing.md, borderWidth: 1, borderColor: colors.border, borderRadius: radius.md }, roleSelected: { borderColor: colors.primary, backgroundColor: colors.primarySoft } });
