import { useNavigation } from '@react-navigation/native';
import { NativeStackNavigationProp } from '@react-navigation/native-stack';
import { useEffect, useMemo, useState } from 'react';
import { Alert, Modal, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { MessageTone, MessageType } from '../apiTypes';
import { AppHeader, EmptyState, ErrorState, IconButton, LoadingState, PrimaryButton, Screen, SecondaryButton, SectionHeader } from '../components/ui';
import { ApiError } from '../services/api';
import { templatesApi } from '../services/endpoints';
import { useAppState } from '../state/AppContext';
import { usePlanExperience } from '../state/PlanExperienceContext';
import { RootStackParamList } from '../types';
import { colors, radius, spacing, typography } from '../theme';
import { titleCase } from '../utils/format';

const types: MessageType[] = ['missed_call','booking_confirmation','review_request','private_feedback','comeback_reminder','custom','public_profile_inquiry']; const tones: MessageTone[] = ['friendly','professional','casual'];
export function TemplatesScreen() {
  const navigation = useNavigation<NativeStackNavigationProp<RootStackParamList>>();
  const { templates, state, loadTemplates } = useAppState(); const { usage, refresh: refreshPlan } = usePlanExperience(); const [activeId, setActiveId] = useState<string | null>(null); const active = useMemo(() => templates.find(item => item.id === activeId) ?? templates[0] ?? null, [activeId, templates]); const [body, setBody] = useState(''); const [name, setName] = useState(''); const [tone, setTone] = useState<MessageTone>('friendly'); const [creating, setCreating] = useState(false); const [newType, setNewType] = useState<MessageType>('missed_call'); const [newName, setNewName] = useState(''); const [newBody, setNewBody] = useState('Hi {{customer_name}}, this is {{business_name}}.'); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null);
  useEffect(() => { void loadTemplates(); }, [loadTemplates]); useEffect(() => { if (active) { setActiveId(active.id); setBody(active.body); setName(active.name); setTone(active.tone); } }, [active]);
  const save = async () => { if (!active || saving) return; setSaving(true); setError(null); try { await templatesApi.patch(active.id, { name: name.trim(), body: body.trim(), tone }); await loadTemplates(); Alert.alert('Template saved', 'The persisted template was reloaded from CHAKUSA.'); } catch (caught) { setError(caught instanceof ApiError ? caught.message : 'Unable to save template.'); } finally { setSaving(false); } };
  const create = async () => { if (saving) return; setSaving(true); setError(null); try { const created = await templatesApi.create({ templateType: newType, name: newName.trim(), body: newBody.trim(), tone, isDefault: true }); void refreshPlan(); setCreating(false); await loadTemplates(); setActiveId(created.id); } catch (caught) { setError(caught instanceof ApiError ? caught.message : 'Unable to create template.'); } finally { setSaving(false); } };
  return <><Screen><AppHeader eyebrow="CUSTOMER RECOVERY" title="Message templates" subtitle="Persisted templates for manual follow-up" right={<IconButton icon="add" label="Create template" onPress={() => setCreating(true)} />} />{!state.templates.loaded && state.templates.loading ? <LoadingState label="Loading templates…" /> : state.templates.error ? <ErrorState message={state.templates.error} onRetry={() => void loadTemplates()} /> : !templates.length ? <EmptyState title="No custom templates" message="Create one, or CHAKUSA will use the backend’s industry defaults." icon="document-text-outline" /> : <><SectionHeader title="Templates" /><View style={styles.tabs}>{templates.map(template => <Pressable key={template.id} onPress={() => setActiveId(template.id)} style={[styles.tab, active?.id === template.id && styles.tabActive]}><View><Text style={[styles.tabText, active?.id === template.id && styles.tabTextActive]}>{template.name}</Text><Text style={styles.tabMeta}>{titleCase(template.templateType)} · {titleCase(template.tone)}</Text></View></Pressable>)}</View>{active ? <View><Text style={styles.label}>Name</Text><TextInput value={name} onChangeText={setName} style={styles.input} /><Text style={styles.label}>Body</Text><TextInput multiline value={body} onChangeText={setBody} style={styles.editor} textAlignVertical="top" /><Text style={styles.helper}>Variables: {'{{customer_name}}'} · {'{{business_name}}'} · {'{{service_name}}'} · {'{{booking_time}}'} · {'{{review_link}}'} · {'{{phone_number}}'}</Text><Text style={styles.label}>Tone</Text><Choices options={tones} value={tone} onChange={value => setTone(value as MessageTone)} /></View> : null}</>}{error ? <Text style={styles.error}>{error}</Text> : null}{active ? <PrimaryButton disabled={saving || !name.trim() || !body.trim()} fullWidth label={saving ? 'Saving…' : 'Save template'} onPress={() => void save()} /> : null}</Screen>
    <Modal visible={creating} transparent animationType="slide" onRequestClose={() => setCreating(false)}><Pressable style={styles.overlay} onPress={() => !saving && setCreating(false)}><Pressable style={styles.sheet} onPress={() => undefined}><Text style={styles.sheetTitle}>New template</Text><Text style={styles.label}>Type</Text><Choices options={types} value={newType} onChange={value => setNewType(value as MessageType)} />{usage ? <Pressable accessibilityRole="button" onPress={() => { setCreating(false); navigation.navigate('Pro'); }}><Text style={styles.helper}>{usage.customTemplates.limitPerType === null ? 'Unlimited custom templates for this type.' : `${usage.customTemplates.usageByType[newType]} of ${usage.customTemplates.limitPerType} custom template${usage.customTemplates.limitPerType === 1 ? '' : 's'} used for this type.`}</Text></Pressable> : null}<Text style={styles.label}>Name</Text><TextInput value={newName} onChangeText={setNewName} style={styles.input} /><Text style={styles.label}>Body</Text><TextInput multiline value={newBody} onChangeText={setNewBody} style={styles.editor} />{error ? <Text style={styles.error}>{error}</Text> : null}<PrimaryButton disabled={saving || !newName.trim() || !newBody.trim()} fullWidth label={saving ? 'Creating…' : 'Create template'} onPress={() => void create()} /><SecondaryButton disabled={saving} fullWidth label="Cancel" onPress={() => setCreating(false)} /></Pressable></Pressable></Modal>
  </>;
}
function Choices({ options, value, onChange }: { options: string[]; value: string; onChange: (value: string) => void }) { return <View style={styles.choices}>{options.map(option => <Pressable key={option} onPress={() => onChange(option)} style={[styles.choice, value === option && styles.choiceActive]}><Text style={[styles.choiceText, value === option && styles.choiceTextActive]}>{titleCase(option)}</Text></Pressable>)}</View>; }
const styles = StyleSheet.create({ tabs: { gap: spacing.xs }, tab: { minHeight: 58, justifyContent: 'center', paddingHorizontal: spacing.md, backgroundColor: colors.surface, borderRadius: radius.md, borderWidth: 1, borderColor: colors.border }, tabActive: { borderColor: colors.primary }, tabText: { ...typography.body, color: colors.text }, tabTextActive: { color: colors.primary, fontWeight: '600' }, tabMeta: { ...typography.caption, color: colors.textSecondary }, label: { ...typography.caption, color: colors.text, marginTop: spacing.md, marginBottom: spacing.xs }, input: { minHeight: 48, backgroundColor: colors.surface, borderRadius: radius.md, borderWidth: 1, borderColor: colors.border, paddingHorizontal: spacing.md, ...typography.body, color: colors.text }, editor: { minHeight: 150, backgroundColor: colors.surface, borderRadius: radius.md, borderWidth: 1, borderColor: colors.border, padding: spacing.md, ...typography.body, color: colors.text }, helper: { ...typography.caption, color: colors.textSecondary, marginTop: spacing.xs }, choices: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.xs }, choice: { minHeight: 40, justifyContent: 'center', paddingHorizontal: spacing.sm, borderRadius: radius.round, borderWidth: 1, borderColor: colors.border }, choiceActive: { borderColor: colors.primary }, choiceText: { ...typography.caption, color: colors.textSecondary }, choiceTextActive: { color: colors.primary, fontWeight: '700' }, error: { ...typography.caption, color: colors.negative }, overlay: { flex: 1, backgroundColor: colors.overlay, justifyContent: 'flex-end' }, sheet: { backgroundColor: colors.surface, borderTopLeftRadius: radius.xl, borderTopRightRadius: radius.xl, padding: spacing.xl, paddingBottom: 40, gap: spacing.xs }, sheetTitle: { ...typography.heading, color: colors.text } });
