export interface IndustryProfession { label: string; href: string; description: string }
export interface IndustryGroup { id: string; label: string; summary: string; icon: string; overviewHref: string; professions: IndustryProfession[] }
export interface IndustryProfessionPage {
  id: string;
  title: string;
  categoryLabel: string;
  headline: string;
  detailIntro: string;
  examples: string[];
  workflow: string[];
}

export const industryGroups: IndustryGroup[] = [
  { id:"beauty-wellness", label:"Beauty and wellness", summary:"Personal care businesses built around appointments and returning clients.", icon:"spa", overviewHref:"/industries/beauty", professions:[
    {label:"Barbers",href:"/industries/barbers",description:"Chair bookings, customer notes, reviews, and regulars."},
    {label:"Hair salons",href:"/industries/hair-salons",description:"Appointments, client history, and repeat visits."},
    {label:"Beauty clinics",href:"/industries/beauty-clinics",description:"Enquiries, treatment bookings, and follow-up."},
    {label:"Spas and massage",href:"/industries/spas-massage",description:"Availability, visits, feedback, and return reminders."},
  ]},
  { id:"home-services", label:"Home services", summary:"Mobile teams that need every call, job, and returning customer kept visible.", icon:"clean", overviewHref:"/industries/home-services", professions:[
    {label:"Cleaners",href:"/industries/cleaners",description:"Recurring work, enquiries, and customer follow-up."},
    {label:"Plumbers",href:"/industries/plumbers",description:"Missed job calls, scheduling, and customer records."},
    {label:"Electricians",href:"/industries/electricians",description:"New enquiries, booked work, and review requests."},
    {label:"Movers",href:"/industries/movers",description:"Quote enquiries, scheduled jobs, and customer feedback."},
    {label:"Small contractors",href:"/industries/small-contractors",description:"Leads, active work, and repeat customer context."},
  ]},
  { id:"automotive", label:"Automotive", summary:"Vehicle service businesses that grow through trust and repeat maintenance.", icon:"car", overviewHref:"/industries/automotive", professions:[
    {label:"Mechanics",href:"/industries/mechanics",description:"Repair enquiries, appointments, reviews, and service returns."},
    {label:"Car washes",href:"/industries/car-washes",description:"Bookings, customer feedback, and repeat visits."},
    {label:"Detailers",href:"/industries/detailers",description:"Service enquiries, scheduled work, and client retention."},
  ]},
  { id:"professional", label:"Professional services", summary:"Appointment-led practices and studios where every client relationship matters.", icon:"camera", overviewHref:"/industries/professional", professions:[
    {label:"Dentists",href:"/industries/dentists",description:"Appointment enquiries, patient follow-up, and reviews."},
    {label:"Photographers",href:"/industries/photographers",description:"Session enquiries, bookings, and customer feedback."},
    {label:"Consultants",href:"/industries/consultants",description:"New leads, scheduled sessions, and relationship history."},
    {label:"Restaurants",href:"/industries/restaurants",description:"Customer enquiries, reservations, feedback, and return visits."},
  ]},
];

// Barbers has a dedicated editorial route. Every other profession listed in
// the menu is generated by /industries/[slug].astro from this collection, so
// the navigation never points at a placeholder or an unrelated category.
export const industryProfessionPages: IndustryProfessionPage[] = [
  {id:"hair-salons",title:"Hair salons",categoryLabel:"Beauty and wellness",headline:"Keep every chair, client, and return visit connected.",detailIntro:"Chakusa keeps new enquiries, scheduled appointments, customer notes, review requests, and clients due back visible in one workflow.",examples:["Hair salon","Color studio","Multi-chair salon"],workflow:["Capture a new-service enquiry before it goes cold","Request honest feedback after the completed appointment","See clients who are due to book their usual service again"]},
  {id:"beauty-clinics",title:"Beauty clinics",categoryLabel:"Beauty and wellness",headline:"A clearer path from treatment enquiry to follow-up.",detailIntro:"Keep consultation enquiries, treatment appointments, customer context, feedback, and responsible follow-up together without losing the human handoff.",examples:["Beauty clinic","Aesthetics studio","Skin studio"],workflow:["Keep consultation and treatment enquiries in one queue","Request a review after a completed visit without rating gating","Create a clear next action for an appropriate follow-up"]},
  {id:"spas-massage",title:"Spas and massage",categoryLabel:"Beauty and wellness",headline:"Make calm service feel organised behind the scenes.",detailIntro:"Chakusa connects availability, appointments, customer history, review requests, and return reminders for appointment-led wellness businesses.",examples:["Day spa","Massage studio","Wellness centre"],workflow:["Respond to service enquiries with the relevant context attached","Ask every eligible visitor for honest feedback after the visit","Keep regular clients visible when their normal return window arrives"]},
  {id:"cleaners",title:"Cleaners",categoryLabel:"Home services",headline:"Recurring work without scattered customer follow-up.",detailIntro:"Keep quote enquiries, scheduled cleaning visits, customer notes, review requests, and recurring-service reminders in one place.",examples:["Home cleaner","Commercial cleaner","Cleaning team"],workflow:["Turn a new quote request into a visible lead","Request feedback after a completed cleaning visit","Track customers who may be ready to schedule the next visit"]},
  {id:"plumbers",title:"Plumbers",categoryLabel:"Home services",headline:"Keep the next job visible—even when you are on the tools.",detailIntro:"Chakusa connects incoming enquiries, booked jobs, customer details, reviews, and later follow-up for busy plumbing businesses.",examples:["Independent plumber","Plumbing team","Emergency service"],workflow:["Record the job enquiry and what the customer needs","Ask for honest feedback once the work is complete","Keep previous customers available for future service follow-up"]},
  {id:"electricians",title:"Electricians",categoryLabel:"Home services",headline:"From first enquiry to completed electrical job.",detailIntro:"Keep job enquiries, scheduling, customer context, review requests, and repeat-service opportunities connected in one business view.",examples:["Independent electrician","Electrical contractor","Service team"],workflow:["Capture each new work enquiry with its customer context","Send the same ungated review request after completed work","Keep past customers and their service history easy to find"]},
  {id:"movers",title:"Movers",categoryLabel:"Home services",headline:"Move every quote enquiry toward a clear next step.",detailIntro:"Chakusa keeps moving enquiries, scheduled work, customer records, post-job feedback, and later follow-up from becoming disconnected.",examples:["Local mover","Removal company","Small moving team"],workflow:["Track new quote enquiries and their next action","Request honest feedback after the move is completed","Keep customer history available for referrals and future work"]},
  {id:"small-contractors",title:"Small contractors",categoryLabel:"Home services",headline:"A practical view of leads, active work, and past customers.",detailIntro:"Keep new project enquiries and customer follow-up visible without forcing a small contracting team into an oversized system.",examples:["General contractor","Small trade team","Independent specialist"],workflow:["Record the project enquiry and the promised follow-up","Request a review once the agreed work is completed","Return to the full customer history when new work appears"]},
  {id:"mechanics",title:"Mechanics",categoryLabel:"Automotive",headline:"Connect repair enquiries with the customer’s next service.",detailIntro:"Chakusa keeps vehicle-service enquiries, appointments, customer records, reviews, and routine return reminders together.",examples:["Independent mechanic","Repair workshop","Service garage"],workflow:["Capture a repair or inspection enquiry as a trackable lead","Request feedback after the vehicle is collected","See customers who may be due for their next routine service"]},
  {id:"car-washes",title:"Car washes",categoryLabel:"Automotive",headline:"Turn one good visit into a reason to return.",detailIntro:"Manage booking enquiries, customer feedback, visit history, and repeat-visit reminders for car-wash businesses.",examples:["Hand car wash","Valeting service","Wash team"],workflow:["Keep booking and service enquiries visible","Ask every eligible customer for honest feedback","Identify customers whose usual return window has arrived"]},
  {id:"detailers",title:"Detailers",categoryLabel:"Automotive",headline:"Premium vehicle care with organised customer follow-through.",detailIntro:"Connect detailing enquiries, scheduled work, customer preferences, reviews, and repeat-care reminders around each visit.",examples:["Mobile detailer","Detailing studio","Vehicle-care specialist"],workflow:["Capture the requested package and vehicle context","Request an ungated review after completed work","Keep repeat-care opportunities visible without guessing"]},
  {id:"dentists",title:"Dentists",categoryLabel:"Professional services",headline:"Keep appointment enquiries and appropriate follow-up visible.",detailIntro:"Chakusa supports general appointment operations and customer communication; it is not a clinical record system or a source of medical advice.",examples:["Dental practice","Dental clinic","Appointment team"],workflow:["Track a non-clinical appointment enquiry and its next action","Request service feedback after a completed appointment","Create appropriate reminders without presenting medical advice"]},
  {id:"photographers",title:"Photographers",categoryLabel:"Professional services",headline:"From first shoot enquiry to the next client relationship.",detailIntro:"Keep session enquiries, booking context, customer feedback, and later follow-up connected for photography businesses.",examples:["Portrait photographer","Event photographer","Creative studio"],workflow:["Capture the shoot enquiry and requested date","Request honest feedback after the completed session","Keep the customer relationship available for future work"]},
  {id:"consultants",title:"Consultants",categoryLabel:"Professional services",headline:"Give every new client conversation a clear next action.",detailIntro:"Chakusa connects enquiries, scheduled sessions, relationship history, feedback, and follow-up for appointment-led consultants.",examples:["Independent consultant","Advisory practice","Small consultancy"],workflow:["Turn the initial enquiry into a visible lead","Request feedback after the completed engagement","Keep prior client context ready when the relationship resumes"]},
  {id:"restaurants",title:"Restaurants",categoryLabel:"Professional services",headline:"Keep enquiries, reservations, feedback, and return visits connected.",detailIntro:"For restaurants using appointment-style reservations and customer follow-up, Chakusa keeps the relationship visible before and after a visit.",examples:["Independent restaurant","Dining room","Reservation team"],workflow:["Capture an enquiry or reservation request","Ask for honest feedback after the visit","Keep returning guest context available for future contact"]},
];
