// Matches mobile/src/screens/OnboardingScreen.tsx's industry picker exactly.
// Do not add a category that isn't offered at signup. Ordered by real
// message-template depth (src/lib/defaultTemplates.ts currently has
// industry-specific templates only for barber, dentist, and restaurant),
// per docs/WEBSITE_CREATIVE_DIRECTION.md Part 6.

export interface Industry {
  id: string;
  title: string;
  examples: string[];
  /** Short teaser, used on the /industries index card only. */
  copy: string;
  /** Written headline for the /industries/[slug] detail page hero. Never
   * generated by joining `examples` into a sentence, that reads like code
   * output, not copy. */
  headline: string;
  /** Detail-page hero support line. Distinct from `copy` on purpose, the
   * two pages sit one click apart and must not repeat the same sentence. */
  detailIntro: string;
  /** 3 concrete, honest examples of what Chakusa tracks for this vertical,
   * always in Recover, Review, Retain order, every line must map to a real
   * feature (Lead, ReviewRequest, Reminder), never an automation claim
   * beyond what's actually live. */
  workflow: string[];
}

export const industries: Industry[] = [
  {
    id: "beauty",
    title: "Beauty",
    examples: ["Salon", "Barber", "Beauty clinic", "Spa"],
    copy: "Missed a walk-in call, or a client who hasn't rebooked their usual cut or color? Chakusa tracks both without you having to remember.",
    headline: "Every client remembered, every chair booked.",
    detailIntro: "Salons and barbershops live on the chair being full and the same faces coming back. Chakusa catches the two moments that usually slip: the call you couldn't take, and the regular who's quietly overdue.",
    workflow: [
      "A missed call from a new client becomes a lead you can follow up with",
      "Send a review request right after a cut, color, or treatment",
      "See who's overdue for their usual appointment before they book elsewhere",
    ],
  },
  {
    id: "professional",
    title: "Professional",
    examples: ["Dentist", "Photographer", "Consultant", "Other"],
    copy: "A missed appointment call or a patient overdue for a check-up shouldn't slip through. Chakusa keeps both visible.",
    headline: "No missed call, no forgotten follow-up.",
    detailIntro: "Practices and studios run on booked time, so a missed call is a missed slot, and a client who never rebooks is revenue that just stopped showing up. Chakusa keeps both in view.",
    workflow: [
      "Track every missed booking call as a lead, not a lost message",
      "Ask for a review once a session or appointment wraps up",
      "Know who's due for a check-up, follow-up, or repeat booking",
    ],
  },
  {
    id: "home-services",
    title: "Home services",
    examples: ["Plumber", "Electrician", "Cleaner", "Contractor"],
    copy: "Between jobs, a missed call is a missed job. Chakusa tracks it as a lead the moment it happens.",
    headline: "Between jobs, nothing gets lost.",
    detailIntro: "You can't answer a call mid-job, and most tools assume you can. Chakusa tracks the call for you and keeps your regulars from quietly switching to whoever answered first.",
    workflow: [
      "A missed call while you're on a job still becomes a trackable lead",
      "Request a review once the job's done, while it's still fresh",
      "Get a reminder when a regular client is due for their next service",
    ],
  },
  {
    id: "automotive",
    title: "Automotive",
    examples: ["Mechanic", "Car wash", "Detailing"],
    copy: "Track every inquiry, ask for a review after the work is done, and know who's due back for their next service.",
    headline: "From first call to next service, tracked.",
    detailIntro: "A shop lives on both new inquiries and repeat service. Chakusa tracks the ones you'd otherwise lose track of: the call that came in busy, and the customer due back for their next check.",
    workflow: [
      "Every missed inquiry call is tracked as a lead, not forgotten",
      "Ask for a review after the work is picked up",
      "See who's due back for a seasonal check or routine service",
    ],
  },
  {
    id: "hospitality",
    title: "Hospitality",
    examples: ["Restaurant", "Private dining", "Reservation team"],
    copy: "Keep reservation enquiries, guest feedback, and returning-customer context connected.",
    headline: "Turn a good visit into a lasting guest relationship.",
    detailIntro: "Independent restaurants rely on responsive reservations, trusted feedback, and guests choosing to return. Chakusa keeps those relationship moments visible.",
    workflow: [
      "Capture an enquiry or reservation request with its next action",
      "Ask every eligible guest for honest feedback after the visit",
      "Keep returning guest context available for future contact",
    ],
  },
];
