import { useState } from "react";
import { useMutation, useQuery } from "@tanstack/react-query";
import { apiFetch } from "../api";
import { DataTable, ErrorState, formatDate, LoadingState, StatusBadge } from "./ui";
interface Detail { versions:{id:string;version:number;publishedAt:string|null;createdAt:string;checksum:string}[]; executions:{id:string;status:string;attempts:number;lastError:string|null;createdAt:string;history:{id:string;type:string;nodeId:string|null;error:string|null;durationMs:number|null;createdAt:string}[]}[] }
export function AdminWorkflowOperations({workflowIds}:{workflowIds:{id:string;name:string}[]}) {
 const [selected,setSelected]=useState(""); const [definition,setDefinition]=useState('{\n  "trigger": { "type": "MANUAL", "config": {} },\n  "nodes": []\n}'); const [template,setTemplate]=useState({key:"",name:"",description:""});
 const detail=useQuery({queryKey:["platform-workflow-detail",selected],queryFn:()=>apiFetch<Detail>(`/admin/workflows/${selected}`),enabled:Boolean(selected)});
 const version=useMutation({mutationFn:()=>apiFetch(`/admin/workflows/${selected}/versions`,{method:"POST",body:JSON.stringify({definition:JSON.parse(definition)})}),onSuccess:()=>detail.refetch()});
 const templateCreate=useMutation({mutationFn:()=>apiFetch('/admin/workflow-templates',{method:'POST',body:JSON.stringify({...template,definition:JSON.parse(definition)})})});
 return <section className="panel table-panel"><div className="panel-heading"><div><p className="eyebrow">Automation</p><h2>Workflow builder and inspection</h2></div><select aria-label="Select workflow" value={selected} onChange={event=>setSelected(event.target.value)}><option value="">Select a workflow</option>{workflowIds.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></div>{selected&&detail.isLoading?<LoadingState label="Loading workflow details"/>:null}{detail.error?<ErrorState message={detail.error.message} onRetry={()=>void detail.refetch()}/>:null}{detail.data?<><div className="automation-builder"><label><span>Validated workflow definition (JSON)</span><textarea value={definition} onChange={event=>setDefinition(event.target.value)} spellCheck={false}/></label><button className="button primary" disabled={version.isPending} onClick={()=>version.mutate()}>Create immutable version</button>{version.error instanceof Error?<p className="error-copy">{version.error.message}</p>:null}</div><DataTable columns={["Version","Published","Created","Checksum"]} rows={detail.data.versions.map(item=>[item.version,item.publishedAt?formatDate(item.publishedAt):"Draft",formatDate(item.createdAt),item.checksum])} empty={{title:"No versions",description:"This workflow has no versions."}}/><DataTable columns={["Execution","Status","Attempts","Created","Failure"]} rows={detail.data.executions.map(item=>[item.id,<StatusBadge value={item.status}/>,item.attempts,formatDate(item.createdAt),item.lastError??"—"])} empty={{title:"No executions",description:"This workflow has no execution history."}}/><DataTable columns={["Event","Node","Duration","Time","Failure"]} rows={detail.data.executions.flatMap(execution=>execution.history.map(event=>[event.type,event.nodeId??"—",event.durationMs==null?"—":`${event.durationMs} ms`,formatDate(event.createdAt),event.error??"—"]))} empty={{title:"No runtime events",description:"Execution events will appear here."}}/></>:null}<div className="automation-builder"><h3>Create template version</h3><div className="builder-fields"><input aria-label="Template key" placeholder="FOLLOW_UP_TEMPLATE" value={template.key} onChange={event=>setTemplate(value=>({...value,key:event.target.value.toUpperCase()}))}/><input aria-label="Template name" placeholder="Template name" value={template.name} onChange={event=>setTemplate(value=>({...value,name:event.target.value}))}/><input aria-label="Template description" placeholder="Description" value={template.description} onChange={event=>setTemplate(value=>({...value,description:event.target.value}))}/></div><button className="button secondary" disabled={!template.key||!template.name||templateCreate.isPending} onClick={()=>templateCreate.mutate()}>Create template version</button>{templateCreate.error instanceof Error?<p className="error-copy">{templateCreate.error.message}</p>:null}</div></section>;
}
