import crypto from "node:crypto";
import { Prisma } from "@prisma/client";
import { prisma } from "../../lib/prisma.js";
import { ApiError } from "../../lib/errors.js";
import { recordOutboxEvent } from "../../lib/outbox.js";
import type { WorkflowDefinition } from "../../lib/automation/workflowContracts.js";
import { validateWorkflow } from "../../lib/automation/workflowValidation.js";
import { cancelWorkflowExecution, pauseWorkflowExecution, resumeWorkflowExecution, startWorkflowExecution } from "../../lib/automation/workflowRuntime.js";
import { isTimeTriggered, nextWorkflowTriggerAt } from "../../lib/automation/workflowScheduling.js";

const checksum = (definition: WorkflowDefinition) => crypto.createHash("sha256").update(JSON.stringify(definition)).digest("hex");
function assertValid(definition: WorkflowDefinition) { const result = validateWorkflow(definition); if (!result.valid) throw ApiError.badRequest(`Invalid workflow: ${result.errors.join("; ")}`); }
export function listWorkflows(businessId: string) { return prisma.workflow.findMany({ where: { businessId, status: { not: "ARCHIVED" } }, include: { versions: { orderBy: { version: "desc" }, take: 1 }, _count: { select: { executions: true } } }, orderBy: { updatedAt: "desc" } }); }
export async function getWorkflow(businessId: string, id: string) { const workflow = await prisma.workflow.findFirst({ where: { id, businessId }, include: { versions: { orderBy: { version: "desc" } }, executions: { orderBy: { createdAt: "desc" }, take: 25 }, _count: { select: { executions: true } } } }); if (!workflow) throw ApiError.notFound("Workflow not found"); return workflow; }
export async function createWorkflow(businessId: string, userId: string, name: string, definition: WorkflowDefinition, description?: string) { assertValid(definition); return prisma.$transaction(async (tx) => { const workflow = await tx.workflow.create({ data: { businessId, createdById: userId, name, description, versions: { create: { version: 1, definition: definition as unknown as Prisma.InputJsonValue, checksum: checksum(definition) } } }, include: { versions: true } }); await recordOutboxEvent(tx, { dedupeKey: `workflow:${workflow.id}:created`, aggregateType: "workflow", aggregateId: workflow.id, eventType: "WorkflowCreated", tenantId: businessId, businessId, payload: { id: workflow.id, version: 1 } }); return workflow; }); }
export async function createWorkflowVersion(businessId: string, id: string, definition: WorkflowDefinition) { assertValid(definition); return prisma.$transaction(async (tx) => { const workflow = await tx.workflow.findFirst({ where: { id, businessId, status: { not: "ARCHIVED" } }, include: { versions: { orderBy: { version: "desc" }, take: 1 } } }); if (!workflow) throw ApiError.notFound("Workflow not found"); const version = (workflow.versions[0]?.version ?? 0) + 1; return tx.workflowVersion.create({ data: { workflowId: id, version, definition: definition as unknown as Prisma.InputJsonValue, checksum: checksum(definition) } }); }, { isolationLevel: "Serializable" }); }
export async function publishWorkflow(businessId: string, id: string, versionNumber?: number) { return prisma.$transaction(async (tx) => { const workflow = await tx.workflow.findFirst({ where: { id, businessId, status: { not: "ARCHIVED" } }, include: { versions: { orderBy: { version: "desc" } } } }); if (!workflow) throw ApiError.notFound("Workflow not found"); const version = versionNumber ? workflow.versions.find((item) => item.version === versionNumber) : workflow.versions[0]; if (!version) throw ApiError.notFound("Workflow version not found"); const definition = version.definition as unknown as WorkflowDefinition; assertValid(definition); const business = await tx.business.findUniqueOrThrow({ where: { id: businessId }, select: { timezone: true } }); const scheduleEnabled = isTimeTriggered(definition); await tx.workflowVersion.updateMany({ where: { workflowId: id, publishedAt: { not: null } }, data: { publishedAt: null } }); await tx.workflowVersion.update({ where: { id: version.id }, data: { publishedAt: new Date() } }); const updated = await tx.workflow.update({ where: { id }, data: { status: "PUBLISHED", scheduleEnabled, nextTriggerAt: scheduleEnabled ? nextWorkflowTriggerAt(definition, String(definition.trigger.config?.timezone ?? business.timezone ?? "UTC")) : null, scheduleLeaseOwner: null, scheduleLeaseExpiresAt: null }, include: { versions: { orderBy: { version: "desc" } } } }); await recordOutboxEvent(tx, { dedupeKey: `workflow:${id}:published:${version.version}`, aggregateType: "workflow", aggregateId: id, eventType: "WorkflowPublished", tenantId: businessId, businessId, payload: { id, version: version.version } }); return updated; }); }
export async function setWorkflowStatus(businessId: string, id: string, status: "PAUSED" | "PUBLISHED" | "ARCHIVED") { const workflow = await prisma.workflow.findFirst({ where: { id, businessId }, include: { versions: { where: { publishedAt: { not: null } }, take: 1 } } }); if (!workflow) throw ApiError.notFound("Workflow not found"); const version = workflow.versions[0]; if (status === "PUBLISHED" && !version) throw ApiError.conflict("Publish a valid workflow version before resuming"); let nextTriggerAt: Date | null = null; let scheduleEnabled = workflow.scheduleEnabled; if (status === "PUBLISHED" && version) { const definition = version.definition as unknown as WorkflowDefinition; const business = await prisma.business.findUniqueOrThrow({ where: { id: businessId }, select: { timezone: true } }); scheduleEnabled = isTimeTriggered(definition); nextTriggerAt = scheduleEnabled ? nextWorkflowTriggerAt(definition, String(definition.trigger.config?.timezone ?? business.timezone ?? "UTC")) : null; } return prisma.workflow.update({ where: { id }, data: { status, scheduleEnabled, nextTriggerAt, scheduleLeaseOwner: null, scheduleLeaseExpiresAt: null } }); }
export async function triggerWorkflowManually(businessId: string, id: string, input: unknown) { const workflow = await prisma.workflow.findFirst({ where: { id, businessId, status: "PUBLISHED" }, include: { versions: { where: { publishedAt: { not: null } }, take: 1 } } }); if (!workflow?.versions[0]) throw ApiError.conflict("Workflow is not published"); const definition = workflow.versions[0].definition as unknown as WorkflowDefinition; if (definition.trigger.type !== "MANUAL") throw ApiError.conflict("Workflow does not support manual triggering"); return startWorkflowExecution({ workflowId: id, version: workflow.versions[0].version, businessId, idempotencyKey: `${id}:${workflow.versions[0].version}:manual:${crypto.randomUUID()}`, state: { manualInput: input, automationLineage: [id] } as Prisma.InputJsonValue }); }
export function listWorkflowExecutions(businessId: string, input: { status?: string; take?: number } = {}) { return prisma.workflowExecution.findMany({ where: { businessId, ...(input.status ? { status: input.status as never } : {}) }, include: { workflow: { select: { id: true, name: true } }, history: { orderBy: { createdAt: "desc" }, take: 10 } }, orderBy: { createdAt: "desc" }, take: Math.min(input.take ?? 50, 100) }); }
export async function controlExecution(businessId: string, id: string, action: "pause" | "resume" | "cancel" | "retry") {
  const execution = await prisma.workflowExecution.findFirst({ where: { id, businessId } }); if (!execution) throw ApiError.notFound("Workflow execution not found");
  let changed = 0;
  if (action === "pause") changed = (await pauseWorkflowExecution(businessId, id)).count;
  else if (action === "resume") changed = (await resumeWorkflowExecution(businessId, id)).count;
  else if (action === "cancel") changed = (await cancelWorkflowExecution(businessId, id, "cancelled_by_user")).count;
  else changed = await prisma.$transaction(async (tx) => { const result = await tx.workflowExecution.updateMany({ where: { id, businessId, status: { in: ["FAILED", "CANCELLED"] } }, data: { status: "PENDING", retryCount: 0, nextAttemptAt: new Date(), scheduledFor: new Date(), completedAt: null, cancelledAt: null, cancellationReason: null, lastError: null, leaseOwner: null, leaseExpiresAt: null } }); if (result.count) await tx.workflowExecutionEvent.create({ data: { executionId: id, businessId, type: "RETRIED_BY_USER" } }); return result.count; });
  if (!changed) throw ApiError.conflict(`Workflow execution cannot ${action} from ${execution.status}`);
  return prisma.workflowExecution.findUniqueOrThrow({ where: { id } });
}
export async function workflowAnalytics(businessId: string, days = 30) {
  const since = new Date(Date.now() - days * 86_400_000);
  const [byStatus, events, rows] = await Promise.all([
    prisma.workflowExecution.groupBy({ by: ["status"], where: { businessId, createdAt: { gte: since } }, _count: { _all: true } }),
    prisma.workflowExecutionEvent.groupBy({ by: ["type"], where: { businessId, createdAt: { gte: since } }, _count: { _all: true }, _sum: { retryCount: true } }),
    prisma.workflowExecution.findMany({ where: { businessId, createdAt: { gte: since } }, select: { workflowId: true, status: true, createdAt: true, startedAt: true, completedAt: true, retryCount: true, lastError: true, workflow: { select: { name: true } } } }),
  ]);
  const total = rows.length, completed = rows.filter((row) => row.status === "COMPLETED").length, failures = rows.filter((row) => row.status === "FAILED" || row.status === "CANCELLED").length;
  const average = (values: number[]) => values.length ? values.reduce((sum, value) => sum + value, 0) / values.length : null;
  const queueWaits = rows.flatMap((row) => row.startedAt ? [Math.max(0, row.startedAt.getTime() - row.createdAt.getTime())] : []);
  const processingTimes = rows.flatMap((row) => row.startedAt && row.completedAt ? [Math.max(0, row.completedAt.getTime() - row.startedAt.getTime())] : []);
  const category = (message: string | null) => !message ? "unknown" : /timeout/i.test(message) ? "timeout" : /cancel/i.test(message) ? "cancelled" : /provider|gateway|network/i.test(message) ? "provider" : /valid|config/i.test(message) ? "validation" : "runtime";
  const failureCategories: Record<string, number> = {}; for (const row of rows.filter((item) => item.status === "FAILED" || item.status === "CANCELLED")) failureCategories[category(row.lastError)] = (failureCategories[category(row.lastError)] ?? 0) + 1;
  const performance = new Map<string, { workflowId: string; name: string; triggered: number; completed: number; failed: number; retries: number }>();
  for (const row of rows) { const item = performance.get(row.workflowId) ?? { workflowId: row.workflowId, name: row.workflow.name, triggered: 0, completed: 0, failed: 0, retries: 0 }; item.triggered += 1; item.completed += row.status === "COMPLETED" ? 1 : 0; item.failed += row.status === "FAILED" || row.status === "CANCELLED" ? 1 : 0; item.retries += row.retryCount; performance.set(row.workflowId, item); }
  return { windowDays: days, totals: Object.fromEntries(byStatus.map((row) => [row.status, row._count._all])), triggerCount: total, throughputPerDay: total / days, successRate: total ? completed / total : null, failureRate: total ? failures / total : null, averageQueueWaitMs: average(queueWaits), averageProcessingTimeMs: average(processingTimes), averageExecutionTimeMs: average(processingTimes), events: Object.fromEntries(events.map((row) => [row.type, row._count._all])), actionCount: events.filter((row) => row.type === "ACTION_COMPLETED").reduce((sum, row) => sum + row._count._all, 0), retries: rows.reduce((sum, row) => sum + row.retryCount, 0), failureCategories, workflowPerformance: [...performance.values()].map((item) => ({ ...item, successRate: item.triggered ? item.completed / item.triggered : null })) };
}
