import { createHash } from "node:crypto";
import { prisma } from "../prisma.js";
import { ApiError } from "../errors.js";

export type AITask = "classification" | "conversation" | "scheduling" | "extraction";
export interface AIProvider { id: string; invoke(input: { model: string; task: AITask; prompt: string; context: unknown; tools: Array<{ name: string; schema: object }> }): Promise<{ output: unknown; confidence?: number; usage?: { inputTokens?: number; outputTokens?: number; reasoningTokens?: number }; toolRequests?: Array<{ name: string; arguments: unknown }> }> }
const providers = new Map<string, AIProvider>();
export function registerAIProvider(provider: AIProvider) { providers.set(provider.id, provider); }
export function clearAIProviders() { providers.clear(); }
const injection = /ignore\s+(all\s+)?(previous|above)|system\s+prompt|reveal\s+(secret|instruction)|act\s+as/iu;
export function assertSafeAIInput(value: string) { if (injection.test(value)) throw ApiError.badRequest("Unsafe prompt content detected"); }
export async function routeAI(input: { businessId: string; task: AITask; prompt: string; context: unknown; customerId?: string; conversationId?: string; workflowExecutionId?: string; correlationId?: string; causationId?: string; promptVersion: string; promptChecksum?: string; requiredCapability?: string }) {
  assertSafeAIInput(input.prompt); const models = await prisma.aIModelRegistry.findMany({ where: { status: "ACTIVE", healthStatus: { in: ["HEALTHY", "UNKNOWN"] } } }); const selected = models.find(row => !input.requiredCapability || Array.isArray(row.capabilities) && row.capabilities.includes(input.requiredCapability)); if (!selected) throw ApiError.serviceUnavailable("No approved AI model is available"); const provider = providers.get(selected.provider); if (!provider) throw ApiError.serviceUnavailable("AI provider adapter is not configured"); const started = Date.now(); const checksum = input.promptChecksum ?? createHash("sha256").update(input.prompt).digest("hex");
  try { const result = await provider.invoke({ model: selected.model, task: input.task, prompt: input.prompt, context: input.context, tools: [] }); const ledger = await prisma.aIInvocationLedger.create({ data: { businessId: input.businessId, customerId: input.customerId, conversationId: input.conversationId, workflowExecutionId: input.workflowExecutionId, provider: selected.provider, model: selected.model, modelVersion: selected.version, promptVersion: input.promptVersion, promptChecksum: checksum, inputTokens: result.usage?.inputTokens, outputTokens: result.usage?.outputTokens, reasoningTokens: result.usage?.reasoningTokens, latencyMs: Date.now()-started, correlationId: input.correlationId, causationId: input.causationId, confidence: result.confidence, safetyResult: "PASSED", outcome: "COMPLETED", toolRequests: result.toolRequests ?? [] } }); return { ...result, provider: selected.provider, model: selected.model, ledgerId: ledger.id }; } catch (error) { await prisma.aIInvocationLedger.create({ data: { businessId: input.businessId, customerId: input.customerId, conversationId: input.conversationId, workflowExecutionId: input.workflowExecutionId, provider: selected.provider, model: selected.model, modelVersion: selected.version, promptVersion: input.promptVersion, promptChecksum: checksum, latencyMs: Date.now()-started, correlationId: input.correlationId, causationId: input.causationId, safetyResult: "FAILED", outcome: "FAILED" } }); throw error; }
}
export async function businessAIContext(businessId: string, customerId?: string) { const [business, customer, services, appointments] = await Promise.all([prisma.business.findUnique({ where: { id: businessId }, select: { name:true, industry:true, timezone:true, workingHours:true, defaultServices:true, preferredTone:true } }), customerId ? prisma.customer.findFirst({ where: { id: customerId, businessId }, select: { name:true, notes:true, customFields:true } }) : null, prisma.serviceOffering.findMany({ where: { businessId, active: true }, take: 30 }), customerId ? prisma.appointment.findMany({ where: { businessId, customerId }, orderBy: { startsAt: "desc" }, take: 10 }) : []]); return { business, customer, services, appointments }; }
