import { createHash } from "node:crypto";
import { z } from "zod";
import { prisma } from "../prisma.js";
import { ApiError } from "../errors.js";
import { getAction, validateActionConfig } from "../automation/actionRegistry.js";
import { businessAIContext, routeAI } from "./aiGateway.js";
import { renderPublishedPrompt } from "./promptRegistry.js";

export const AI_RUN_STATES = ["RECEIVED","CONTEXT_READY","CLASSIFIED","PLANNED","TOOL_SELECTION","TOOL_EXECUTION","DRAFT_RESPONSE","HUMAN_APPROVAL","RESPONDING","COMPLETED","ESCALATED","FAILED"] as const;
const allowed = new Set(["UPDATE_CUSTOMER","UPDATE_LEAD","UPDATE_APPOINTMENT","CREATE_TASK","ASSIGN_STAFF","ESCALATE","PAUSE_WORKFLOW","RESUME_WORKFLOW"]);
export async function executeAITool(input: { businessId: string; runId: string; name: string; config: unknown; idempotencyKey: string; approved: boolean }) { if (!input.approved) throw ApiError.forbidden("AI tool execution requires approval"); if (!allowed.has(input.name)) throw ApiError.forbidden("AI tool is not allowlisted"); const config = z.record(z.string(), z.unknown()).parse(input.config); const errors = validateActionConfig(input.name, config); if (errors.length) throw ApiError.badRequest("Invalid AI tool request", errors); const run = await prisma.aIConversationRun.findFirst({ where: { id: input.runId, businessId: input.businessId } }); if (!run) throw ApiError.notFound("AI conversation run not found"); const handler = getAction(input.name); if (!handler) throw ApiError.serviceUnavailable("AI tool handler is not configured"); const existing = await prisma.aIInvocationLedger.findFirst({ where: { businessId: input.businessId, correlationId: input.idempotencyKey, outcome: "TOOL_COMPLETED" } }); if (existing) return { replayed: true }; const result = await handler({ businessId: input.businessId, executionId: `ai:${run.id}`, nodeId: input.name, input: run.state, idempotencyKey: input.idempotencyKey, signal: AbortSignal.timeout(30_000) }, config); await prisma.aIInvocationLedger.create({ data: { businessId: input.businessId, customerId: run.customerId, conversationId: run.conversationId, provider: "tool-broker", model: input.name, promptVersion: "tool-v1", promptChecksum: createHash("sha256").update(input.name).digest("hex"), correlationId: input.idempotencyKey, safetyResult: "PASSED", outcome: "TOOL_COMPLETED", toolRequests: { name: input.name } } }); return result; }
export async function advanceAIConversation(input: { businessId: string; runId: string; prompt: string; mode?: "DRAFT" | "APPROVAL" | "AUTONOMOUS" }) { const run = await prisma.aIConversationRun.findFirst({ where: { id: input.runId, businessId: input.businessId } }); if (!run) throw ApiError.notFound("AI conversation run not found"); const transitions = ["CONTEXT_READY","CLASSIFIED","PLANNED","TOOL_SELECTION","DRAFT_RESPONSE"] as const; for (const status of transitions) await prisma.aIConversationRun.update({ where: { id: run.id }, data: { status } }); const context = await businessAIContext(input.businessId, run.customerId ?? undefined); const resolved = await renderPublishedPrompt({ templateKey: "conversation.orchestrator", businessId: input.businessId, values: { message: input.prompt } }); const response = await routeAI({ businessId: input.businessId, customerId: run.customerId ?? undefined, conversationId: run.conversationId, task: "conversation", prompt: resolved.rendered.prompt, context, promptVersionId: resolved.versionId, requiredCapability: resolved.requiredCapability ?? "conversation" }); const next = input.mode === "APPROVAL" ? "HUMAN_APPROVAL" : "COMPLETED"; return prisma.aIConversationRun.update({ where: { id: run.id }, data: { status: next, mode: input.mode ?? run.mode, state: { context, response: response.output, promptVersionId: resolved.versionId, ledgerId: response.ledgerId } as never } }); }
